# Prerequisites

In [4]:
%cd /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/
#import sys
#print(sys.version)
#!python3 --version

/dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5

/dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [3]:
!pip uninstall transformers -y
!pip install transformers==4.36.2  datasets==4.3.0 accelerate==0.27.2
!pip install torch==2.9.1
!pip install ipywidgets==8.1.7
!pip install python-dotenv==1.2.1 pickleshare==0.7.5

WARNING: Skipping transformers as it is not installed.
Collecting transformers==4.36.2
  Using cached transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
Collecting datasets==4.3.0
  Using cached datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Collecting accelerate==0.27.2
  Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)
Collecting filelock (from transformers==4.36.2)
  Downloading filelock-3.28.0-py3-none-any.whl.metadata (2.0 kB)
Collecting huggingface-hub<1.0,>=0.19.3 (from transformers==4.36.2)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from transformers==4.36.2) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (6.0.2)
Collecting regex!=2019.12.17 (from transformers==4.36.2)
  Using cached regex-2026.4.4-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (2.32.3)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.36.2)
  Using cached tokenizers-0.15.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.3.1 (from transformers==4.36.2)
  Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: tqdm>=4.27 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from transformers==4.36.2) (4.67.3)
Collecting pyarrow>=21.0.0 (from datasets==4.3.0)
  Using cached pyarrow-23.0.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Collecting dill<0.4.1,>=0.3.0 (from datasets==4.3.0)
  Using cached dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets==4.3.0) (2.2.2)
Requirement already satisfied: httpx<1.0.0 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from datasets==4.3.0) (0.28.1)
Collecting xxhash (from datasets==4.3.0)
  Using cached xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets==4.3.0)
  Using cached multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (2024.6.1)
Requirement already satisfied: psutil in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from accelerate==0.27.2) (7.2.2)
Collecting torch>=1.10.0 (from accelerate==0.27.2)
  Using cached torch-2.11.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (29 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (3.10.1)
Requirement already satisfied: anyio in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from httpx<1.0.0->datasets==4.3.0) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets==4.3.0) (2024.7.4)
Requirement already satisfied: httpcore==1.* in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from httpx<1.0.0->datasets==4.3.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets==4.3.0) (3.7)
Requirement already satisfied: h11>=0.16 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from httpcore==1.*->httpx<1.0.0->datasets==4.3.0) (0.16.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2)
  Using cached hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (2.0.7)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (70.3.0)
Collecting sympy>=1.13.3 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.1.4)
Collecting cuda-toolkit==13.0.2 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached cuda_bindings-13.2.0-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Collecting nvidia-cudnn-cu13==9.19.0.56 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.0 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.28.9 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.6.0 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached triton-3.6.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.0.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from pandas->datasets==4.3.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets==4.3.0) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets==4.3.0) (2024.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (2.3.5)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (4.0.3)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings<14,>=13.0.3->torch>=1.10.0->accelerate==0.27.2)
  Downloading cuda_pathfinder-1.5.3-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==4.3.0) (1.16.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.27.2)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from anyio->httpx<1.0.0->datasets==4.3.0) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.27.2) (2.1.5)
Using cached transformers-4.36.2-py3-none-any.whl (8.2 MB)
Using cached datasets-4.3.0-py3-none-any.whl (506 kB)
Using cached accelerate-0.27.2-py3-none-any.whl (279 kB)
Using cached dill-0.4.0-py3-none-any.whl (119 kB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached multiprocess-0.70.16-py310-none-any.whl (134 kB)
Using cached pyarrow-23.0.1-cp310-cp310-manylinux_2_28_x86_64.whl (47.6 MB)
Using cached regex-2026.4.4-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (793 kB)
Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
Using cached tokenizers-0.15.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Using cached torch-2.11.0-cp310-cp310-manylinux_2_28_x86_64.whl (530.6 MB)
Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl (2.4 kB)
Using cached nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl (366.1 MB)
Using cached nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl (169.9 MB)
Using cached nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl (196.5 MB)
Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
Using cached triton-3.6.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.1 MB)
Using cached nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Downloading filelock-3.28.0-py3-none-any.whl (39 kB)
Using cached xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
Using cached cuda_bindings-13.2.0-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.3 MB)
Using cached hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Downloading cuda_pathfinder-1.5.3-py3-none-any.whl (49 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: nvidia-cusparselt-cu13, mpmath, cuda-toolkit, xxhash, triton, sympy, safetensors, regex, pyarrow, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, nvidia-cublas, hf-xet, filelock, dill, cuda-pathfinder, nvidia-cusparse, nvidia-cufft, nvidia-cudnn-cu13, multiprocess, huggingface-hub, cuda-bindings, tokenizers, nvidia-cusolver, transformers, datasets, torch, accelerate
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 16.1.0
    Uninstalling pyarrow-16.1.0:
      Successfully uninstalled pyarrow-16.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf 24.6.0 requires pyarrow<16.2.0a0,>=16.1.0, but you have pyarrow 23.0.1 which is incompatible.
Successfully installed accelerate-0.27.2 cuda-bindings-13.2.0 cuda-pathfinder-1.5.3 cuda-toolkit-13.0.2 datasets-4.3.0 dill-0.4.0 filelock-3.28.0 hf-xet-1.4.3 huggingface-hub-0.36.2 mpmath-1.3.0 multiprocess-0.70.16 nvidia-cublas-13.1.0.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.19.0.56 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.0 nvidia-nccl-cu13-2.28.9 nvidia-nvjitlink-13.0.88 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 pyarrow-23.0.1 regex-2026.4.4 safetensors-0.7.0 sympy-1.14.0 tokenizers-0.15.2 torch-2.11.0 transformers-4.36.2 triton-3.6.0 xxhash-3.6.0
Collecting torch==2.9.1
  Using cached torch-2.9.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.28.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /dss/dsshome1/03/ge87wod2/.local/lib/python3.10/site-packages (from torch==2.9.1) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2024.6.1)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch==2.9.1)
  Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch==2.9.1)
  Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch==2.9.1)
  Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch==2.9.1)
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch==2.9.1)
  Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch==2.9.1)
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch==2.9.1)
  Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch==2.9.1)
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch==2.9.1)
  Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch==2.9.1)
  Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch==2.9.1)
  Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.3.20 (from torch==2.9.1)
  Using cached nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch==2.9.1)

Collecting torch==2.9.1
  Using cached torch-2.9.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (4.12.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2024.5.0)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch==2.9.1)
  Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch==2.9.1)
  Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch==2.9.1)
  Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch==2.9.1)
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch==2.9.1)
  Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch==2.9.1)
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch==2.9.1)
  Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch==2.9.1)
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch==2.9.1)
  Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch==2.9.1)
  Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch==2.9.1)
  Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.3.20 (from torch==2.9.1)
  Using cached nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch==2.9.1)
  Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch==2.9.1)
  Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch==2.9.1)
  Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.5.1 (from torch==2.9.1)
  Using cached triton-3.5.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch==2.9.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.9.1) (2.1.5)
Using cached torch-2.9.1-cp310-cp310-manylinux_2_28_x86_64.whl (899.8 MB)
Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.3 MB)
Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
Using cached nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (124.7 MB)
Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Using cached triton-3.5.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (170.3 MB)
Installing collected packages: nvidia-cusparselt-cu12, triton, nvidia-nvtx-cu12, nvidia-nvshmem-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: torch
    Found existing installation: torch 2.11.0
    Uninstalling torch-2.11.0:
      Successfully uninstalled torch-2.11.0
Successfully installed nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-cusparselt-cu12-0.7.1 nvidia-nccl-cu12-2.27.5 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvshmem-cu12-3.3.20 nvidia-nvtx-cu12-12.8.90 torch-2.9.1 triton-3.5.1
Collecting ipywidgets==8.1.7
  Using cached ipywidgets-8.1.7-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (8.21.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (5.9.0)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets==8.1.7)
  Using cached widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets==8.1.7)
  Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.19.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (3.0.46)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (2.18.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.6.3)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (1.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (4.7.0)

Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.7) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.1.7) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.4.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (1.16.0)
Using cached ipywidgets-8.1.7-py3-none-any.whl (139 kB)
Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
Using cached widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets
Successfully installed ipywidgets-8.1.7 jupyterlab_widgets-3.0.16 widgetsnbextension-4.0.15
Collecting python-dotenv==1.2.1
  Using cached python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Collecting pickleshare==0.7.5
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl.metadata (1.5 kB)
Using cached python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Installing collected packages: pickleshare, python-dotenv
Successfully installed pickleshare-0.7.5 python-dotenv-1.2.1

In [1]:
from dotenv import load_dotenv
import os

load_dotenv("../../.env",override=True)

HF_TOKEN = os.getenv("HF_TOKEN")

#print("HF_TOKEN: ", HF_TOKEN)

 # source: https://huggingface.co/docs/transformers/v4.28.1/tasks/summarization
from huggingface_hub import login
login(HF_TOKEN)

ModuleNotFoundError: No module named 'dotenv'

# Continued Pre-training

In [9]:
# from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments
from datasets import load_dataset
import random
# get tokenizer and sentinal tokens for masking
tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
extra_id_0 = tokenizer.convert_tokens_to_ids("<extra_id_0>")
extra_id_1 = tokenizer.convert_tokens_to_ids("<extra_id_1>")
print(extra_id_0, extra_id_1)

# Load pre-trained model
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, return_tensors="pt")
random.seed(10)
# Masking by processing the data line by line
def preprocess_function(examples): # receives unmasked sentence as input
    # get input sentence
    input_ids_batch = []
    attention_mask_batch = []
    labels_batch = []
    
    inputs_batch = examples["input"]
    for inputs in inputs_batch:
        inputs = inputs.strip()
        model_inputs = tokenizer(inputs)
        input_ids = model_inputs.input_ids
        attention_mask = model_inputs.attention_mask
        # print(input_ids, attention_mask, len(input_ids),len(attention_mask))
        
        # mask 15% of the bytes randomly in the tokenized sentence leaving out bordering bytes.
        length = round(len(input_ids) * 0.25) # mask 20% of bytes (T5 and mT5 do that for tokens)
        max_start_index = len(input_ids) - length -1  # 2 bytes + eos byte-> 3 - 1x eos - 1= 1 -> index 0 or 1 possible, eos does not count to bytes
        start_index = random.randrange(1, max_start_index -1) # leave out first bytes and last byte "full stop: 49"
        exclusive_end_index = start_index + length
        masked_input_ids = (  input_ids[:start_index] + [extra_id_0] + input_ids[exclusive_end_index :]  )
        masked_labels_ids = ([extra_id_0]+ input_ids[start_index: exclusive_end_index] +[extra_id_1])
        
        # update attention mask and labels and add to batch
        attention_mask = [1] * len(masked_input_ids)
        input_ids_batch.append(masked_input_ids)
        attention_mask_batch.append(attention_mask)
        labels_batch.append(masked_labels_ids)
    return {
        "input_ids": input_ids_batch,
        "attention_mask": attention_mask_batch,
        "labels": labels_batch
    }

# load dataset
lang = "csb-pol-sent"
train_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json_or_tsv/data/{lang}_trn.tsv"
eval_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json_or_tsv/data/{lang}_dev.tsv"
dataset = load_dataset("csv", delimiter="\t",column_names=["input"],data_files={"train": train_path,"validation": eval_path},quoting=3) # disable quote parsing
tokenized_dataset = dataset.map(preprocess_function, batched=True)
print(tokenized_dataset["train"]["input_ids"])
print(tokenized_dataset)

#training_args = Seq2SeqTrainingArguments(
#    output_dir="./byt5_small/csb-pol-byte-25perc-sent",
#    evaluation_strategy="epoch",
#    learning_rate=5e-5,
#    per_device_train_batch_size=16,
#    per_device_eval_batch_size=16,
#    weight_decay=0.01,
#    save_total_limit=3,
#    num_train_epochs=4,
#    predict_with_generate=True,
#    # save_strategy="epoch",
#    fp16=False,# did not work with True #change to bf16=True for XPU 
#    #bf16 = True, # performance was best without setting fp16 or bf16 to true
#    push_to_hub=True,
#    warmup_steps = 500,
#    # load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification
#)
# Training arguments


output_model = "csb-pol-25perc-oldpar-byte-sent"
training_args = TrainingArguments (
    output_dir="./byt5_small/"+output_model,
    overwrite_output_dir=True,
    num_train_epochs=4,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=5e-5,
    weight_decay=0.01,
    evaluation_strategy = "epoch",
    #predict_with_generate=True,
   # save_steps=10_000,
    save_total_limit=3,
)

# Trainer
#trainer = Seq2SeqTrainer(
#    model=model,
#    args=training_args,
#    train_dataset=tokenized_dataset["train"],
#    eval_dataset=tokenized_dataset["validation"],
#    data_collator=data_collator,
#    tokenizer=tokenizer,
#)

# Pretrain the model
trainer.train()
trainer.push_to_hub()

259 260
Column([[87, 104, 117, 259, 113, 199, 136, 35, 105, 108, 125, 124, 102, 125, 113, 198, 172, 106, 198, 181, 35, 122, 198, 174, 102, 107, 198, 181, 122, 100, 113, 108, 198, 183, 49, 1], [74, 117, 199, 136, 103, 114, 111, 35, 109, 104, 35, 198, 181, 101, 118, 100, 103, 125, 114, 113, 124, 35, 113, 100, 35, 106, 198, 182, 259, 108, 104, 119, 104, 122, 102, 125, 108, 49, 1], [198, 149, 113, 35, 122, 35, 118, 122, 198, 181, 109, 108, 112, 35, 102, 125, 259, 102, 107, 102, 104, 49, 1], [68, 111, 115, 104, 109, 118, 110, 198, 183, 35, 198, 181, 117, 114, 106, 104, 113, 104, 125, 100, 35, 118, 115, 117, 100, 122, 108, 200, 133, 100, 35, 117, 198, 174, 118, 125, 113, 259, 114, 103, 125, 198, 172, 200, 133, 114, 122, 108, 102, 107, 35, 74, 198, 182, 117, 49, 1], [80, 198, 259, 125, 108, 35, 122, 104, 35, 90, 104, 118, 119, 117, 125, 198, 172, 103, 113, 124, 35, 72, 198, 188, 117, 114, 115, 108, 104, 35, 198, 188, 113, 108, 122, 104, 117, 118, 124, 119, 104, 119, 47, 35, 109, 100, 102, 125, 108, 35, 113, 114, 118, 124, 35, 103, 125, 124, 118, 198, 183, 35, 109, 104, 106, 198, 181, 35, 112, 108, 114, 113, 114, 49, 1]])
DatasetDict({
    train: Dataset({
        features: ['input', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 9000
    })
    validation: Dataset({
        features: ['input', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})

AttributeError: 'TrainingArguments' object has no attribute 'generation_config'

In [2]:
# from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset
import math, random
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
import torch
tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
# tokenized_dataset = dataset.map(preprocess_function, batched=True)
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")

sentinal_token_1 = tokenizer("<extra_id_0>", return_tensors="pt").to(model.device).input_ids # skip eos value "1"
sentinal_token_2 = tokenizer("<extra_id_1>", return_tensors="pt").to(model.device).input_ids # skip eos value "1"
extra_id_0 = int(sentinal_token_1[0][0])
extra_id_1 = int(sentinal_token_2[0][0])
print(extra_id_0, extra_id_1)

model_inputs = tokenizer("我是一条狗.")
#model_inputs = tokenizer(".")
input_ids = model_inputs.input_ids
attention_mask = model_inputs.attention_mask
print(input_ids, attention_mask, len(input_ids),len(attention_mask))

# mask 15% of the bytes in the tokenized sentence
length = round(len(input_ids) * 0.15) # mask 15% of character (T5 and mT5 do that for tokens)
max_start_index = len(input_ids) - length  # 2 chars -> 2-1=1 -> index 0 or 1 possible
random.seed(10)
start_index = random.randrange(1, max_start_index ) # leave out first and last character
exclusive_end_index = start_index + length
masked_input_ids = (  input_ids[:start_index] + [extra_id_0] + input_ids[exclusive_end_index :]  )
masked_labels_ids = ([extra_id_0]+ input_ids[start_index: exclusive_end_index] +[extra_id_1])

# update attention mask and labels
attention_mask = [1] * len(masked_input_ids)
model_inputs["attention_mask"] = attention_mask
model_inputs["labels"] = masked_labels_ids

print(input_ids, masked_input_ids,masked_labels_ids)
print(model_inputs)

ModuleNotFoundError: No module named 'datasets'

In [1]:
# from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

# Load domain-specific text (replace with your own corpus)
lang = "csb-pol-sent"
train_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json_or_tsv/data/{lang}_trn.tsv"
eval_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json_or_tsv/data/{lang}_dev.tsv"
dataset = load_dataset("csv", delimiter="\t",column_names=["input","labels"],data_files={"train": train_path,"validation": eval_path},quoting=3) # disable quote parsing


# Tokenizing
def preprocess_function(examples):
    inputs = examples["input"]
    model_inputs = tokenizer(inputs)
    labels = tokenizer(text_target=examples["labels"],padding=True) # same length irrelevant here, so no truncation or padding
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs




tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
tokenized_dataset = dataset.map(preprocess_function, batched=True)




# Load pre-trained model
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, return_tensors="pt")
# Training arguments
training_args = TrainingArguments (
    output_dir="./byt5_small/"+lang+"-8epochs",
    overwrite_output_dir=True,
    num_train_epochs=8,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    evaluation_strategy = "epoch",
    #predict_with_generate=True,
   # save_steps=10_000,
    save_total_limit=3,
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
)

# Pretrain the model
trainer.train()
trainer.push_to_hub()

/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
2026-04-12 13:26:29.946699: I tensorflow/core/platform/cpu_feature_guard.cc:211] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Map:   0%|          | 0/9000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

KeyboardInterrupt:

# Fine-tuning small pre-trained ByT5 model using dataset

In [6]:
LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"]
LANGS = LANGS[-2:]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul-language-code","mul-language-word"]
LANGS = ["mul-language-code"]
LANGS = ["pol"]
#LANGS = ["slavic-family"]
#LANGS = ["slk"] # ces, slk, dsb
CHECKPOINT = "livles/csb-pol-byte-25perc-sent"
#CHECKPOINT = "google/byt5-small"


PATH_JSON_DATA = "../preprocessing/preprocessing_to_json_or_tsv/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang.split("-")[0] + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # -

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    checkpoint = CHECKPOINT
    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/csb-pol-byte-25perc-sent-"+lang,
        evaluation_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=4,
        predict_with_generate=True,
        # save_strategy="epoch",
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        # load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,   
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Inflect zacny | ADJ;ACC(SG,FEM)', 'target': 'zacną'}

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[125, 100, 102, 113, 199, 136, 1]

config.json:   0%|          | 0.00/837 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/142 [00:00<?, ?B/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

# Fine-Tuning with more epochs

In [8]:
!rm -rf /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/byt5_small/*
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]

PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # 

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/"+lang+"_13epochs",
        eval_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=13,
        predict_with_generate=True,
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        save_strategy="epoch",
        load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification,
        greater_is_better=False,
        metric_for_best_model="eval_loss"
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Navajo: Inflect náʼáłkad | V;IND;PFV;NOM(1,GRPL)', 'target': 'ńdaʼiilkad'}
DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[200, 135, 103, 100, 205, 191, 108, 108, 111, 110, 100, 103, 1]

/tmp/ipykernel_3401446/2533773261.py:79: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

# Inference

In [8]:
# SETTINGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"] + ["mul_2","ote","pol","amh"] + ["mul-language-code","mul-language-word"]
SETTINGS = ["mul"]
SETTINGS = ["5lang-sample"]
BASE_TEST_LANGUAGES_OF_SETTING = {"slavic":["csb"],"slavic-word":["csb"],"slavic-family":["pol","ces","csb","dsb","slk"],"5lang-sample":["deu","nav","klr","amh","grc"],"5lang-sample_16epochs":["amh"],
                                 "sme-15ksamples":["sme"],"sme-20ksamples":["sme"],"klr-15ksamples":["klr"],"klr-20ksamples":["klr"],"slavic-distant-word": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],"slavic-distant-word-or-family": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],
                                  "csb-pol":["csb","pol"], "csb-pol-sent-pol": ["csb", "pol"], "csb-pol-sent-6epochs-pol": ["csb", "pol"],
                                  "csb-sent-6epochs-pol": ["csb", "pol"], "dsb":["dsb"],"slk":["slk"],"ces":["ces"],"grc":["grc"],"sme":["sme"],"klr":["klr"],"nav":["nav"],
                                  "mul-language-word":["klr"],"pol":["csb"],"amh":["amh"],"mul_2":["sme","klr","grc"],"csb-pol-byte-sent-pol":["csb"],"csb-pol-byte-20perc-sent-pol":["csb"],"csb-pol-byte-25perc-sent-pol":["csb"]
                                 }
CODES = {"slavic": [""],"slavic-word":["-lang-word"],"slavic-family":["-family","-lang-word","-word-or-family"],"5lang-sample":["-lang-word"],"5lang-sample_16epochs":["-lang-word"],"5lang-sample_13epochs":["-lang-word"],"sme-15ksamples":[""],"sme-20ksamples":[""],"klr-15ksamples":[""],"klr-20ksamples":[""],"slavic-distant-word":["-lang-word"],"slavic-distant-word-or-family":["-lang-word"],"csb-pol":[""],"csb-pol-sent-pol":[""],"csb-pol-sent-6epochs-pol": [""],"csb-sent-6epochs-pol": [""],"ces":[""],"slk":[""],"dsb":[""],"grc":[""],"sme":[""],"klr":[""],
        "mul-language-word":["-lang-word"],"nav":[""],"pol":[""],"amh":[""],"mul_2":[""],"csb-pol":[""],"csb-pol-byte-sent-pol":[""],"csb-pol-byte-20perc-sent-pol":[""],"csb-pol-byte-25perc-sent-pol":[""]}
SETTINGS = ["slavic","slavic-word"]
SETTINGS = ["sme-15ksamples","sme-20ksamples","klr-15ksamples","klr-20ksamples","5lang-sample_16epochs"]
SETTINGS = ["slavic-distant-word-or-family"]
SETTINGS = ["csb-sent-6epochs-pol"]
SETTINGS = ["slavic"]
SETTINGS = ["csb-pol-byte-25perc-sent-pol"]
#SETTINGS = ["mul-language-word"]
#TEST_LANGS_OLD = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] 
#TEST_LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] + ["ote","pol","amh","csb"]
#lang5_LANGS = ["deu","nav","klr","amh","grc"]
#lang_code = ""
ERROR_ANALYSIS_PATH = "/dss/dsshome1/03/ge87wod2/morphological-inflection/error_analysis_lucy/byt5"
for lang_setting in SETTINGS:
    test_langs = BASE_TEST_LANGUAGES_OF_SETTING[lang_setting]
    #if lang_setting == "mul": LANG_CODES = ["-language-word","-language-code",""] # test with no language code/word too
    #else: LANG_CODES = [""]
    #for lang_code in LANG_CODES:
        #if lang_setting in ( "deu_eng", "mul") and lang_code == "": test_langs = TEST_LANGS_OLD
        #elif lang_setting in ["mul_2","mul"]: test_langs = TEST_LANGS # test multilingual model on all languages it was trained on + Kashubian
        #elif lang_setting == "5lang-sample": test_langs = lang5_LANGS
        #elif lang_setting == "pol": test_langs = ["pol","csb"] # test Polish model on Kashubian also
        #else: 
    for lang_code in CODES[lang_setting]:
        for test_lang in test_langs:
            import torch
            from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
            PRETRAINED_MODEL = "google/byt5-small"
            FINETUNED_MODEL ="livles/"+lang_setting
            #FINETUNED_MODEL ="./byt5_small/"+lang_setting + lang_code
            MODEL = FINETUNED_MODEL
            print(MODEL)
            tokenizer = AutoTokenizer.from_pretrained(
                FINETUNED_MODEL,
            )
            model = AutoModelForSeq2SeqLM.from_pretrained(
                FINETUNED_MODEL,
            torch_dtype=torch.float16,
            device_map="auto"
            )
            from datasets import load_dataset
            OUT_DIR = "output_byt5_small/" + lang_setting + "/" 
            PATH_TO_JSON_TEST_FILE = "../preprocessing/preprocessing_to_json_or_tsv/data/" + test_lang + lang_code+ "_tst.json"
            #ERROR_ANALYSIS_PATH = "/dss/dsshome1/03/ge87wod2/morphological-inflection/error_analysis_lucy/byt5/" + lang_setting + "/" + test_lang + lang_code + ".errors"
            print("test file: ",PATH_TO_JSON_TEST_FILE)
            PATH_TO_ORIG_TEST_FILE = "/dss/dsshome1/03/ge87wod2/morphological-inflection/2023InflectionST/part1/data/" + test_lang + ".tst"
            from pathlib import Path
            Path(OUT_DIR).mkdir(parents=True, exist_ok=True)
            with open (OUT_DIR + test_lang + lang_code + "_byt5-small.out","w") as out_file, open (PATH_TO_ORIG_TEST_FILE, "r") as test_file: #, open (ERROR_ANALYSIS_PATH, "w") as error_file
                dataset = load_dataset("json",data_files={"test":PATH_TO_JSON_TEST_FILE})
                covered_test_lines = dataset["test"]["input"]
                LEN = len(covered_test_lines)
                COUNTER = 0

                # preds = map (generate,covered_test_lines)
                for line in covered_test_lines:
                    input_ids = tokenizer(line, return_tensors="pt").to(model.device)
                    output = model.generate(
                        **input_ids,
                        max_new_tokens=50,
                        num_beams=4,
                        #early_stopping=True
                    )
                    output_string = (tokenizer.decode(output[0], skip_special_tokens=True))
                    ref_line = test_file.readline()
                    lemma, features, ref = ref_line.strip().split("\t")

                    # evaluate
                    if (ref == output_string):
                        COUNTER += 1
                        print(ref,output_string)
                    else:
                        print("ref:",ref,"pred:",output_string)
                     #   error_file.write("ref\t"+ref_line+"\n")
                      #  error_file.write("byt5\t"+line+"\n\n")
                       # error_file.flush()
                    # write
                    out_file.write(lemma + "\t" +features+ "\t" + output_string + "\n")
                    out_file.flush()

                accuracy = COUNTER / LEN
                out_file.write("accuracy:"+ str(accuracy)+"\n")
                print(accuracy)

livles/csb-pol-byte-25perc-sent-pol

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

config.json:   0%|          | 0.00/851 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/142 [00:00<?, ?B/s]

test file:  ../preprocessing/preprocessing_to_json_or_tsv/data/csb_tst.json
ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzaczom pred: narzãdzôczom
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczama pred: narzãdzôczami
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczowi pred: narzãdzôczowi
ref: narzãdzacza pred: narzãdzôcza
ref: narzãdzaczach pred: narzãdzôczach
ref: narzãdzaczów pred: narzãdzôczy
ref: narzãdzaczã pred: narzãdzôczem
ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzacza pred: narzãdzôcz
narzãdzôcz narzãdzôcz
ref: narzãdzacze pred: narzãdzôcze
Jastrë Jastrë
Jastrach Jastrach
ref: Jastróm pred: Jastrom
Jastrów Jastrów
ref: Jastrama pred: Jastrë
Jastrë Jastrë
Jastrë Jastrë
ref: pòniedzałczi pred: pòniedzôłki
ref: pòniedzałkóm pred: pòniedzôłkom
ref: pòniedzałkù pred: pòniedzôłku
ref: pòniedzałkama pred: pòniedzôłkami
ref: pòniedzałkù pred: pòniedzôłcu
ref: poniedzałkòwi pred: pòniedzôłcowi
ref: pòniedzałkù pred: pòniedzôłku
ref: pòniedzałkach pred: pòniedzôłkach
ref: pòniedzałków pred: pòniedzôłków
ref: pòniedzałkã pred: pòniedzôłkiem
ref: pòniedzałczi pred: pòniedzôłki
pòniedzôłk pòniedzôłk
pòniedzôłk pòniedzôłk
ref: pòniedzałczi pred: pòniedzôłki
ref: pùjczi pred: pùjki
pùjkom pùjkom
ref: pùjkù pred: pùjku
ref: pùjkama pred: pùjkami
ref: pùjkù pred: pùjku
ref: pùjkòwi pred: pùjkowi
pùjka pùjka
pùjkach pùjkach
pùjków pùjków
ref: pùjkã pred: pùjkiem
ref: pùjczi pred: pùjki
ref: pùjka pred: pùjk
pùjk pùjk
ref: pùjczi pred: pùjki
ref: môlniczi pred: môlniki
ref: môlnikòm pred: môlnikom
ref: môlnikù pred: môlniku
ref: môlnikama pred: môlnikami
ref: môlnikù pred: môlniku
ref: môlnikòwi pred: môlnikowi
môlnika môlnika
môlnikach môlnikach
môlników môlników
ref: môlnikã pred: môlnikiem
ref: môlniczi pred: môlniki
môlnik môlnik
môlnik môlnik
ref: môlniczi pred: môlniki
ref: wòłiwaczë pred: wòłiwôcze
ref: wòłiwaczom pred: wòłiwôczom
ref: wòłiwaczu pred: wòłiwôczu
ref: wòłiwaczama pred: wòłiwoczami
ref: wòłiwaczu pred: wòłiwoczu
ref: wòłiwaczowi pred: wòłiwoczowi
ref: wòłiwacza pred: wòłiwocza
ref: wòłiwaczach pred: wòłiwoczach
ref: wòłiwaczów pred: wòłiwoczów
ref: wòłiwaczã pred: wòłiwoczem
ref: wòłiwaczë pred: wòłiwôcze
ref: wòłiwacza pred: wòłiwôcz
wòłiwôcz wòłiwôcz
ref: wòłiwaczë pred: wòłiwôcze
ref: łżëkwiôtë pred: łżëkwiôty
ref: łżëkwiôtom pred: łżëkwiotom
ref: łżëkwiôce pred: łżëkwiotowi
ref: łżëkwiôtama pred: łżëkwiotami
ref: łżëkwiôce pred: łżëkwiocie
ref: łżëkwiôtowi pred: łżëkwiotowi
ref: łżëkwiôta pred: łżëkwiotu
ref: łżëkwiôtach pred: łżëkwiotach
łżëkwiôtów łżëkwiôtów
ref: łżëkwiôtã pred: łżëkwiotem
ref: łżëkwiôtë pred: łżëkwiôty
ref: łżëkwiôta pred: łżëkwiôt
łżëkwiôt łżëkwiôt
ref: łżëkwiôtë pred: łżëkwiôty
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnikòm pred: lëstopadnikom
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikama pred: lëstopadnikami
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikòwi pred: lëstopadnikowi
lëstopadnika lëstopadnika
lëstopadnikach lëstopadnikach
lëstopadników lëstopadników
ref: lëstopadnikã pred: lëstopadnikiem
ref: lëstopadniczi pred: lëstopadniki
lëstopadnika lëstopadnika
lëstopadnik lëstopadnik
ref: lëstopadniczi pred: lëstopadniki
ref: sobòtë pred: sobòty
ref: sobòtóm pred: sobotom
ref: sobòto pred: sobòcie
ref: sobòtama pred: sobotami
ref: sobòce pred: sobòcie
sobòce sobòce
ref: sobòtë pred: sobòty
sobòtach sobòtach
ref: sobòtów pred: sobòt
ref: sobòtã pred: sobòtą
ref: sobòtë pred: sobòty
ref: sobòtã pred: sobòtę
sobòta sobòta
ref: sobòtë pred: sobòty
ref: kònie pred: kóń
ref: kòniom pred: końom
ref: kòniu pred: kóń
ref: kòniama pred: kóńmi
ref: kòniu pred: konie
ref: kòniowi pred: koniowi
ref: kònia pred: kóń
ref: kòniach pred: kóńcach
ref: kòni pred: kóń
ref: kòniã pred: kóńm
ref: kònie pred: konie
ref: kònia pred: kóń
kóń kóń
ref: kònie pred: kóń
ref: nazéwacze pred: nazéwôcze
ref: nazéwaczom pred: nazéwôczom
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczama pred: nazéwôczami
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczowi pred: nazéwôczowi
ref: nazéwacza pred: nazéwôcza
ref: nazéwaczach pred: nazéwôczach
ref: nazéwaczów pred: nazéwôczów
ref: nazéwaczã pred: nazéwôczem
ref: nazéwacze pred: nazéwôcze
ref: nazéwacza pred: nazéwôcz
nazéwôcz nazéwôcz
ref: nazéwacze pred: nazéwôcze
ref: piątczi pred: piątki
ref: piątkóm pred: piątkom
ref: piątkù pred: piątku
ref: piątkama pred: piątkami
ref: piątkù pred: piątcu
ref: piątkòwi pred: piątkowi
ref: piątkù pred: piątka
piątkach piątkach
piątków piątków
ref: piątkã pred: piątkiem
ref: piątczi pred: piątki
piątk piątk
piątk piątk
ref: piątczi pred: piątki
ref: rënczi pred: rënki
ref: rënkóm pred: rënkom
ref: stolem pred: rënku
ref: rënkama pred: rënkami
ref: rënkù pred: rënku
ref: rënkòwi pred: rënkowi
ref: rënkù pred: rënku
rënkach rënkach
rënków rënków
ref: rënkã pred: rënkiem
ref: rënczi pred: rënki
rënk rënk
rënk rënk
ref: rënczi pred: rënki
ref: wtórczi pred: wtórki
ref: wtórkòm pred: wtórkom
ref: wtórkù pred: wtórku
ref: wtórkama pred: wtórkami
ref: wtórkù pred: wtórcu
ref: wtórkòwi pred: wtórkowi
wtórka wtórka
wtórkach wtórkach
wtórków wtórków
ref: wtórkã pred: wtórkiem
ref: wtórczi pred: wtórki
wtórk wtórk
wtórk wtórk
ref: wtórczi pred: wtórki
ref: winowacze pred: winowôcze
ref: winowaczom pred: winowôczom
ref: winowaczu pred: winowôczu
ref: winowaczama pred: winowôczami
ref: winowaczu pred: winowoczu
ref: winowaczowi pred: winowôczowi
ref: winowacza pred: winowôcza
ref: winowaczach pred: winowoczach
ref: winowaczów pred: winowôczów
ref: winowaczã pred: winowôczem
ref: winowacze pred: winowôcze
ref: winowacza pred: winowôcz
winowôcz winowôcz
ref: winowacze pred: winowôcze
ref: òjcowie pred: òjcy
ref: òjcóm pred: òjcom
ref: òjcze pred: òjcu
ref: òjcama pred: òjcami
òjcu òjcu
ref: òjcu pred: òjcowi
òjca òjca
òjcach òjcach
òjców òjców
ref: òjcã pred: òjcem
òjcem òjcem
ref: òjców pred: òjcy
ref: òjca pred: òjc
òjc òjc
ref: òjcowie pred: òjcy
ref: latawiska pred: latawiski
ref: latawiskóm pred: latawiskom
ref: latawiskù pred: latawisko
ref: latawiskama pred: latawiskami
ref: latawiskù pred: latawisku
ref: latawiskù pred: latawiskowi
latawiska latawiska
latawiskach latawiskach
latawisków latawisków
ref: latawiskã pred: latawiskiem
ref: latawiska pred: latawiski
latawiskò latawiskò
ref: latawiskò pred: latawisko
ref: latawiska pred: latawiski
ref: Jastra pred: Jastry
Jastrach Jastrach
ref: Jastróm pred: Jastrom
ref: Jastrów pred: Jastr
ref: Jastrama pred: Jastry
ref: Jastra pred: Jastry
ref: Jastra pred: Jastry
czerwińce czerwińce
czerwińcom czerwińcom
czerwińcu czerwińcu
ref: czerwińcama pred: czerwińcami
czerwińcu czerwińcu
czerwińcowi czerwińcowi
czerwińca czerwińca
czerwińcach czerwińcach
czerwińców czerwińców
ref: czerwińcã pred: czerwińcem
czerwińce czerwińce
ref: czerwińca pred: czerwińc
czerwińc czerwińc
ref: czerwińc pred: czerwińce
ref: rujanë pred: rujany
rujanom rujanom
rujanie rujanie
ref: rujanama pred: rujanami
rujanie rujanie
rujanowi rujanowi
ref: rujana pred: rujanu
rujanach rujanach
rujanów rujanów
ref: rujanã pred: rujanem
ref: rujanë pred: rujany
ref: rujana pred: rujan
rujan rujan
ref: rujanë pred: rujany
ref: dôwacze pred: dôwôcze
ref: dôwaczom pred: dôwôczom
ref: dôwaczu pred: dôwôczu
ref: dôwaczama pred: dôwôczami
ref: dôwaczu pred: dôwôczu
ref: dôwaczowi pred: dôwôczowi
dôwôcza dôwôcza
ref: dôwaczach pred: dôwôczach
ref: dôwaczów pred: dôwôczów
ref: dôwaczã pred: dôwôczem
ref: dôwacze pred: dôwôcze
ref: dôwacza pred: dôwôcz
dôwôcz dôwôcz
ref: dôwacze pred: dôwôcze
ref: serca pred: serce
ref: sercóm pred: sercom
ref: serce pred: sercu
ref: sercama pred: sercami
sercu sercu
ref: serce pred: sercu
ref: sercu pred: sercowi
serca serca
sercach sercach
serców serców
ref: serc pred: serców
ref: sercã pred: sercem
sercem sercem
serca serca
serce serce
serce serce
serca serca
ref: lëpince pred: lëpincy
lëpincom lëpincom
lëpincu lëpincu
ref: lëpincama pred: lëpincami
lëpincu lëpincu
lëpincowi lëpincowi
lëpinca lëpinca
lëpincach lëpincach
lëpinców lëpinców
ref: lëpincã pred: lëpincem
ref: lëpince pred: lëpincy
lëpinc lëpinc
lëpinc lëpinc
ref: lëpince pred: lëpincy
ref: séwniczi pred: séwniki
ref: séwnikòm pred: séwnikom
ref: séwnikù pred: séwniku
ref: séwnikama pred: séwnikami
ref: séwnikù pred: séwniku
ref: séwnikòwi pred: séwnikowi
séwnika séwnika
séwnikach séwnikach
séwników séwników
ref: séwnikã pred: séwnikiem
ref: séwniczi pred: séwniki
ref: séwnika pred: séwnik
séwnik séwnik
ref: séwniczi pred: séwniki
ref: zélniczi pred: zélniki
ref: zélnikòm pred: zélnikom
ref: zélnikù pred: zélniku
ref: zélnikama pred: zélnikami
ref: zélnikù pred: zélniku
ref: zélnikòwi pred: zélnikowi
zélnika zélnika
zélnikach zélnikach
zélników zélników
ref: zélnikã pred: zélnikiem
ref: zélniczi pred: zélniki
ref: zélnika pred: zélnik
zélnik zélnik
ref: zélniczi pred: zélniki
ref: stëczniczi pred: stëczniki
ref: stëcznikòm pred: stëcznikom
ref: stëcznikù pred: stëczniku
ref: stëcznikama pred: stëcznikami
ref: stëcznikù pred: stëczniku
ref: stëcznikòwi pred: stëcznikowi
stëcznika stëcznika
stëcznikach stëcznikach
stëczników stëczników
ref: stëcznikã pred: stëcznikiem
ref: stëczniczi pred: stëczniki
ref: stëcznika pred: stëcznik
stëcznik stëcznik
ref: stëczniczi pred: stëczniki
ref: strzodë pred: strzody
ref: strzodóm pred: strzodom
ref: strzodo pred: strzodzie
ref: strzodama pred: strzodami
ref: strzodze pred: strzodzie
ref: strzodze pred: strzodzie
ref: strzodë pred: strzody
strzodach strzodach
ref: strzodów pred: strzod
ref: strzodã pred: strzodą
ref: strzodë pred: strzody
ref: strzodã pred: strzodę
strzoda strzoda
ref: strzodë pred: strzody
ref: maje pred: môje
ref: majom pred: mojom
ref: maju pred: môju
ref: majima pred: môjami
ref: maju pred: moju
ref: majowi pred: mojowi
ref: maja pred: môja
ref: majach pred: mojach
ref: majów pred: môjów
ref: majã pred: môjem
ref: maje pred: môje
môj môj
môj môj
ref: maje pred: môje
ref: strumianniczi pred: strumianniki
ref: strumiannikòm pred: strumiannikom
ref: strumiannikù pred: strumianniku
ref: strumiannikama pred: strumiannikami
ref: strumiannikù pred: strumianniku
ref: strumiannikòwi pred: strumiannikowi
strumiannika strumiannika
strumiannikach strumiannikach
strumianników strumianników
ref: strumiannikã pred: strumiannikiem
ref: strumianniczi pred: strumianniki
strumiannik strumiannik
strumiannik strumiannik
ref: strumianniczi pred: strumianniki
tidzénie tidzénie
ref: tidzénióm pred: tidzéniom
tidzéniu tidzéniu
ref: tidzénama pred: tidzéniami
tidzéniu tidzéniu
tidzéniowi tidzéniowi
tidzénia tidzénia
ref: tidzénach pred: tidzéniach
ref: tidzéniów pred: tidzéń
ref: tidzénã pred: tidzéniem
tidzénie tidzénie
tidzéń tidzéń
tidzéń tidzéń
tidzénie tidzénie
ref: czwôrtczi pred: czwôrtki
ref: czwôrtkóm pred: czwôrtkom
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkama pred: czwôrtkami
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkòwi pred: czwôrtkowi
ref: czwôrtkù pred: czwôrtka
czwôrtkach czwôrtkach
czwôrtków czwôrtków
ref: czwôrtkã pred: czwôrtkiem
ref: czwôrtczi pred: czwôrtki
czwôrtk czwôrtk
czwôrtk czwôrtk
ref: czwôrtczi pred: czwôrtki
ref: kòtë pred: kòty
kòtom kòtom
ref: kòce pred: kòtowi
ref: kòtama pred: kòtami
ref: kòce pred: kòcie
kòtowi kòtowi
ref: kòtu pred: kòtowi
ref: kòta pred: kòtu
kòtach kòtach
kòtów kòtów
ref: kòtã pred: kòtem
ref: kòtë pred: kòty
ref: kòta pred: kòt
kòt kòt
ref: kòtë pred: kòty
ref: gromiczniczi pred: gromiczniki
ref: gromicznikòm pred: gromicznikom
ref: gromicznikù pred: gromiczniku
ref: gromicznikama pred: gromicznikami
ref: gromicznikù pred: gromiczniku
ref: gromicznikòwi pred: gromicznikowi
gromicznika gromicznika
gromicznikach gromicznikach
gromiczników gromiczników
ref: gromicznikã pred: gromicznikiem
ref: gromiczniczi pred: gromiczniki
ref: gromicznika pred: gromicznik
gromicznik gromicznik
ref: gromiczniczi pred: gromiczniki
rodzôcze rodzôcze
rodzôczom rodzôczom
rodzôczu rodzôczu
ref: rodzôczama pred: rodzôczami
rodzôczu rodzôczu
rodzôczowi rodzôczowi
rodzôcza rodzôcza
rodzôczach rodzôczach
rodzôczów rodzôczów
ref: rodzôczã pred: rodzôczem
rodzôcze rodzôcze
ref: rodzôcza pred: rodzôcz
rodzôcz rodzôcz
rodzôcze rodzôcze
niedzele niedzele
ref: niedzelóm pred: niedzelom
ref: niedzelo pred: niedzeli
ref: niedzelama pred: niedzelami
niedzeli niedzeli
niedzeli niedzeli
ref: niedzeli pred: niedzely
niedzelach niedzelach
ref: niedzelów pred: niedzel
ref: niedzelã pred: niedzelą
niedzele niedzele
ref: niedzelã pred: niedzelę
niedzela niedzela
niedzele niedzele
ref: gòdniczi pred: gòdniki
ref: gòdnikòm pred: gòdnikom
ref: gòdnikù pred: gòdniku
ref: gòdnikama pred: gòdnikami
ref: gòdnikù pred: gòdniku
ref: gòdnikòwi pred: gòdnikowi
gòdnika gòdnika
gòdnikach gòdnikach
gòdników gòdników
ref: gòdnikã pred: gòdnikiem
ref: gòdniczi pred: gòdniki
ref: gòdnika pred: gòdnik
gòdnik gòdnik
ref: gòdniczi pred: gòdniki
ref: stolemë pred: stolemy
ref: stolemóm pred: stolemom
ref: stolem pred: stolemie
ref: stolemama pred: stolemami
stolemie stolemie
ref: stolemòwi pred: stolemowi
ref: stolema pred: stolemu
stolemach stolemach
stolemów stolemów
ref: stolemã pred: stolemem
ref: stolemów pred: stolemy
ref: stolema pred: stolem
stolem stolem
ref: stolemë pred: stolemy
0.3182711198428291

In [32]:
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments
from datasets import load_dataset
import random
import numpy
# get tokenizer and sentinal tokens for masking
tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")

# Load pre-trained model
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, return_tensors="pt")
random.seed(10)

def preprocess_function(examples): # receives unmasked sentence as input
    inputs = examples
    inputs = inputs.strip()
    model_inputs = tokenizer(inputs)
    input_ids = model_inputs.input_ids
    attention_mask = model_inputs.attention_mask
    # print(input_ids, attention_mask, len(input_ids),len(attention_mask))
    # mask 15% of the bytes randomly in the tokenized sentence leaving out bordering bytes.
    len_sentence = len(input_ids)
    length = round(len(input_ids) * 0.22) # mask 15% of character (T5 and mT5 do that for tokens)
    return length



from array import array
# load dataset
lang = "csb-pol-sent"
train_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json_or_tsv/data/{lang}_trn.tsv"
eval_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json_or_tsv/data/{lang}_dev.tsv"
dataset = load_dataset("csv", delimiter="\t",column_names=["input"],data_files={"train": train_path,"validation": eval_path},quoting=3) # disable quote parsing
print(dataset["train"][1])
mean_train = sum(list(map(preprocess_function, dataset["train"]["input"]))) / 9000
mean_dev = sum( list( map(preprocess_function, dataset["validation"]["input"]) ) ) / 1000

print("mean" ,mean_train,mean_dev)

{'input': 'Grądol je òbsadzony na górze drobné wietewczi.'}
mean 21.695666666666668 21.667