# Setup

In [2]:
%cd /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/

/dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5

In [2]:
!rm -rf /usr/local/lib/python3.10/dist-packages/-andas*
!pip install transformers torch datasets accelerate tiktoken pandas==2.2.2 numpy==1.23.5 pyarrow==16.1.0
#!pip install transformers --upgrade
!pip install ipywidgets
!pip install python-dotenv pickleshare

WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.57.1)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.9.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (1.12.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.10/dist-packages (0.12.0)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy==1.23.5 in /usr/local/lib/python3.10/dist-packages (1.23.5)
Requirement already satisfied: pyarrow==16.1.0 in /usr/local/lib/python3.10/dist-packages (16.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch) (3.5.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (8.26.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (3.0.47)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (1.3.1)
Requirement already satisfied: typing-extensions>=4.6 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (4.15.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets) (4.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.17.0)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.10/dist-packages (1.2.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (0.7.5)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)

# Pre-training
with 10k sentences in Kashubian

In [11]:
# source: https://corpora.uni-leipzig.de/en?corpusId=csb_wikipedia_2021
# source: https://huggingface.co/docs/transformers/v4.57.1/en/model_doc/t5#transformers.T5Config
sentences_path = "/dss/dsshome1/03/ge87wod2/morphological-inflection/data/leipzig-corpera-collection/csb_wikipedia_2021_10K/" + "csb_wikipedia_2021_10K-sentences.txt"
import random
import math
with open (sentences_path,"r") as in_file:
   
    lines = in_file.readlines()
    for i in range(math.floor((len(lines)-1)/16)):
        if i == 4: break
        print(i)
        inputs = []
        labels = []
        batch_lines = lines[i*16:min(i*16+16,len(lines))]
        for line in batch_lines:
            sentence = line.split("\t")[1] # cut out line number
            words = sentence.split(" ")
            end_index = len(words)-4
            mask_len = 3
            while (end_index < 1 and mask_len > 0 ):
                mask_len -= 1
                end_index += 1
            start_index = random.randint(1,end_index) # mask 3 words: start mask between second and fourth last word
            input_sentence = words[:start_index] + ["<extra_id_0>"] + words[start_index+mask_len:]
            label_sentence = ["<extra_id_0>"]+words[start_index:start_index+mask_len]+["<extra_id_1>"]
            input_sentence = " ".join(input_sentence)
            label = " ".join(label_sentence)
            inputs.append(input_sentence)
            labels.append(label)
            from transformers import AutoTokenizer, T5ForConditionalGeneration, AutoModelForSeq2SeqLM
            tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
            modeler = T5ForConditionalGeneration.from_pretrained("google/byt5-small")

            # training
            input_ids = tokenizer(inputs, return_tensors="pt",padding=True).input_ids
            labels_batch = tokenizer(labels, return_tensors="pt",padding=True).input_ids
            outputs = model(input_ids=input_ids, labels=labels_batch)
            loss = outputs.loss
            logits = outputs.logits
print(inputs[0],labels[0])

# inference
input_ids = tokenizer(
    "The <extra_id_0> walks in <extra_id_1> park", return_tensors="pt"
).input_ids  # Batch size 1
outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
# studies have shown that owning a dog is good for you.

0

NameError: name 'model' is not defined

In [19]:
input_ids = tokenizer("The dog chases a ball in the park.").input_ids
masked_input = torch.tensor([input_ids[:8] + [258] + input_ids[14:21] + [257] + input_ids[28:]])
print(input_ids)
print(masked_input)
output = model.generate(masked_input, max_length=100)

[87, 107, 104, 35, 103, 114, 106, 35, 102, 107, 100, 118, 104, 118, 35, 100, 35, 101, 100, 111, 111, 35, 108, 113, 35, 119, 107, 104, 35, 115, 100, 117, 110, 49, 1]
tensor([[ 87, 107, 104,  35, 103, 114, 106,  35, 258,  35, 100,  35, 101, 100,
         111, 111, 257,  35, 115, 100, 117, 110,  49,   1]])

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

# Load domain-specific text (replace with your own corpus)
train_path = "/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/csb-sent.json"
eval_path = "/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/csb-sent.json"
dataset = load_dataset("json", data_files={"train": train_path,"validation":eval_path})

# Tokenizer
def preprocess_function(examples):
    # inputs = [prefix + doc for doc in examples["text"]]
    inputs = examples["input"]
    model_inputs = tokenizer(inputs)

    labels = tokenizer(text_target=examples["labels"],padding=True) # same length irrelevant here, so no truncation or padding

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
tokenized_dataset = dataset.map(preprocess_function, batched=True)

# Load pre-trained model
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, return_tensors="pt")
# Training arguments
training_args = TrainingArguments (
    output_dir="./byt5_small/csb-sent",
    overwrite_output_dir=True,
    num_train_epochs=4,
    per_device_train_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
   # save_steps=10_000,
   # save_total_limit=2,
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    data_collator=data_collator,
    processing_class=tokenizer,
)

# Pretrain the model
trainer.train()
trainer.push_to_hub()

In [5]:
import torch
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")

num_special_tokens = 3

input_ids = torch.tensor([list("Life is like a box of chocolates.".encode("utf-8"))]) + num_special_tokens
labels = torch.tensor([list("La vie est comme une boîte de chocolat.".encode("utf-8"))]) + num_special_tokens
loss = model(input_ids, labels=labels).loss
loss.item()

2.658773899078369

# Training small pre-trained ByT5 model using dataset

In [9]:
LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"]
LANGS = LANGS[-2:]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul-language-code","mul-language-word"]
LANGS = ["mul-language-code"]
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]
LANGS = ["pol"]

PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang.split("-")[0] + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # -

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    checkpoint = "livles/csb-sent"
    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/csb-"+lang,
        eval_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=4,
        predict_with_generate=True,
        # save_strategy="epoch",
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        # load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Inflect zacny | ADJ;ACC(SG,FEM)', 'target': 'zacną'}
DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[125, 100, 102, 113, 199, 136, 1]

/tmp/ipykernel_1505850/3745286411.py:82: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

# Train with more epochs

In [6]:
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]



PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # 

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/"+lang+"_13epochs",
        eval_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=13,
        predict_with_generate=True,
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        save_strategy="epoch",
        load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification,
        greater_is_better=False,
        metric_for_best_model="eval_loss"
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Navajo: Inflect náʼáłkad | V;IND;PFV;NOM(1,GRPL)', 'target': 'ńdaʼiilkad'}
DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[200, 135, 103, 100, 205, 191, 108, 108, 111, 110, 100, 103, 1]

/tmp/ipykernel_1244657/1895635383.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

# Testing models
+ [ ] TODO: finetune all slavic models and test them on the specific dataset
+ [ ] TODO: test 5lang-sample model on the dataset with prefixes

In [10]:
# SETTINGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"] + ["mul_2","ote","pol","amh"] + ["mul-language-code","mul-language-word"]
SETTINGS = ["mul"]
SETTINGS = ["5lang-sample"]
BASE_TEST_LANGUAGES_OF_SETTING = {"slavic":["pol","ces","csb","dsb","slk"],"slavic-word":["pol","ces","csb","dsb","slk"],"slavic-family":["pol","ces","csb","dsb","slk"],"5lang-sample":["deu","nav","klr","amh","grc"],"5lang-sample_16epochs":["deu","nav","klr","amh","grc"],
                                 "sme-15ksamples":["sme"],"sme-20ksamples":["sme"],"klr-15ksamples":["klr"],"klr-20ksamples":["klr"],"slavic-distant-word": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],"slavic-distant-word-or-family": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],
                                  "csb-pol":["csb","pol"]
                                 }
CODES = {"slavic": "","slavic-word":["-lang-word"],"slavic-family":["-family","-lang-word","-word-or-family"],"5lang-sample":["-lang-word"],"5lang-sample_16epochs":["-lang-word"],"5lang-sample_13epochs":["-lang-word"],"sme-15ksamples":[""],"sme-20ksamples":[""],"klr-15ksamples":[""],"klr-20ksamples":[""],"slavic-distant-word":["-lang-word"],"slavic-distant-word-or-family":["-lang-word"],"csb-pol":[""]}
SETTINGS = ["slavic","slavic-word"]
SETTINGS = ["sme-15ksamples","sme-20ksamples","klr-15ksamples","klr-20ksamples","5lang-sample_16epochs"]
SETTINGS = ["slavic-distant-word-or-family"]
SETTINGS = ["csb-pol"]

#TEST_LANGS_OLD = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] 
#TEST_LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] + ["ote","pol","amh","csb"]
#lang5_LANGS = ["deu","nav","klr","amh","grc"]
#lang_code = ""
for lang_setting in SETTINGS:
    test_langs = BASE_TEST_LANGUAGES_OF_SETTING[lang_setting]
    #if lang_setting == "mul": LANG_CODES = ["-language-word","-language-code",""] # test with no language code/word too
    #else: LANG_CODES = [""]
    #for lang_code in LANG_CODES:
        #if lang_setting in ( "deu_eng", "mul") and lang_code == "": test_langs = TEST_LANGS_OLD
        #elif lang_setting in ["mul_2","mul"]: test_langs = TEST_LANGS # test multilingual model on all languages it was trained on + Kashubian
        #elif lang_setting == "5lang-sample": test_langs = lang5_LANGS
        #elif lang_setting == "pol": test_langs = ["pol","csb"] # test Polish model on Kashubian also
        #else: 
    for lang_code in CODES[lang_setting]:
        for test_lang in test_langs:
            import torch
            from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
            PRETRAINED_MODEL = "google/byt5-small"
            FINETUNED_MODEL ="livles/"+lang_setting
            #FINETUNED_MODEL ="./byt5_small/"+lang_setting + lang_code
            MODEL = FINETUNED_MODEL
            print(MODEL)
            tokenizer = AutoTokenizer.from_pretrained(
                FINETUNED_MODEL,
            )
            model = AutoModelForSeq2SeqLM.from_pretrained(
                FINETUNED_MODEL,
            dtype=torch.float16,
            device_map="auto"
            )
            from datasets import load_dataset
            OUT_DIR = "output_byt5_small/" + lang_setting + "/" 
            PATH_TO_JSON_TEST_FILE = "../preprocessing/preprocessing_to_json/data/" + test_lang + lang_code+ "_tst.json"
            print("test file: ",PATH_TO_JSON_TEST_FILE)
            PATH_TO_ORIG_TEST_FILE = "../2023InflectionST/part1/data/" + test_lang + ".tst"
            from pathlib import Path
            Path(OUT_DIR).mkdir(parents=True, exist_ok=True)
            with open (OUT_DIR + test_lang + lang_code + "_byt5-small.out","w") as out_file, open (PATH_TO_ORIG_TEST_FILE, "r") as test_file:
                dataset = load_dataset("json",data_files={"test":PATH_TO_JSON_TEST_FILE})
                covered_test_lines = dataset["test"]["input"]
                LEN = len(covered_test_lines)
                COUNTER = 0

                # preds = map (generate,covered_test_lines)
                for line in covered_test_lines:
                    input_ids = tokenizer(line, return_tensors="pt").to(model.device)
                    output = model.generate(
                        **input_ids,
                        max_new_tokens=50,
                        num_beams=4,
                        #early_stopping=True
                    )
                    output_string = (tokenizer.decode(output[0], skip_special_tokens=True))
                    lemma, features, ref = test_file.readline().strip().split("\t")

                    # evaluate
                    if (ref == output_string):
                        COUNTER += 1
                        print(ref,output_string)
                    else:
                        print("ref:",ref,"pred:",output_string)

                    # write
                    out_file.write(lemma + "\t" +features+ "\t" + output_string + "\n")
                    out_file.flush()

                accuracy = COUNTER / LEN
                out_file.write("accuracy:"+ str(accuracy)+"\n")
                print(accuracy)

livles/csb-pol

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/791 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/152 [00:00<?, ?B/s]

test file:  ../preprocessing/preprocessing_to_json/data/csb_tst.json

Generating test split: 0 examples [00:00, ? examples/s]

ref: narzãdzacze pred: narzódzócze
ref: narzãdzaczom pred: narzódzóczom
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczama pred: narzãdzóczami
ref: narzãdzaczu pred: narzãdzóczu
ref: narzãdzaczowi pred: narzãdzóczowi
ref: narzãdzacza pred: narzãdzócza
ref: narzãdzaczach pred: narzãdzóczach
ref: narzãdzaczów pred: narzódzócz
ref: narzãdzaczã pred: narzãdzóczem
ref: narzãdzacze pred: narzódzócze
ref: narzãdzacza pred: narzãdzôcz
narzãdzôcz narzãdzôcz
ref: narzãdzacze pred: narzódzócze
ref: Jastrë pred: Jastry
Jastrach Jastrach
ref: Jastróm pred: Jastrom
Jastrów Jastrów
ref: Jastrama pred: Jastrów
ref: Jastrë pred: Jastrów
ref: Jastrë pred: Jastry
ref: pòniedzałczi pred: pòniedzółki
ref: pòniedzałkóm pred: pòniedzółkom
ref: pòniedzałkù pred: pòniedzôłku
ref: pòniedzałkama pred: pòniedzółkami
ref: pòniedzałkù pred: pòniedzôłcu
ref: poniedzałkòwi pred: pòniedzôłcowi
ref: pòniedzałkù pred: pòniedzôłka
ref: pòniedzałkach pred: pòniedzôłkach
ref: pòniedzałków pred: pòniedzółków
ref: pòniedzałkã pred: pòniedzôłkiem
ref: pòniedzałczi pred: pòniedzółki
pòniedzôłk pòniedzôłk
pòniedzôłk pòniedzôłk
ref: pòniedzałczi pred: pòniedzółki
ref: pùjczi pred: pùjki
pùjkom pùjkom
ref: pùjkù pred: pùjku
ref: pùjkama pred: pùjkami
ref: pùjkù pred: pùjku
ref: pùjkòwi pred: pùjkowi
pùjka pùjka
pùjkach pùjkach
pùjków pùjków
ref: pùjkã pred: pùjkiem
ref: pùjczi pred: pùjki
ref: pùjka pred: pùjk
pùjk pùjk
ref: pùjczi pred: pùjki
ref: môlniczi pred: môlniki
ref: môlnikòm pred: môlnikom
ref: môlnikù pred: môlniku
ref: môlnikama pred: môlnikami
ref: môlnikù pred: môlniku
ref: môlnikòwi pred: môlnikowi
môlnika môlnika
môlnikach môlnikach
môlników môlników
ref: môlnikã pred: môlnikiem
ref: môlniczi pred: môlniki
môlnik môlnik
môlnik môlnik
ref: môlniczi pred: môlniki
ref: wòłiwaczë pred: wòłiwócze
ref: wòłiwaczom pred: wòłiwoczom
ref: wòłiwaczu pred: wòłiwôczu
ref: wòłiwaczama pred: wòłiwóczami
ref: wòłiwaczu pred: wòłiwoczu
ref: wòłiwaczowi pred: wòłiwoczowi
ref: wòłiwacza pred: wòłiwôcza
ref: wòłiwaczach pred: wòłiwóczach
ref: wòłiwaczów pred: wòłiwoczów
ref: wòłiwaczã pred: wòłiwôczem
ref: wòłiwaczë pred: wòłiwócze
ref: wòłiwacza pred: wòłiwôcz
wòłiwôcz wòłiwôcz
ref: wòłiwaczë pred: wòłiwócze
ref: łżëkwiôtë pred: łżëkwioty
ref: łżëkwiôtom pred: łżëkwiotom
ref: łżëkwiôce pred: łżëkwiôt
ref: łżëkwiôtama pred: łżëkwiotami
ref: łżëkwiôce pred: łżëkwiocie
ref: łżëkwiôtowi pred: łżëkwiocie
ref: łżëkwiôta pred: łżëkwiota
ref: łżëkwiôtach pred: łżëkwiotach
ref: łżëkwiôtów pred: łżëkwiotów
ref: łżëkwiôtã pred: łżëkwiotem
ref: łżëkwiôtë pred: łżëkwioty
ref: łżëkwiôta pred: łżëkwiôt
łżëkwiôt łżëkwiôt
ref: łżëkwiôtë pred: łżëkwioty
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnikòm pred: lëstopadnikom
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikama pred: lëstopadnikami
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikòwi pred: lëstopadnikowi
lëstopadnika lëstopadnika
lëstopadnikach lëstopadnikach
lëstopadników lëstopadników
ref: lëstopadnikã pred: lëstopadnikiem
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnika pred: lëstopadnik
lëstopadnik lëstopadnik
ref: lëstopadniczi pred: lëstopadniki
ref: sobòtë pred: sobóty
ref: sobòtóm pred: sobotom
ref: sobòto pred: sobóto
ref: sobòtama pred: sobótami
ref: sobòce pred: sobocie
ref: sobòce pred: sobotowi
ref: sobòtë pred: sobóty
ref: sobòtach pred: sobótach
ref: sobòtów pred: sobót
ref: sobòtã pred: sobótą
ref: sobòtë pred: sobóty
ref: sobòtã pred: sobótę
ref: sobòta pred: sobóta
ref: sobòtë pred: sobóty
ref: kònie pred: kóń
ref: kòniom pred: kóńom
ref: kòniu pred: kóń
ref: kòniama pred: kóńami
ref: kòniu pred: kóńce
ref: kòniowi pred: kóńowi
ref: kònia pred: kóń
ref: kòniach pred: kóńach
ref: kòni pred: kóń
ref: kòniã pred: kóńem
ref: kònie pred: kóń
ref: kònia pred: kóń
kóń kóń
ref: kònie pred: kóń
ref: nazéwacze pred: nazéwócze
ref: nazéwaczom pred: nazéwoczom
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczama pred: nazéwóczami
ref: nazéwaczu pred: nazéwoczu
ref: nazéwaczowi pred: nazéwoczowi
ref: nazéwacza pred: nazéwocza
ref: nazéwaczach pred: nazéwóczach
ref: nazéwaczów pred: nazéwócz
ref: nazéwaczã pred: nazéwôczem
ref: nazéwacze pred: nazéwócze
ref: nazéwacza pred: nazéwôcz
nazéwôcz nazéwôcz
ref: nazéwacze pred: nazéwócze
ref: piątczi pred: piątki
ref: piątkóm pred: piątkom
ref: piątkù pred: piątku
ref: piątkama pred: piątkami
ref: piątkù pred: piątce
ref: piątkòwi pred: piątkowi
ref: piątkù pred: piątka
piątkach piątkach
piątków piątków
ref: piątkã pred: piątkiem
ref: piątczi pred: piątki
piątk piątk
piątk piątk
ref: piątczi pred: piątki
ref: rënczi pred: rënki
ref: rënkóm pred: rënkom
ref: stolem pred: rënku
ref: rënkama pred: rënkami
ref: rënkù pred: rënku
ref: rënkòwi pred: rënkowi
ref: rënkù pred: rënka
rënkach rënkach
rënków rënków
ref: rënkã pred: rënkem
ref: rënczi pred: rënki
rënk rënk
rënk rënk
ref: rënczi pred: rënki
ref: wtórczi pred: wtórki
ref: wtórkòm pred: wtórkom
ref: wtórkù pred: wtórku
ref: wtórkama pred: wtórkami
ref: wtórkù pred: wtórce
ref: wtórkòwi pred: wtórkowi
wtórka wtórka
wtórkach wtórkach
wtórków wtórków
ref: wtórkã pred: wtórkiem
ref: wtórczi pred: wtórki
wtórk wtórk
wtórk wtórk
ref: wtórczi pred: wtórki
ref: winowacze pred: winowócze
ref: winowaczom pred: winowóczom
ref: winowaczu pred: winowôczu
ref: winowaczama pred: winowóczami
ref: winowaczu pred: winowoczu
ref: winowaczowi pred: winowoczowi
ref: winowacza pred: winowócza
ref: winowaczach pred: winowóczach
ref: winowaczów pred: winowócz
ref: winowaczã pred: winowóczem
ref: winowacze pred: winowócze
ref: winowacza pred: winowôcz
winowôcz winowôcz
ref: winowacze pred: winowócze
ref: òjcowie pred: òjcy
ref: òjcóm pred: òjcom
ref: òjcze pred: òjcu
ref: òjcama pred: òjcami
òjcu òjcu
ref: òjcu pred: òjcowi
òjca òjca
òjcach òjcach
òjców òjców
ref: òjcã pred: òjcem
òjcem òjcem
ref: òjców pred: òjcy
ref: òjca pred: òjc
òjc òjc
ref: òjcowie pred: òjcy
ref: latawiska pred: latawiski
ref: latawiskóm pred: latawiskom
ref: latawiskù pred: latawisko
ref: latawiskama pred: latawiskami
ref: latawiskù pred: latawisku
ref: latawiskù pred: latawiskowi
latawiska latawiska
latawiskach latawiskach
latawisków latawisków
ref: latawiskã pred: latawiskiem
ref: latawiska pred: latawiski
ref: latawiskò pred: latawisko
ref: latawiskò pred: latawisko
ref: latawiska pred: latawiski
ref: Jastra pred: Jastry
Jastrach Jastrach
ref: Jastróm pred: Jastrom
Jastrów Jastrów
ref: Jastrama pred: Jastry
ref: Jastra pred: Jastry
ref: Jastra pred: Jastry
czerwińce czerwińce
czerwińcom czerwińcom
czerwińcu czerwińcu
ref: czerwińcama pred: czerwińcami
czerwińcu czerwińcu
czerwińcowi czerwińcowi
czerwińca czerwińca
czerwińcach czerwińcach
czerwińców czerwińców
ref: czerwińcã pred: czerwińcem
czerwińce czerwińce
ref: czerwińca pred: czerwińc
czerwińc czerwińc
ref: czerwińc pred: czerwińce
ref: rujanë pred: rujany
rujanom rujanom
ref: rujanie pred: rujanu
ref: rujanama pred: rujanami
rujanie rujanie
rujanowi rujanowi
rujana rujana
rujanach rujanach
rujanów rujanów
ref: rujanã pred: rujanem
ref: rujanë pred: rujany
ref: rujana pred: rujan
rujan rujan
ref: rujanë pred: rujany
ref: dôwacze pred: dôwôcze
ref: dôwaczom pred: dôwoczom
ref: dôwaczu pred: dôwôczu
ref: dôwaczama pred: dôwôczami
ref: dôwaczu pred: dôwôczu
ref: dôwaczowi pred: dôwôczowi
dôwôcza dôwôcza
ref: dôwaczach pred: dôwôczach
ref: dôwaczów pred: dôwôczów
ref: dôwaczã pred: dôwôczem
ref: dôwacze pred: dôwôcze
ref: dôwacza pred: dôwôcz
dôwôcz dôwôcz
ref: dôwacze pred: dôwôcze
ref: serca pred: serce
ref: sercóm pred: sercom
serce serce
ref: sercama pred: sercami
ref: sercu pred: sercie
ref: serce pred: sercie
ref: sercu pred: sercowi
serca serca
sercach sercach
serców serców
ref: serc pred: serców
ref: sercã pred: sercem
sercem sercem
ref: serca pred: serce
ref: serce pred: sercę
serce serce
ref: serca pred: serce
lëpince lëpince
lëpincom lëpincom
lëpincu lëpincu
ref: lëpincama pred: lëpincami
lëpincu lëpincu
lëpincowi lëpincowi
lëpinca lëpinca
lëpincach lëpincach
lëpinców lëpinców
ref: lëpincã pred: lëpincem
lëpince lëpince
lëpinc lëpinc
lëpinc lëpinc
lëpince lëpince
ref: séwniczi pred: séwniki
ref: séwnikòm pred: séwnikom
ref: séwnikù pred: séwniku
ref: séwnikama pred: séwnikami
ref: séwnikù pred: séwniku
ref: séwnikòwi pred: séwnikowi
séwnika séwnika
séwnikach séwnikach
séwników séwników
ref: séwnikã pred: séwnikiem
ref: séwniczi pred: séwniki
ref: séwnika pred: séwnik
séwnik séwnik
ref: séwniczi pred: séwniki
ref: zélniczi pred: zélniki
ref: zélnikòm pred: zélnikom
ref: zélnikù pred: zélniku
ref: zélnikama pred: zélnikami
ref: zélnikù pred: zélniku
ref: zélnikòwi pred: zélnikowi
zélnika zélnika
zélnikach zélnikach
zélników zélników
ref: zélnikã pred: zélnikiem
ref: zélniczi pred: zélniki
ref: zélnika pred: zélnik
zélnik zélnik
ref: zélniczi pred: zélniki
ref: stëczniczi pred: stëczniki
ref: stëcznikòm pred: stëcznikom
ref: stëcznikù pred: stëczniku
ref: stëcznikama pred: stëcznikami
ref: stëcznikù pred: stëczniku
ref: stëcznikòwi pred: stëcznikowi
stëcznika stëcznika
stëcznikach stëcznikach
stëczników stëczników
ref: stëcznikã pred: stëcznikiem
ref: stëczniczi pred: stëczniki
ref: stëcznika pred: stëcznik
stëcznik stëcznik
ref: stëczniczi pred: stëczniki
ref: strzodë pred: strzody
ref: strzodóm pred: strzodom
strzodo strzodo
ref: strzodama pred: strzodami
ref: strzodze pred: strzodzie
ref: strzodze pred: strzodzie
ref: strzodë pred: strzody
strzodach strzodach
strzodów strzodów
ref: strzodã pred: strzodą
ref: strzodë pred: strzody
ref: strzodã pred: strzodę
strzoda strzoda
ref: strzodë pred: strzody
ref: maje pred: móje
ref: majom pred: mojom
ref: maju pred: môju
ref: majima pred: mójami
ref: maju pred: moju
ref: majowi pred: mojowi
ref: maja pred: môja
ref: majach pred: mójach
ref: majów pred: mój
ref: majã pred: môjem
ref: maje pred: môje
môj môj
môj môj
ref: maje pred: móje
ref: strumianniczi pred: strumianniki
ref: strumiannikòm pred: strumiannikom
ref: strumiannikù pred: strumianniku
ref: strumiannikama pred: strumiannikami
ref: strumiannikù pred: strumianniku
ref: strumiannikòwi pred: strumiannikowi
strumiannika strumiannika
strumiannikach strumiannikach
strumianników strumianników
ref: strumiannikã pred: strumiannikiem
ref: strumianniczi pred: strumianniki
strumiannik strumiannik
strumiannik strumiannik
ref: strumianniczi pred: strumianniki
ref: tidzénie pred: tidzóń
ref: tidzénióm pred: tidzówom
ref: tidzéniu pred: tidzóń
ref: tidzénama pred: tidzéńmi
ref: tidzéniu pred: tidzeniu
ref: tidzéniowi pred: tidzówce
tidzénia tidzénia
ref: tidzénach pred: tidzónach
ref: tidzéniów pred: tidzón
ref: tidzénã pred: tidzéną
ref: tidzénie pred: tidzóny
tidzéń tidzéń
tidzéń tidzéń
ref: tidzénie pred: tidzóny
ref: czwôrtczi pred: czwórtki
ref: czwôrtkóm pred: czwórtkom
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkama pred: czwórtkami
ref: czwôrtkù pred: czwórtce
ref: czwôrtkòwi pred: czwórtkowi
ref: czwôrtkù pred: czwôrtka
ref: czwôrtkach pred: czwórtkach
ref: czwôrtków pred: czwórtków
ref: czwôrtkã pred: czwórtkiem
ref: czwôrtczi pred: czwórtki
czwôrtk czwôrtk
czwôrtk czwôrtk
ref: czwôrtczi pred: czwórtki
ref: kòtë pred: kóty
ref: kòtom pred: kótom
ref: kòce pred: kót
ref: kòtama pred: kótami
ref: kòce pred: kocie
ref: kòtowi pred: kotowi
ref: kòtu pred: kotowi
ref: kòta pred: kòtu
ref: kòtach pred: kótach
kòtów kòtów
ref: kòtã pred: kótem
ref: kòtë pred: kóty
ref: kòta pred: kòt
kòt kòt
ref: kòtë pred: kóty
ref: gromiczniczi pred: gromiczniki
ref: gromicznikòm pred: gromicznikom
ref: gromicznikù pred: gromiczniku
ref: gromicznikama pred: gromicznikami
ref: gromicznikù pred: gromiczniku
ref: gromicznikòwi pred: gromicznikowi
gromicznika gromicznika
gromicznikach gromicznikach
gromiczników gromiczników
ref: gromicznikã pred: gromicznikiem
ref: gromiczniczi pred: gromiczniki
ref: gromicznika pred: gromicznik
gromicznik gromicznik
ref: gromiczniczi pred: gromiczniki
ref: rodzôcze pred: rodzócze
ref: rodzôczom pred: rodzóczom
ref: rodzôczu pred: rodzóczu
ref: rodzôczama pred: rodzóczami
ref: rodzôczu pred: rodzóczu
ref: rodzôczowi pred: rodzóczowi
ref: rodzôcza pred: rodzócza
ref: rodzôczach pred: rodzóczach
ref: rodzôczów pred: rodzócz
ref: rodzôczã pred: rodzóczem
ref: rodzôcze pred: rodzócze
ref: rodzôcza pred: rodzócz
ref: rodzôcz pred: rodzócz
ref: rodzôcze pred: rodzócze
niedzele niedzele
ref: niedzelóm pred: niedzelom
niedzelo niedzelo
ref: niedzelama pred: niedzelami
niedzeli niedzeli
ref: niedzeli pred: niedzelowi
niedzeli niedzeli
niedzelach niedzelach
ref: niedzelów pred: niedzel
ref: niedzelã pred: niedzelą
niedzele niedzele
ref: niedzelã pred: niedzelę
niedzela niedzela
niedzele niedzele
ref: gòdniczi pred: gódniki
ref: gòdnikòm pred: gódnikom
ref: gòdnikù pred: gódniku
ref: gòdnikama pred: gódnikami
ref: gòdnikù pred: gódniku
ref: gòdnikòwi pred: gódnikowi
gòdnika gòdnika
ref: gòdnikach pred: gódnikach
ref: gòdników pred: gódników
ref: gòdnikã pred: gódnikiem
ref: gòdniczi pred: gódniki
ref: gòdnika pred: gòdnik
gòdnik gòdnik
ref: gòdniczi pred: gódniki
ref: stolemë pred: stolemy
ref: stolemóm pred: stolemom
ref: stolem pred: stolemu
ref: stolemama pred: stolemami
stolemie stolemie
ref: stolemòwi pred: stolemowi
ref: stolema pred: stolemu
stolemach stolemach
stolemów stolemów
ref: stolemã pred: stolemem
ref: stolemów pred: stolemy
ref: stolema pred: stolem
stolem stolem
ref: stolemë pred: stolemy
0.26129666011787817
livles/csb-pol
test file:  ../preprocessing/preprocessing_to_json/data/pol_tst.json

Generating test split: 0 examples [00:00, ? examples/s]

bezgrzeszne bezgrzeszne
bezgrzeszne bezgrzeszne
bezgrzesznego bezgrzesznego
bezgrzesznego bezgrzesznego
bezgrzesznego bezgrzesznego
bezgrzesznej bezgrzesznej
bezgrzesznej bezgrzesznej
bezgrzesznej bezgrzesznej
bezgrzesznemu bezgrzesznemu
bezgrzesznemu bezgrzesznemu
bezgrzeszny bezgrzeszny
bezgrzesznych bezgrzesznych
bezgrzesznych bezgrzesznych
bezgrzesznych bezgrzesznych
bezgrzesznym bezgrzesznym
bezgrzesznym bezgrzesznym
bezgrzesznymi bezgrzesznymi
uchwytami uchwytami
uchwyt uchwyt
uchwytom uchwytom
ref: uchwytowi pred: uchwycie
uchwytów uchwytów
uchwyty uchwyty
uchwyty uchwyty
uchwyty uchwyty
zdaniami podrzędnymi zdaniami podrzędnymi
zdania podrzędnego zdania podrzędnego
zdania podrzędne zdania podrzędne
zdania podrzędne zdania podrzędne
zdaniem podrzędnym zdaniem podrzędnym
zdanie podrzędne zdanie podrzędne
ref: zdaniu podrzędnym pred: zdaniu podrzędnemu
ref: zdań podrzędnych pred: zdania podrzędnych
ref: będą nosili pred: będziemy nosili
ref: będą nosiły pred: będziemy nosiły
ref: będziecie nosili pred: będą nosili
ref: będziecie nosiły pred: będziemy nosiły
będzie nosiła będzie nosiła
będzie nosił będzie nosił
ref: będziesz nosiła pred: będzie nosiła
niech nosi niech nosi
ref: noście pred: niech nosili
ref: nosić pred: nosił
nosiłabym nosiłabym
nosiłabyś nosiłabyś
ref: nosiłaby pred: nosiłabyś
nosiłam nosiłam
nosiłbym nosiłbym
nosiłbyś nosiłbyś
nosiłeś nosiłeś
nosilibyście nosilibyście
nosilibyśmy nosilibyśmy
ref: nosiliby pred: nosilibyście
nosiliście nosiliście
nosiliśmy nosiliśmy
ref: nosili pred: nosiliście
ref: nosiłoby pred: nosiłbyś
ref: nosił pred: nosiłeś
nosiłyście nosiłyście
ref: nosiły pred: nosiłyście
ref: nosimy pred: nosiłyśmy
ref: nosisz pred: nosił
ref: nośmy pred: niech nosimy
ref: nosząca pred: nosiłabym
noszące noszące
noszące noszące
ref: noszący pred: nosilibyśmy
ref: noszą pred: nosiłyście
ref: noszenie pred: nosić
ref: noszeni pred: nosilibyśmy
ref: noszę pred: nosił
ref: noszona pred: nosiłabym
ref: noszone pred: noszące
ref: noszone pred: noszące
ref: noszono pred: noszące
kosmonaucie kosmonaucie
kosmonaucie kosmonaucie
ref: kosmonauci pred: kosmonauty
kosmonautach kosmonautach
kosmonautą kosmonautą
kosmonauta kosmonauta
kosmonautę kosmonautę
ref: kosmonautów pred: kosmonauty
kosmonautów kosmonautów
kosmonauty kosmonauty
łączach łączach
łączami łączami
ref: łącza pred: łącze
ref: łącze pred: łączę
łącze łącze
ref: łącze pred: łączo
ref: łączu pred: łączowi
łączu łączu
ref: rosołach pred: rosółach
ref: rosołami pred: rosółami
ref: rosołem pred: rosółem
ref: rosole pred: rosół
rosół rosół
ref: rosołów pred: rosół
ref: rosoły pred: rosóły
bękarcie bękarcie
ref: bękarcie pred: bękartowi
bękartach bękartach
bękartami bękartami
bękartom bękartom
ref: bękartowi pred: bękarcowi
bękartów bękartów
naukowa naukowa
naukowe naukowe
naukowe naukowe
naukowe naukowe
ref: naukowego pred: naukowy
naukowego naukowego
naukowego naukowego
naukowego naukowego
naukowej naukowej
naukowemu naukowemu
naukowemu naukowemu
naukowych naukowych
naukowych naukowych
naukowych naukowych
naukowym naukowym
naukowym naukowym
naukowymi naukowymi
szufladami szufladami
szufladą szufladą
szufladę szufladę
szuflado szuflado
szuflady szuflady
szuflady szuflady
szuflady szuflady
rzepikami rzepikami
rzepikiem rzepikiem
rzepiki rzepiki
rzepik rzepik
rzepik rzepik
rzepików rzepików
rzepiku rzepiku
rzepiku rzepiku
ref: gnojach pred: gnójach
ref: gnojami pred: gnójami
ref: gnojem pred: gnójem
ref: gnoje pred: gnóje
ref: gnoje pred: gnóje
gnój gnój
gnój gnój
gnojowi gnojowi
ref: gnoju pred: gnóju
ref: gnoju pred: gnój
winogronowe winogronowe
winogronowe winogronowe
winogronowe winogronowe
winogronowego winogronowego
winogronowego winogronowego
winogronowej winogronowej
winogronowej winogronowej
winogronowej winogronowej
winogronowemu winogronowemu
winogronowemu winogronowemu
winogronowy winogronowy
winogronowym winogronowym
winogronowym winogronowym
będą kleili będą kleili
ref: będą kleiły pred: będziemy kleiły
ref: będę kleiła pred: będzie kleiła
ref: będę kleił pred: będzie kleił
ref: będziecie kleiły pred: będziemy kleiły
będzie kleiło będzie kleiło
ref: będziemy kleili pred: będą kleili
ref: kleicie pred: kleją
ref: kleić pred: kleiło
kleiłabym kleiłabym
kleiłabyś kleiłabyś
kleiłam kleiłam
ref: kleiłby pred: kleiłbyś
ref: kleiłem pred: kleiłeś
ref: kleiłeś pred: kleiło
kleilibyśmy kleilibyśmy
kleiliście kleiliście
kleiliśmy kleiliśmy
kleiło kleiło
ref: kleił pred: kleiło
kleiłybyście kleiłybyście
ref: kleiłyby pred: kleiłybyście
kleiłyście kleiłyście
kleiłyśmy kleiłyśmy
ref: kleimy pred: kleją
klejąca klejąca
klejące klejące
klejący klejący
ref: klejący pred: klejące
kleją kleją
ref: klejeni pred: klejący
ref: klejona pred: klejąca
ref: klejono pred: klejące
ref: klej pred: będziesz kleił
uczuciach uczuciach
uczuciami uczuciami
uczucia uczucia
uczucia uczucia
uczucie uczucie
uczuciu uczuciu
edylach edylach
edylami edylami
ref: edyla pred: edylu
ref: edyli pred: edyle
edyl edyl
edylom edylom
ref: edylowie pred: edyle
edylu edylu
edylu edylu
tłumaczeniach tłumaczeniach
tłumaczenia tłumaczenia
tłumaczenia tłumaczenia
tłumaczeniem tłumaczeniem
tłumaczenie tłumaczenie
tłumaczenie tłumaczenie
ref: tłumaczeniu pred: tłumaczonemu
tłumaczeniu tłumaczeniu
plombą plombą
plomba plomba
plombę plombę
ref: plombie pred: plombowi
plombie plombie
ref: plomb pred: plombów
ref: plombo pred: plombie
plomby plomby
plomby plomby
nieśmiertelną nieśmiertelną
nieśmiertelną nieśmiertelną
nieśmiertelnego nieśmiertelnego
nieśmiertelnej nieśmiertelnej
nieśmiertelnej nieśmiertelnej
nieśmiertelnej nieśmiertelnej
nieśmiertelnemu nieśmiertelnemu
nieśmiertelni nieśmiertelni
nieśmiertelnych nieśmiertelnych
nieśmiertelnych nieśmiertelnych
nieśmiertelnym nieśmiertelnym
kulach kulach
kulą kulą
kula kula
kule kule
kule kule
ref: kuli pred: kulie
ref: kuli pred: kuly
kul kul
brzoskwiniową brzoskwiniową
brzoskwiniowa brzoskwiniowa
brzoskwiniowe brzoskwiniowe
brzoskwiniowe brzoskwiniowe
ref: brzoskwiniowego pred: brzoskwiniowy
brzoskwiniowego brzoskwiniowego
ref: brzoskwiniowego pred: brzoskwiniowygo
brzoskwiniowej brzoskwiniowej
brzoskwiniowej brzoskwiniowej
ref: brzoskwiniowi pred: brzoskwiniowy
brzoskwiniowy brzoskwiniowy
brzoskwiniowych brzoskwiniowych
brzoskwiniowych brzoskwiniowych
brzoskwiniowych brzoskwiniowych
brzoskwiniowym brzoskwiniowym
brzoskwiniowymi brzoskwiniowymi
istnieniach istnieniach
istnienia istnienia
istnienia istnienia
istnienia istnienia
istnienie istnienie
istnienie istnienie
istnieniom istnieniom
ref: istnień pred: istnienia
martwą martwą
martwa martwa
martwe martwe
martwe martwe
martwego martwego
martwego martwego
martwemu martwemu
martwemu martwemu
ref: martwi pred: martwy
martwy martwy
martwy martwy
martwych martwych
martwych martwych
martwym martwym
martwym martwym
martwym martwym
martwym martwym
martwymi martwymi
napięciach napięciach
napięcia napięcia
napięcia napięcia
napięcia napięcia
napięcie napięcie
napięciu napięciu
ref: napięć pred: napięcia
dziwce dziwce
dziwkami dziwkami
dziwką dziwką
dziwki dziwki
dziwki dziwki
dziwkom dziwkom
dziwko dziwko
kompromisem kompromisem
kompromisie kompromisie
ref: kompromisie pred: kompromisu
kompromis kompromis
kompromisom kompromisom
kompromisowi kompromisowi
kompromisów kompromisów
kompromisu kompromisu
kompromisy kompromisy
klanami klanami
klanem klanem
klanie klanie
klan klan
klanom klanom
klanowi klanowi
klany klany
klany klany
klany klany
polanach polanach
polanami polanami
polana polana
polanę polanę
ref: polanie pred: polanowi
polanie polanie
polanom polanom
polano polano
polany polany
polany polany
ref: niech wyrządzą pred: będziemy wyrządzili
ref: niech wyrządzę pred: będziesz wyrządził
ref: wyrządzeni pred: wyrządzonych
ref: wyrządzę pred: będzie wyrządził
wyrządziłabym wyrządziłabym
wyrządziłabyś wyrządziłabyś
wyrządziłaś wyrządziłaś
wyrządziła wyrządziła
wyrządziłbym wyrządziłbym
wyrządziłbyś wyrządziłbyś
ref: wyrządziłby pred: wyrządziłbyś
wyrządziłeś wyrządziłeś
wyrządzilibyście wyrządzilibyście
wyrządzilibyśmy wyrządzilibyśmy
ref: wyrządziliby pred: wyrządzilibyśmy
wyrządziliście wyrządziliście
wyrządziliśmy wyrządziliśmy
ref: wyrządziłoby pred: wyrządziłbyś
wyrządził wyrządził
wyrządziłybyśmy wyrządziłybyśmy
wyrządziłyście wyrządziłyście
wyrządziłyśmy wyrządziłyśmy
ref: wyrządziły pred: wyrządziłyście
ref: wyrządzimy pred: będziemy wyrządzili
wyrządzona wyrządzona
wyrządzone wyrządzone
ref: wyrządzono pred: wyrządzone
ref: wyrządź pred: będziesz wyrządził
niższą niższą
niższa niższa
niższe niższe
niższe niższe
niższego niższego
niższego niższego
niższej niższej
niższemu niższemu
niższych niższych
niższym niższym
niższym niższym
niższym niższym
niższym niższym
nastolatkach nastolatkach
nastolatkami nastolatkami
nastolatka nastolatka
nastolatki nastolatki
nastolatki nastolatki
ref: nastolatków pred: nastolatki
nastolatku nastolatku
zbiegach zbiegach
ref: zbiega pred: zbieg
zbieg zbieg
zbiegom zbiegom
ref: zbiegowie pred: zbiegi
ref: zbiegów pred: zbiegi
zbiegu zbiegu
ref: szkutnicy pred: szkutniki
szkutnikach szkutnikach
szkutnikami szkutnikami
szkutnika szkutnika
szkutnikom szkutnikom
szkutników szkutników
szkutniku szkutniku
samotniejsi samotniejsi
samotniejszą samotniejszą
samotniejszą samotniejszą
samotniejsza samotniejsza
samotniejsze samotniejsze
samotniejsze samotniejsze
samotniejsze samotniejsze
ref: samotniejszego pred: samotniejszy
samotniejszego samotniejszego
samotniejszej samotniejszej
samotniejszej samotniejszej
samotniejszemu samotniejszemu
samotniejszy samotniejszy
samotniejszy samotniejszy
samotniejszych samotniejszych
samotniejszych samotniejszych
samotniejszym samotniejszym
samotniejszym samotniejszym
samotniejszymi samotniejszymi
mitozach mitozach
mitoza mitoza
mitozę mitozę
mitozie mitozie
mitozom mitozom
mitozy mitozy
asemblerach asemblerach
asemblerami asemblerami
asemblera asemblera
asemblerowi asemblerowi
asemblerów asemblerów
asemblery asemblery
asemblery asemblery
asemblerze asemblerze
ref: asemblerze pred: asemblerowi
ref: automacie pred: automatu
automatami automatami
automat automat
ref: automatowi pred: automacie
automaty automaty
automaty automaty
kasztanach kasztanach
kasztanami kasztanami
kasztan kasztan
kasztan kasztan
kasztany kasztany
kasztany kasztany
ref: śródmózgowiach pred: śródmózgowcach
ref: śródmózgowiami pred: śródmózgowcami
ref: śródmózgowia pred: śródmózgowie
śródmózgowie śródmózgowie
śródmózgowie śródmózgowie
ref: śródmózgowi pred: śródmózgowców
ref: śródmózgowiu pred: śródmózgowcowi
ref: śródmózgowiu pred: śródmózgowcu
ref: lisiąt pred: lisionów
ref: lisięciem pred: lisięmi
ref: lisięciu pred: lisionowi
ref: lisięciu pred: lisionie
lisię lisię
lisię lisię
ref: lisiętach pred: lisięch
ref: lisiętami pred: lisięmi
ref: lisięta pred: lisię
ref: lisięta pred: lisiony
ref: lisiętom pred: lisiom
ref: graniach pred: grańach
ref: granią pred: grańem
granie granie
granie granie
ref: grani pred: grania
grań grań
basach basach
basie basie
ref: basie pred: basu
bas bas
bas bas
basy basy
woskowiną woskowiną
woskowina woskowina
woskowino woskowino
ref: zadadzą pred: będziesz zadały
sinologia sinologia
sinologię sinologię
sinologii sinologii
sinologii sinologii
sinologii sinologii
sinologio sinologio
kurami kurami
kur kur
kurom kurom
kurowi kurowi
kurów kurów
kurze kurze
ref: kurze pred: kurowi
przysięgach przysięgach
przysięgami przysięgami
przysięga przysięga
przysięgi przysięgi
przysięgom przysięgom
przysięgo przysięgo
nonanem nonanem
ref: nonanie pred: nonanu
nonan nonan
nonan nonan
nonanów nonanów
nonany nonany
elektrowniami elektrowniami
elektrownie elektrownie
elektrownie elektrownie
elektrownie elektrownie
ref: elektrowni pred: elektrowniu
elektrowni elektrowni
elektrowniom elektrowniom
fotografach fotografach
fotografami fotografami
fotografem fotografem
fotografie fotografie
fotograf fotograf
ref: fotografów pred: fotografy
ref: będą machały pred: będzie machały
ref: będę machała pred: będzie machała
ref: będę machał pred: będzie machał
ref: będziecie machali pred: będą machali
będzie machała będzie machała
będzie machało będzie machało
będzie machał będzie machał
ref: będziemy machali pred: będą machali
ref: będziemy machały pred: będziemy machali
ref: będziesz machała pred: będzie machała
ref: będziesz machał pred: będzie machał
ref: machający pred: machalibyśmy
ref: machający pred: machane
ref: machajcie pred: będziemy machali
ref: machajmy pred: niech machajmy
ref: machałaby pred: machałabym
machałam machałam
machałaś machałaś
machała machała
machałbym machałbym
ref: machałby pred: machałbyś
machałem machałem
machalibyście machalibyście
machalibyśmy machalibyśmy
machaliśmy machaliśmy
ref: machałoby pred: machałbyś
machałybyśmy machałybyśmy
ref: machałyby pred: machałybyście
machałyście machałyście
machałyśmy machałyśmy
ref: machały pred: machałyście
ref: macham pred: machał
ref: machane pred: machające
machanie machanie
ref: machani pred: machalibyśmy
ref: machano pred: machane
ref: machasz pred: machał
ref: niech macha pred: będziesz machał
jonosferach jonosferach
jonosfera jonosfera
jonosferom jonosferom
jonosfery jonosfery
jonosfery jonosfery
jonosfery jonosfery
jonosferze jonosferze
ref: lodach pred: lódach
ref: lodem pred: lódem
lód lód
ref: lodom pred: lódom
lodowi lodowi
ref: lodów pred: lódów
lodzie lodzie
ref: będą siąknąły pred: będziemy siąknęły
ref: będą siąknęli pred: będziemy siąknęli
będziemy siąknęli będziemy siąknęli
ref: będzie siąknąła pred: będzie siąknęła
ref: będzie siąknąło pred: będzie siąknęło
będzie siąknął będzie siąknął
ref: będziesz siąknąła pred: będzie siąknęła
ref: będziesz siąknął pred: będzie siąknął
ref: niech siąkną pred: będziemy siąknęli
ref: niech siąknie pred: będzie siąknęło
ref: siąknąca pred: siąknęłabym
siąknące siąknące
siąknące siąknące
ref: siąknący pred: siąknące
ref: siąknąłabyś pred: siąknęłabyś
ref: siąknąłaby pred: siąknęłabyś
ref: siąknąła pred: siąknęła
ref: siąknąłbyś pred: siąknęłbyś
ref: siąknąłeś pred: siąknęło
ref: siąknąłybyście pred: siąknęłybyście
ref: siąknąłybyśmy pred: siąknęłybyśmy
ref: siąknąłyby pred: siąknęłybyście
ref: siąknąłyśmy pred: siąknęłyśmy
siąkną siąkną
ref: siąknęlibyście pred: siąknąlibyście
ref: siąknęlibyśmy pred: siąknąlibyśmy
ref: siąknęliście pred: siąknąliście
ref: siąknęliśmy pred: siąknąliśmy
ref: siąknę pred: siąknęło
ref: siąkniemy pred: siąkną
ref: siąkniesz pred: siąknęło
ref: siąknie pred: siąknęło
ref: siąknijcie pred: niech siąkną
ref: siąknijmy pred: niech siąkną
ref: siąknij pred: będzie siąknęło
najdzikszą najdzikszą
najdziksza najdziksza
najdziksze najdziksze
najdziksze najdziksze
najdzikszego najdzikszego
najdzikszej najdzikszej
najdzikszej najdzikszej
najdzikszej najdzikszej
najdzikszemu najdzikszemu
najdzikszy najdzikszy
najdzikszy najdzikszy
najdzikszych najdzikszych
najdzikszych najdzikszych
najdzikszym najdzikszym
peronach peronach
peronem peronem
peronie peronie
peronom peronom
peronów peronów
perony perony
sygnałach sygnałach
sygnałami sygnałami
sygnał sygnał
sygnałom sygnałom
sygnały sygnały
sygnały sygnały
najlżejszą najlżejszą
najlżejsza najlżejsza
najlżejsze najlżejsze
najlżejsze najlżejsze
najlżejsze najlżejsze
ref: najlżejszego pred: najlżejszy
najlżejszego najlżejszego
najlżejszej najlżejszej
najlżejszemu najlżejszemu
najlżejszy najlżejszy
najlżejszych najlżejszych
najlżejszych najlżejszych
najlżejszym najlżejszym
najlżejszymi najlżejszymi
wybuchach wybuchach
wybuchem wybuchem
wybuch wybuch
wybuch wybuch
wybuchowi wybuchowi
wybuchu wybuchu
ref: wybuchu pred: wybucha
wybuchu wybuchu
wybuchy wybuchy
wybuchy wybuchy
ref: sekście pred: sekstowi
ref: sekście pred: sekscie
sekstą sekstą
seksta seksta
ref: sekst pred: sekstów
sekstom sekstom
seksto seksto
seksty seksty
seksty seksty
seksty seksty
bocianach bocianach
bocianami bocianami
bociana bociana
bocianem bocianem
bocianie bocianie
bocian bocian
bocianom bocianom
bocianów bocianów
bociany bociany
bociany bociany
trwania trwania
trwanie trwanie
trwanie trwanie
trwaniu trwaniu
trwaniu trwaniu
ref: będę marła pred: będzie mrzeła
ref: będziecie marli pred: będą mrzeli
ref: będziecie marły pred: będziemy mrzeli
ref: będzie marła pred: będzie mrzeła
ref: będzie marło pred: będzie mrzeło
ref: będzie marł pred: będzie mrzeł
ref: będziemy marli pred: będą mrzeli
ref: marcie pred: mrzenie
ref: marłabyś pred: mrzełabyś
ref: marłam pred: mrzełam
ref: marłaś pred: mrzełaś
ref: marła pred: mrzeła
ref: marłbyś pred: mrzełbyś
ref: marłby pred: mrzełbyś
ref: marłeś pred: mrzełeś
ref: marlibyście pred: mrzelibyście
ref: marlibyśmy pred: mrzelibyśmy
ref: marł pred: mrzeł
ref: marłyby pred: mrzełybyście
ref: marłyśmy pred: mrzełyśmy
ref: marły pred: mrzełyście
ref: mrące pred: mrzenie
ref: mrące pred: mrzenie
ref: mrąc pred: mrzenie
ref: mrący pred: mrzelibyście
ref: mrący pred: mrzenie
ref: mrzecie pred: mrzyłyście
ref: mrzeć pred: mrzeł
ref: mrzemy pred: mrzeliśmy
ref: mrze pred: mrzeł
ref: mrzyjcie pred: będziemy mrzeli
ref: mrzyj pred: będziesz mrzeł
ref: niech mrą pred: będziemy mrzeli
ref: niech mrze pred: będziesz mrzeł
oczopląsach oczopląsach
oczopląs oczopląs
oczopląsowi oczopląsowi
oczopląsy oczopląsy
przewodniczącego przewodniczącego
ref: przewodniczących pred: przewodniczące
przewodniczących przewodniczących
przewodniczącym przewodniczącym
ref: przewodniczący pred: przewodniczące
ref: przewodniczący pred: przewodniczące
mięczakach mięczakach
mięczakami mięczakami
ref: mięczaka pred: mięczak
mięczaka mięczaka
mięczakiem mięczakiem
mięczaki mięczaki
mięczaki mięczaki
mięczaki mięczaki
mięczak mięczak
mięczakowi mięczakowi
mięczaków mięczaków
nieodpowiedzialna nieodpowiedzialna
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialnego nieodpowiedzialnego
nieodpowiedzialnego nieodpowiedzialnego
nieodpowiedzialnego nieodpowiedzialnego
nieodpowiedzialnemu nieodpowiedzialnemu
nieodpowiedzialnemu nieodpowiedzialnemu
nieodpowiedzialni nieodpowiedzialni
nieodpowiedzialny nieodpowiedzialny
nieodpowiedzialnych nieodpowiedzialnych
nieodpowiedzialnym nieodpowiedzialnym
nieodpowiedzialnym nieodpowiedzialnym
nieodpowiedzialnymi nieodpowiedzialnymi
szalu szalu
cyrkami cyrkami
ref: cyrkiem pred: cyrkem
cyrki cyrki
cyrk cyrk
cyrk cyrk
cyrków cyrków
cyrku cyrku
ref: cyrku pred: cyrka
cyrku cyrku
najjaśniejsi najjaśniejsi
najjaśniejszą najjaśniejszą
najjaśniejsza najjaśniejsza
najjaśniejsze najjaśniejsze
najjaśniejsze najjaśniejsze
ref: najjaśniejszego pred: najjaśniejszy
najjaśniejszej najjaśniejszej
najjaśniejszej najjaśniejszej
najjaśniejszych najjaśniejszych
najjaśniejszych najjaśniejszych
najjaśniejszych najjaśniejszych
najjaśniejszym najjaśniejszym
najjaśniejszym najjaśniejszym
żenecie żenecie
żenetami żenetami
żenetą żenetą
żeneta żeneta
żenetę żenetę
ref: żenet pred: żenetów
żenetom żenetom
żenety żenety
żenety żenety
żenety żenety
waściach waściach
waściami waściami
waści waści
ref: waści pred: waściu
ref: waści pred: waścia
ref: waści pred: waście
ref: waści pred: waść
waść waść
ref: otwarci pred: otwarty
otwartą otwartą
otwarta otwarta
otwarte otwarte
otwarte otwarte
otwartego otwartego
otwartej otwartej
otwartej otwartej
otwartej otwartej
otwartemu otwartemu
otwartemu otwartemu
ref: otwarty pred: otwarte
ref: otwarty pred: otwarte
otwartych otwartych
otwartym otwartym
otwartym otwartym
otwartymi otwartymi
ref: dłużnicy pred: dłużniki
ref: dłużnicy pred: dłużniki
dłużnikami dłużnikami
dłużnika dłużnika
dłużnik dłużnik
dłużnikowi dłużnikowi
ref: manicure'ami pred: manicurami
ref: manicure'em pred: manicurem
ref: manicure pred: manicurę
ref: manicure'om pred: manicurom
ref: manicure'y pred: manicury
ref: manicure'y pred: manicury
ref: manicure'y pred: manicury
manicurze manicurze
sefardyjscy sefardyjscy
sefardyjski sefardyjski
sefardyjskich sefardyjskich
sefardyjskie sefardyjskie
sefardyjskiego sefardyjskiego
sefardyjskiego sefardyjskiego
sefardyjskiej sefardyjskiej
ref: sefardyjskiej pred: sefardyjską
sefardyjskiemu sefardyjskiemu
sefardyjskim sefardyjskim
sefardyjskim sefardyjskim

nieodpowiedzialnym nieodpowiedzialnym
nieodpowiedzialnymi nieodpowiedzialnymi
szalu szalu
cyrkami cyrkami
cyrkiem cyrkiem
cyrki cyrki
cyrk cyrk
cyrk cyrk
cyrków cyrków
cyrku cyrku
ref: cyrku pred: cyrka
cyrku cyrku
najjaśniejsi najjaśniejsi
najjaśniejszą najjaśniejszą
najjaśniejsza najjaśniejsza
najjaśniejsze najjaśniejsze
najjaśniejsze najjaśniejsze
najjaśniejszego najjaśniejszego
najjaśniejszej najjaśniejszej
najjaśniejszej najjaśniejszej
najjaśniejszych najjaśniejszych
najjaśniejszych najjaśniejszych
najjaśniejszych najjaśniejszych
najjaśniejszym najjaśniejszym
najjaśniejszym najjaśniejszym
żenecie żenecie
żenetami żenetami
żenetą żenetą
żeneta żeneta
żenetę żenetę
żenet żenet
żenetom żenetom
żenety żenety
żenety żenety
żenety żenety
waściach waściach
waściami waściami
waści waści
waści waści
waści waści
waści waści
waści waści
waść waść
ref: otwarci pred: otwarcy
otwartą otwartą
otwarta otwarta
otwarte otwarte
otwarte otwarte
otwartego otwartego
otwartej otwartej
otwartej otwartej
otwartej otwartej
otwartemu otwartemu
otwartemu otwartemu
otwarty otwarty
otwarty otwarty
otwartych otwartych
otwartym otwartym
otwartym otwartym
otwartymi otwartymi
ref: dłużnicy pred: dłużniki
ref: dłużnicy pred: dłużniki
dłużnikami dłużnikami
dłużnika dłużnika
dłużnik dłużnik
dłużnikowi dłużnikowi
ref: manicure'ami pred: manicurami
ref: manicure'em pred: manicurem
manicure manicure
ref: manicure'om pred: manicurom
ref: manicure'y pred: manicury
ref: manicure'y pred: manicury
ref: manicure'y pred: manicury
ref: manicurze pred: manicurzu
sefardyjscy sefardyjscy
sefardyjski sefardyjski
sefardyjskich sefardyjskich
sefardyjskie sefardyjskie
sefardyjskiego sefardyjskiego
sefardyjskiego sefardyjskiego
sefardyjskiej sefardyjskiej
sefardyjskiej sefardyjskiej
sefardyjskiemu sefardyjskiemu
sefardyjskim sefardyjskim
sefardyjskim sefardyjskim
sefardyjskim sefardyjskim
sefardyjskimi sefardyjskimi
szynce szynce
szynce szynce
szynek szynek
szynkami szynkami
szynkę szynkę
szynki szynki
szynkom szynkom
szynko szynko
częstokołach częstokołach
częstokołami częstokołami
częstokole częstokole
częstokół częstokół
tulem tulem
tul tul
tulowi tulowi
tulu tulu
tulu tulu
ścianami ścianami
ściana ściana
ścianę ścianę
ścianom ścianom
ściano ściano
ściany ściany
ściany ściany
ref: baracheł pred: barachł
barachłach barachłach
barachła barachła
barachła barachła
barachła barachła
barachło barachło
barachło barachło
ref: barachłu pred: barachłowi
czczą czczą
czcza czcza
czcze czcze
czcze czcze
czcze czcze
czczego czczego
czczej czczej
czczej czczej
czczy czczy
czczych czczych
czczym czczym
czczym czczym
czczymi czczymi
ref: Indianach pred: Indianinach
ref: Indianie pred: Indianiny
Indianinie Indianinie
Indianinie Indianinie
Indianin Indianin
Indianinowi Indianinowi
ref: Indian pred: Indianiny
hodowlach hodowlach
hodowlą hodowlą
hodowla hodowla
hodowle hodowle
hodowli hodowli
hodowli hodowli
hodowli hodowli
hodowlom hodowlom
pacie pacie
ref: pacie pred: patze
patami patami
ref: pata pred: pat
pat pat
patowi patowi
patów patów
paty paty
ilustracjach ilustracjach
ilustracje ilustracje
ilustracje ilustracje
ilustracji ilustracji
ilustracjom ilustracjom
ilustracjo ilustracjo
rachunek rachunek
rachunek rachunek
rachunkach rachunkach
rachunkiem rachunkiem
rachunki rachunki
rachunkowi rachunkowi
rachunków rachunków
rachunku rachunku
rachunku rachunku
zimową zimową
zimową zimową
zimowa zimowa
zimowe zimowe
zimowe zimowe
zimowego zimowego
zimowego zimowego
zimowego zimowego
zimowej zimowej
zimowemu zimowemu
zimowy zimowy
zimowy zimowy
zimowych zimowych
zimowych zimowych
zimowym zimowym
zimowym zimowym
zimowym zimowym
rutenem rutenem
ruten ruten
chrabąszczach chrabąszczach
chrabąszczami chrabąszczami
ref: chrabąszcza pred: chrabąszcz
chrabąszczem chrabąszczem
chrabąszcze chrabąszcze
chrabąszcze chrabąszcze
chrabąszczom chrabąszczom
chrabąszczowi chrabąszczowi
chrabąszczy chrabąszczy
miarami miarami
miarę miarę
miar miar
miarom miarom
miaro miaro
miary miary
miary miary
ref: mierze pred: miarze
dzieżach dzieżach
dzieżami dzieżami
dzieżą dzieżą
dzieże dzieże
dzieże dzieże
dzieżom dzieżom
dzieżo dzieżo
dzieży dzieży
dzieży dzieży
małpeczce małpeczce
małpeczkach małpeczkach
małpeczkami małpeczkami
małpeczki małpeczki
małpeczkom małpeczkom
małpeczko małpeczko
koronach koronach
koroną koroną
korona korona
koronę koronę
koronie koronie
koronom koronom
korono korono
korony korony
korony korony
korony korony
ref: lipca pred: lipcu
lipce lipce
lipce lipce
lipce lipce
lipcom lipcom
lipców lipców
lipiec lipiec
lipiec lipiec
zupami zupami
zupą zupą
zupa zupa
zupie zupie
zup zup
zupo zupo
zupy zupy
zupy zupy
miocie miocie
miotach miotach
miotami miotami
miot miot
miotom miotom
miotowi miotowi
miotu miotu
mioty mioty
mioty mioty
mioty mioty
0.881
livles/slavic-distant-word-or-family
test file:  ../preprocessing/preprocessing_to_json/data/ces-lang-word_tst.json
ref: neptunštěji pred: neneneptunštěji
ref: neneptunštěji pred: neneneptunštěji
vulkanizovanosti vulkanizovanosti
vulkanizovanostech vulkanizovanostech
vulkanizovanostmi vulkanizovanostmi
vulkanizovanosti vulkanizovanosti
vulkanizovanosti vulkanizovanosti
zestarávajícíma zestarávajícíma
zestarávajících zestarávajících
zestarávajícím zestarávajícím
zestarávající zestarávající
zestarávajícími zestarávajícími
zestarávající zestarávající
zestarávajících zestarávajících
zestarávajícím zestarávajícím
zestarávající zestarávající
zestarávajícího zestarávajícího
zestarávajícímu zestarávajícímu
zestarávajícím zestarávajícím
zestarávajícím zestarávajícím
zestarávajícím zestarávajícím
zestarávající zestarávající
zestarávající zestarávající
zestarávajícího zestarávajícího
zestarávající zestarávající
zestarávajících zestarávajících
zestarávající zestarávající
zestarávajících zestarávajících
zestarávající zestarávající
zestarávajícího zestarávajícího
zestarávajícímu zestarávajícímu
zestarávajícím zestarávajícím
zestarávajícím zestarávajícím
natrucombudsmančiných natrucombudsmančiných
natrucombudsmančiny natrucombudsmančiny
natrucombudsmančinými natrucombudsmančinými
natrucombudsmančina natrucombudsmančina
natrucombudsmančiny natrucombudsmančiny
natrucombudsmančinu natrucombudsmančinu
natrucombudsmančina natrucombudsmančina
natrucombudsmančiny natrucombudsmančiny
natrucombudsmančiných natrucombudsmančiných
natrucombudsmančiným natrucombudsmančiným
natrucombudsmančiny natrucombudsmančiny
natrucombudsmančiných natrucombudsmančiných
natrucombudsmančinými natrucombudsmančinými
natrucombudsmančina natrucombudsmančina
natrucombudsmančin natrucombudsmančin
natrucombudsmančini natrucombudsmančini
ref: natrucombudsmančiny pred: natrucombudsmančiné
natrucombudsmančiných natrucombudsmančiných
natrucombudsmančin natrucombudsmančin
natrucombudsmančinu natrucombudsmančinu
natrucombudsmančině natrucombudsmančině
natrucombudsmančiným natrucombudsmančiným
natrucombudsmančina natrucombudsmančina
natrucombudsmančiných natrucombudsmančiných
natrucombudsmančina natrucombudsmančina
natrucombudsmančinu natrucombudsmančinu
natrucombudsmančino natrucombudsmančino
natrucombudsmančině natrucombudsmančině
opískovávacíma opískovávacíma
opískovávací opískovávací
opískovávací opískovávací
opískovávací opískovávací
opískovávacích opískovávacích
opískovávacími opískovávacími
opískovávací opískovávací
opískovávací opískovávací
opískovávací opískovávací
opískovávacími opískovávacími
opískovávacího opískovávacího
opískovávacímu opískovávacímu
opískovávací opískovávací
opískovávací opískovávací
opískovávací opískovávací
opískovávací opískovávací
opískovávací opískovávací
opískovávacích opískovávacích
opískovávací opískovávací
opískovávací opískovávací
opískovávacími opískovávacími
opískovávací opískovávací
opískovávacího opískovávacího
opískovávacímu opískovávacímu
opískovávací opískovávací
opískovávacím opískovávacím
vyžďuchanosti vyžďuchanosti
vyžďuchanosti vyžďuchanosti
vyžďuchanost vyžďuchanost
poveláky poveláky
poveláků poveláků
poveláky poveláky
ref: povelácích pred: povelákách
poveláky poveláky
ref: poveláku pred: poveláka
ref: poveláku pred: povelákovi
povelák povelák
ref: poveláku pred: povelák
poveláku poveláku
povelákem povelákem
ref: zrozkotávatelněji pred: nezrozkotávatelněji
nezrozkotávatelněji nezrozkotávatelněji

ref: nejzrozkotávatelněji pred: nejnezrozkotávatelněji
nejnezrozkotávatelněji nejnezrozkotávatelněji
dotlačováváme dotlačováváme
nedotlačováváme nedotlačováváme
dotlačováváte dotlačováváte
dotlačovávají dotlačovávají
dotlačovávám dotlačovávám
nedotlačovává nedotlačovává
dotlačovávat dotlačovávat
budu dotlačovávat budu dotlačovávat
nebudeš dotlačovávat nebudeš dotlačovávat
nebude dotlačovávat nebude dotlačovávat
nebudeme dotlačovávat nebudeme dotlačovávat
budete dotlačovávat budete dotlačovávat
nedotlačovávejte nedotlačovávejte
dotlačovávej dotlačovávej
dotlačovávali jste dotlačovávali jste
dotlačovávali bychom dotlačovávali bychom
dotlačovávali byste dotlačovávali byste
byli by dotlačovávali byli by dotlačovávali
byli byste dotlačovávali byli byste dotlačovávali
nedotlačovávali jsme nedotlačovávali jsme
nedotlačovávali jste nedotlačovávali jste
nedotlačovávali by nedotlačovávali by
nedotlačovávali byste nedotlačovávali byste
nebyli byste dotlačovávali nebyli byste dotlačovávali
ref: dotlačovávalo jsi pred: dotlačovávalos
dotlačovávalo by dotlačovávalo by
dotlačovávalo bych dotlačovávalo bych
dotlačovávalo bys dotlačovávalo bys
bylo by dotlačovávalo bylo by dotlačovávalo
ref: nedotlačovávalo jsi pred: nedotlačovávalos
nedotlačovávalo bych nedotlačovávalo bych
nedotlačovávalo bys nedotlačovávalo bys
nebylo bys dotlačovávalo nebylo bys dotlačovávalo
nedotlačovávalos nedotlačovávalos
dotlačovávala jsem dotlačovávala jsem
byla by dotlačovávala byla by dotlačovávala
dotlačovávala dotlačovávala
dotlačovávala jste dotlačovávala jste
dotlačovávala bychom dotlačovávala bychom
dotlačovávala byste dotlačovávala byste
byla by dotlačovávala byla by dotlačovávala
byla bychom dotlačovávala byla bychom dotlačovávala
byla byste dotlačovávala byla byste dotlačovávala
nedotlačovávala nedotlačovávala
nedotlačovávala by nedotlačovávala by
nedotlačovávala bych nedotlačovávala bych
nedotlačovávala bys nedotlačovávala bys
nebyla bych dotlačovávala nebyla bych dotlačovávala
nedotlačovávala nedotlačovávala
nedotlačovávala jsme nedotlačovávala jsme
nedotlačovávala bychom nedotlačovávala bychom
dotlačovávaly dotlačovávaly
dotlačovávaly byste dotlačovávaly byste
byly bychom dotlačovávaly byly bychom dotlačovávaly
dotlačovávaly jste dotlačovávaly jste
dotlačovávaly by dotlačovávaly by
dotlačovávaly bychom dotlačovávaly bychom
dotlačovávaly byste dotlačovávaly byste
byly bychom dotlačovávaly byly bychom dotlačovávaly
byly byste dotlačovávaly byly byste dotlačovávaly
nedotlačovávaly nedotlačovávaly
nedotlačovávaly by nedotlačovávaly by
nebyly byste dotlačovávaly nebyly byste dotlačovávaly
nedotlačovávaly jste nedotlačovávaly jste
nedotlačovávaly by nedotlačovávaly by
nebyly by dotlačovávaly nebyly by dotlačovávaly
nebyly bychom dotlačovávaly nebyly bychom dotlačovávaly
nebyly byste dotlačovávaly nebyly byste dotlačovávaly
dotlačovával jsem dotlačovával jsem
dotlačovával bys dotlačovával bys
byl bych dotlačovával byl bych dotlačovával
dotlačovávals dotlačovávals
nedotlačovával nedotlačovával
nedotlačovával bych nedotlačovával bych
nedotlačovával bys nedotlačovával bys
nebyl by dotlačovával nebyl by dotlačovával
nebyl bych dotlačovával nebyl bych dotlačovával
nedotlačovávals nedotlačovávals
dotlačovávánas dotlačovávánas
nedotlačovávánu nedotlačovávánu
dotlačováváni dotlačováváni
nedotlačovávános nedotlačovávános
dotlačováváno dotlačováváno
nedotlačováváno nedotlačováváno
nedotlačovávána nedotlačovávána
dotlačováván dotlačováván
nedotlačováván nedotlačováván
třicetihaléřovostem třicetihaléřovostem
třicetihaléřovosti třicetihaléřovosti
třicetihaléřovostech třicetihaléřovostech
třicetihaléřovosti třicetihaléřovosti
třicetihaléřovostí třicetihaléřovostí
delikventčiných delikventčiných
delikventčiných delikventčiných
delikventčinými delikventčinými
delikventčina delikventčina
delikventčiny delikventčiny
delikventčina delikventčina
delikventčině delikventčině
delikventčiny delikventčiny
delikventčiných delikventčiných
delikventčiným delikventčiným
delikventčiny delikventčiny
delikventčiných delikventčiných
delikventčinu delikventčinu
delikventčin delikventčin
delikventčině delikventčině
delikventčini delikventčini
delikventčiným delikventčiným
delikventčiných delikventčiných
delikventčinými delikventčinými
ref: delikventčinu pred: delikventčinumu
delikventčina delikventčina
delikventčině delikventčině
delikventčiným delikventčiným
delikventčina delikventčina
delikventčiným delikventčiným
delikventčina delikventčina
delikventčina delikventčina
delikventčiných delikventčiných
delikventčinými delikventčinými
delikventčinu delikventčinu
delikventčino delikventčino
delikventčině delikventčině
delikventčiným delikventčiným
vašnostovanosti vašnostovanosti
vašnostovanost vašnostovanost
vašnostovanosti vašnostovanosti
vašnostovanost vašnostovanost
zašmátravší zašmátravší
zašmátravšími zašmátravšími
zašmátravší zašmátravší
zašmátravší zašmátravší
zašmátravší zašmátravší
zašmátravší zašmátravší
zašmátravším zašmátravším
zašmátravší zašmátravší
zašmátravších zašmátravších
zašmátravšími zašmátravšími
zašmátravší zašmátravší
zašmátravšího zašmátravšího
zašmátravší zašmátravší
zašmátravších zašmátravších
zašmátravší zašmátravší
zašmátravší zašmátravší
zašmátravších zašmátravších
zašmátravší zašmátravší
zašmátravšího zašmátravšího
zašmátravšímu zašmátravšímu
zašmátravším zašmátravším
zašmátravší zašmátravší
zašmátravší zašmátravší
zašmátravší zašmátravší
zašmátravší zašmátravší
vyplavávajícíma vyplavávajícíma
vyplavávající vyplavávající
vyplavávající vyplavávající
vyplavávající vyplavávající
vyplavávající vyplavávající
vyplavávajícím vyplavávajícím
vyplavávajícími vyplavávajícími
vyplavávajícímu vyplavávajícímu
vyplavávajícím vyplavávajícím
vyplavávající vyplavávající
vyplavávajících vyplavávajících
vyplavávající vyplavávající
vyplavávající vyplavávající
vyplavávajících vyplavávajících
vyplavávající vyplavávající
vyplavávajícího vyplavávajícího
vyplavávající vyplavávající
vyplavávajícími vyplavávajícími
vyplavávajícímu vyplavávajícímu
vyplavávajícím vyplavávajícím
ref: přeťukávatelně pred: nepřeťukávatelně
nepřeťukávatelně nepřeťukávatelně
fotosenzitivníma fotosenzitivníma
fotosenzitivnějších fotosenzitivnějších
fotosenzitivnějším fotosenzitivnějším
nejfotosenzitivnějším nejfotosenzitivnějším
fotosenzitivní fotosenzitivní
fotosenzitivnější fotosenzitivnější
fotosenzitivních fotosenzitivních
fotosenzitivní fotosenzitivní
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivnější fotosenzitivnější
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivnější fotosenzitivnější
fotosenzitivnější fotosenzitivnější
fotosenzitivní fotosenzitivní
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivní fotosenzitivní
fotosenzitivnější fotosenzitivnější
fotosenzitivních fotosenzitivních
nejfotosenzitivnějších nejfotosenzitivnějších
fotosenzitivním fotosenzitivním
fotosenzitivní fotosenzitivní
fotosenzitivnější fotosenzitivnější
fotosenzitivní fotosenzitivní
fotosenzitivnější fotosenzitivnější
fotosenzitivnějších fotosenzitivnějších
nejfotosenzitivnějšími nejfotosenzitivnějšími
fotosenzitivní fotosenzitivní
fotosenzitivnější fotosenzitivnější
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivního fotosenzitivního
fotosenzitivnějšího fotosenzitivnějšího
nejfotosenzitivnějšího nejfotosenzitivnějšího
nejfotosenzitivnějšímu nejfotosenzitivnějšímu
fotosenzitivnější fotosenzitivnější
fotosenzitivnější fotosenzitivnější
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivním fotosenzitivním
fotosenzitivnějším fotosenzitivnějším
nejfotosenzitivnějším nejfotosenzitivnějším
fotosenzitivnějším fotosenzitivnějším
nejfotosenzitivnějším nejfotosenzitivnějším
fotosenzitivní fotosenzitivní
fotosenzitivnější fotosenzitivnější
fotosenzitivnějších fotosenzitivnějších
nejfotosenzitivnějších nejfotosenzitivnějších
fotosenzitivním fotosenzitivním
nejfotosenzitivnějším nejfotosenzitivnějším
fotosenzitivní fotosenzitivní
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivnější fotosenzitivnější
fotosenzitivnějších fotosenzitivnějších
fotosenzitivními fotosenzitivními
fotosenzitivnějšími fotosenzitivnějšími
nejfotosenzitivnějšími nejfotosenzitivnějšími
fotosenzitivní fotosenzitivní
fotosenzitivnějšího fotosenzitivnějšího

nejfotosenzitivnějšího nejfotosenzitivnějšího
fotosenzitivnímu fotosenzitivnímu
nejfotosenzitivnějšího nejfotosenzitivnějšího
fotosenzitivním fotosenzitivním
fotosenzitivnějším fotosenzitivnějším
fotosenzitivním fotosenzitivním
fotosenzitivnější fotosenzitivnější
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivním fotosenzitivním
fotosenzitivnějším fotosenzitivnějším
fotosenzitivnější fotosenzitivnější
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivnější fotosenzitivnější
fotosenzitivních fotosenzitivních
fotosenzitivnějšími fotosenzitivnějšími
fotosenzitivnější fotosenzitivnější
nejfotosenzitivnější nejfotosenzitivnější
fotosenzitivního fotosenzitivního
nejfotosenzitivnějšího nejfotosenzitivnějšího
fotosenzitivnímu fotosenzitivnímu
fotosenzitivnějšímu fotosenzitivnějšímu
nejfotosenzitivnějšímu nejfotosenzitivnějšímu
fotosenzitivní fotosenzitivní
fotosenzitivnější fotosenzitivnější
nejfotosenzitivnějším nejfotosenzitivnějším
pseudoekonomickosti pseudoekonomickosti
pseudoekonomickostí pseudoekonomickostí
pseudoekonomickostem pseudoekonomickostem
pseudoekonomickosti pseudoekonomickosti
pseudoekonomickost pseudoekonomickost
pseudoekonomickosti pseudoekonomickosti
idealizovávání idealizovávání
idealizovávání idealizovávání
idealizováváních idealizováváních
idealizovávání idealizovávání
idealizovávání idealizovávání
zaaltajštějšíma zaaltajštějšíma
nejzaaltajštějšíma nejzaaltajštějšíma
zaaltajské zaaltajské
nejzaaltajštější nejzaaltajštější
zaaltajštějších zaaltajštějších
zaaltajské zaaltajské
zaaltajštější zaaltajštější
nejzaaltajštější nejzaaltajštější
nejzaaltajštějších nejzaaltajštějších
zaaltajskými zaaltajskými
zaaltajštějšími zaaltajštějšími
nejzaaltajštější nejzaaltajštější
zaaltajské zaaltajské
zaaltajštější zaaltajštější
zaaltajské zaaltajské
nejzaaltajštější nejzaaltajštější
zaaltajštější zaaltajštější
nejzaaltajštější nejzaaltajštější
nejzaaltajštější nejzaaltajštější
zaaltajské zaaltajské
nejzaaltajštější nejzaaltajštější
zaaltajštějších zaaltajštějších
nejzaaltajštějších nejzaaltajštějších
zaaltajštějším zaaltajštějším
zaaltajské zaaltajské
zaaltajštější zaaltajštější
nejzaaltajštější nejzaaltajštější
zaaltajské zaaltajské
zaaltajskými zaaltajskými
zaaltajský zaaltajský
nejzaaltajštější nejzaaltajštější
zaaltajského zaaltajského
zaaltajskému zaaltajskému
zaaltajštějšímu zaaltajštějšímu
nejzaaltajštějšímu nejzaaltajštějšímu
zaaltajský zaaltajský
zaaltajštější zaaltajštější
zaaltajském zaaltajském
nejzaaltajštějším nejzaaltajštějším
zaaltajštějším zaaltajštějším
zaaltajští zaaltajští
nejzaaltajštější nejzaaltajštější
zaaltajských zaaltajských
zaaltajštějších zaaltajštějších
nejzaaltajštějších nejzaaltajštějších
zaaltajským zaaltajským
zaaltajštějším zaaltajštějším
nejzaaltajštějším nejzaaltajštějším
zaaltajští zaaltajští
zaaltajskými zaaltajskými
zaaltajský zaaltajský
nejzaaltajštější nejzaaltajštější
zaaltajského zaaltajského
nejzaaltajštějšího nejzaaltajštějšího
zaaltajštějšímu zaaltajštějšímu
nejzaaltajštějšímu nejzaaltajštějšímu
zaaltajštějšího zaaltajštějšího
zaaltajský zaaltajský
zaaltajštější zaaltajštější
nejzaaltajštější nejzaaltajštější
zaaltajském zaaltajském
nejzaaltajštějším nejzaaltajštějším
zaaltajským zaaltajským
zaaltajská zaaltajská
zaaltajštějších zaaltajštějších
zaaltajským zaaltajským
zaaltajštějším zaaltajštějším
zaaltajská zaaltajská
zaaltajštějších zaaltajštějších
nejzaaltajštějších nejzaaltajštějších
zaaltajštějšími zaaltajštějšími
zaaltajskému zaaltajskému
nejzaaltajštějšímu nejzaaltajštějšímu
zaaltajské zaaltajské
nejzaaltajštější nejzaaltajštější
nejzaaltajštějším nejzaaltajštějším
zaaltajštějším zaaltajštějším
nejzaaltajštějším nejzaaltajštějším
orlovitýma orlovitýma
orlovitých orlovitých
nejorlovitějších nejorlovitějších
orlovitějším orlovitějším
nejorlovitějším nejorlovitějším
orlovitější orlovitější
orlovité orlovité
nejorlovitější nejorlovitější
orlovitých orlovitých
nejorlovitějšími nejorlovitějšími
orlovitá orlovitá
nejorlovitější nejorlovitější
nejorlovitější nejorlovitější
orlovitá orlovitá
nejorlovitější nejorlovitější
orlovité orlovité
nejorlovitější nejorlovitější
orlovitější orlovitější
orlovité orlovité
nejorlovitější nejorlovitější
orlovité orlovité
orlovitý orlovitý
nejorlovitější nejorlovitější
orlovitému orlovitému
orlovitějšímu orlovitějšímu
nejorlovitější nejorlovitější
orlovitý orlovitý
nejorlovitější nejorlovitější
ref: orlovitějším pred: orlovičtějším
nejorlovitějším nejorlovitějším
orlovitým orlovitým
orlovití orlovití
nejorlovitější nejorlovitější
orlovitějších orlovitějších
nejorlovitějších nejorlovitějších
orlovitým orlovitým
orlovitějším orlovitějším
orlovité orlovité
ref: nejorlovitější pred: nejorlovičtější
orlovitých orlovitých
orlovitějšími orlovitějšími
nejorlovitější nejorlovitější
orlovitějšího orlovitějšího
nejorlovitějšího nejorlovitějšího
orlovitému orlovitému
orlovitějšího orlovitějšího
orlovitý orlovitý
orlovitém orlovitém
orlovitějším orlovitějším
nejorlovitějším nejorlovitějším
nejorlovitějším nejorlovitějším
orlovitá orlovitá
orlovitější orlovitější
orlovitých orlovitých
nejorlovitější nejorlovitější
nejorlovitější nejorlovitější
nejorlovitějších nejorlovitějších
nejorlovitějšími nejorlovitějšími
ref: orlovitější pred: orlovičtější
nejorlovitějšího nejorlovitějšího
orlovitému orlovitému
orlovitějšímu orlovitějšímu
nejorlovitějšímu nejorlovitějšímu
ref: orlovitější pred: orlovičtější
nejorlovitější nejorlovitější
nejorlovitějším nejorlovitějším
revokujících revokujících
revokující revokující
revokujících revokujících
revokujícími revokujícími
revokující revokující
revokující revokující
revokující revokující
revokující revokující
revokujících revokujících
revokující revokující
revokujícího revokujícího
revokující revokující
revokujícím revokujícím
revokující revokující
revokujícími revokujícími
revokujícímu revokujícímu
revokujícím revokujícím
revokujícím revokujícím
revokujících revokujících
revokujících revokujících
revokujícího revokujícího
revokujícímu revokujícímu
revokující revokující
protiokupantskostech protiokupantskostech
protiokupantskostmi protiokupantskostmi
protiokupantskost protiokupantskost
protiokupantskosti protiokupantskosti
protiokupantskostí protiokupantskostí
oprasenosti oprasenosti
oprasenosti oprasenosti
oprasenostech oprasenostech
oprasenostmi oprasenostmi
oprasenosti oprasenosti
oprasenosti oprasenosti
nejkomeniologičtější nejkomeniologičtější
komeniologické komeniologické
komeniologičtější komeniologičtější
nejkomeniologičtější nejkomeniologičtější
komeniologické komeniologické
nejkomeniologičtější nejkomeniologičtější
komeniologičtějších komeniologičtějších
nejkomeniologičtějších nejkomeniologičtějších
komeniologickými komeniologickými
nejkomeniologičtějšími nejkomeniologičtějšími
nejkomeniologičtější nejkomeniologičtější
komeniologičtější komeniologičtější
komeniologická komeniologická
komeniologické komeniologické
komeniologičtější komeniologičtější
komeniologičtější komeniologičtější
nejkomeniologičtější nejkomeniologičtější
komeniologičtějších komeniologičtějších
komeniologickým komeniologickým
nejkomeniologičtějším nejkomeniologičtějším
komeniologické komeniologické
komeniologičtější komeniologičtější
komeniologických komeniologických
komeniologičtějších komeniologičtějších
nejkomeniologičtějších nejkomeniologičtějších
komeniologickými komeniologickými
komeniologický komeniologický
komeniologičtější komeniologičtější
nejkomeniologičtější nejkomeniologičtější
komeniologického komeniologického
nejkomeniologičtějšího nejkomeniologičtějšího
nejkomeniologičtějšímu nejkomeniologičtějšímu
komeniologický komeniologický
komeniologický komeniologický
komeniologičtější komeniologičtější
komeniologickém komeniologickém
komeniologičtějším komeniologičtějším
nejkomeniologičtějším nejkomeniologičtějším
komeniologických komeniologických
nejkomeniologičtějších nejkomeniologičtějších
komeniologičtějším komeniologičtějším
nejkomeniologičtějším nejkomeniologičtějším
komeniologické komeniologické
komeniologičtější komeniologičtější
nejkomeniologičtější nejkomeniologičtější
ref: komeniologičtí pred: komeniologickí
nejkomeniologičtější nejkomeniologičtější
komeniologických komeniologických
komeniologičtějších komeniologičtějších
komeniologičtější komeniologičtější

komeniologického komeniologického
komeniologičtějšího komeniologičtějšího
komeniologičtějšího komeniologičtějšího
nejkomeniologičtějšího nejkomeniologičtějšího
nejkomeniologičtější nejkomeniologičtější
nejkomeniologičtějším nejkomeniologičtějším
komeniologická komeniologická
komeniologičtějších komeniologičtějších
komeniologičtějším komeniologičtějším
komeniologičtější komeniologičtější
nejkomeniologičtější nejkomeniologičtější
komeniologická komeniologická
komeniologičtější komeniologičtější
nejkomeniologičtější nejkomeniologičtější
komeniologických komeniologických
nejkomeniologičtějších nejkomeniologičtějších
komeniologičtější komeniologičtější
nejkomeniologičtější nejkomeniologičtější
komeniologickému komeniologickému
komeniologičtějšímu komeniologičtějšímu
komeniologické komeniologické
komeniologické komeniologické
nejkomeniologičtější nejkomeniologičtější
komeniologičtějším komeniologičtějším
komeniologickým komeniologickým
komeniologičtějším komeniologičtějším
tachonýrovy tachonýrovy
tachonýrových tachonýrových
tachonýrovým tachonýrovým
tachonýrovy tachonýrovy
tachonýrových tachonýrových
tachonýrovu tachonýrovu
tachonýrovou tachonýrovou
tachonýrových tachonýrových
tachonýrovým tachonýrovým
tachonýrových tachonýrových
tachonýrův tachonýrův
tachonýrova tachonýrova
tachonýrových tachonýrových
tachonýrovy tachonýrovy
tachonýrovi tachonýrovi
tachonýrův tachonýrův
tachonýrova tachonýrova
tachonýrova tachonýrova
tachonýrův tachonýrův
tachonýrově tachonýrově
tachonýrových tachonýrových
tachonýrova tachonýrova
tachonýrovo tachonýrovo
tachonýrova tachonýrova
tachonýrovu tachonýrovu
tachonýrovo tachonýrovo
tachonýrově tachonýrově
tachonýrovým tachonýrovým
procesovatelnosti procesovatelnosti
procesovatelnosti procesovatelnosti
procesovatelnostmi procesovatelnostmi
procesovatelnosti procesovatelnosti
procesovatelnosti procesovatelnosti
procesovatelností procesovatelností
poměřovávacích poměřovávacích
poměřovávací poměřovávací
poměřovávací poměřovávací
poměřovávací poměřovávací
poměřovávacích poměřovávacích
poměřovávacím poměřovávacím
poměřovávacímu poměřovávacímu
poměřovávacím poměřovávacím
poměřovávací poměřovávací
poměřovávacím poměřovávacím
poměřovávací poměřovávací
poměřovávací poměřovávací
poměřovávacího poměřovávacího
poměřovávacím poměřovávacím
poměřovávacím poměřovávacím
poměřovávacích poměřovávacích
poměřovávací poměřovávací
poměřovávacích poměřovávacích
poměřovávací poměřovávací
poměřovávacímu poměřovávacímu
poměřovávací poměřovávací
Brooklyňančinýma Brooklyňančinýma
Brooklyňančiny Brooklyňančiny
Brooklyňančiny Brooklyňančiny
Brooklyňančinými Brooklyňančinými
Brooklyňančina Brooklyňančina
Brooklyňančině Brooklyňančině
Brooklyňančina Brooklyňančina
Brooklyňančiných Brooklyňančiných
Brooklyňančinými Brooklyňančinými
Brooklyňančin Brooklyňančin
Brooklyňančina Brooklyňančina
Brooklyňančin Brooklyňančin
Brooklyňančině Brooklyňančině
Brooklyňančiným Brooklyňančiným
Brooklyňančini Brooklyňančini
Brooklyňančiných Brooklyňančiných
Brooklyňančiným Brooklyňančiným
Brooklyňančini Brooklyňančini
Brooklyňančiných Brooklyňančiných
Brooklyňančin Brooklyňančin
Brooklyňančina Brooklyňančina
Brooklyňančinu Brooklyňančinu
Brooklyňančině Brooklyňančině
Brooklyňančiných Brooklyňančiných
Brooklyňančinu Brooklyňančinu
Brooklyňančino Brooklyňančino
ref: vytíratelně pred: nevytíratelně
ref: vytíratelněji pred: nevytíratelněji
čimčarávatelnosti čimčarávatelnosti
čimčarávatelnostem čimčarávatelnostem
čimčarávatelnosti čimčarávatelnosti
čimčarávatelnostmi čimčarávatelnostmi
čimčarávatelnosti čimčarávatelnosti
čimčarávatelnost čimčarávatelnost
čimčarávatelnosti čimčarávatelnosti
čimčarávatelnosti čimčarávatelnosti
nedeikticky nedeikticky
ref: deiktičtěji pred: nedeiktičtěji
ref: nejdeiktičtěji pred: nejnedeiktičtěji
nejnedeiktičtěji nejnedeiktičtěji
navrtací navrtací
navrtací navrtací
navrtacích navrtacích
navrtacími navrtacími
navrtací navrtací
navrtací navrtací
navrtací navrtací
navrtací navrtací
navrtací navrtací
navrtací navrtací
navrtacích navrtacích
navrtacím navrtacím
navrtacími navrtacími
navrtací navrtací
navrtacího navrtacího
navrtacímu navrtacímu
navrtacím navrtacím
navrtací navrtací
navrtacích navrtacích
navrtacím navrtacím
navrtací navrtací
navrtací navrtací
navrtacího navrtacího
navrtací navrtací
navrtacím navrtacím
navrtací navrtací
navrtacími navrtacími
navrtacího navrtacího
navrtacímu navrtacímu
navrtacím navrtacím
navrtacím navrtacím
volšovskosti volšovskosti
volšovskostem volšovskostem
volšovskosti volšovskosti
volšovskostech volšovskostech
volšovskosti volšovskosti
volšovskosti volšovskosti
vklouzacíma vklouzacíma
vklouzací vklouzací
vklouzací vklouzací
vklouzacích vklouzacích
vklouzacími vklouzacími
vklouzací vklouzací
vklouzací vklouzací
vklouzací vklouzací
vklouzací vklouzací
vklouzacími vklouzacími
vklouzacím vklouzacím
vklouzacím vklouzacím
vklouzací vklouzací
vklouzacími vklouzacími
vklouzacího vklouzacího
vklouzacím vklouzacím
vklouzací vklouzací
vklouzacímu vklouzacímu
vklouzací vklouzací
načeřitelnosti načeřitelnosti
načeřitelností načeřitelností
načeřitelnosti načeřitelnosti
načeřitelnostmi načeřitelnostmi
načeřitelnost načeřitelnost
načeřitelnost načeřitelnost
načeřitelnosti načeřitelnosti
načeřitelnosti načeřitelnosti
ref: odorizačně pred: neodorizačně
ref: odorizačněji pred: neodorizačněji
neodorizačněji neodorizačněji
ref: vysoptěně pred: nevysoptěně
odstřídávatelností odstřídávatelností
odstřídávatelnosti odstřídávatelnosti
odstřídávatelnosti odstřídávatelnosti
odstřídávatelnostmi odstřídávatelnostmi
odstřídávatelnost odstřídávatelnost
odstřídávatelnosti odstřídávatelnosti
odstřídávatelností odstřídávatelností
joly joly
jolám jolám
joly joly
joly joly
jola jola
joly joly
ref: jole pred: jolě
jolu jolu
ref: jolo pred: jola
ref: jole pred: jolě
jolou jolou
odvzdušněností odvzdušněností
odvzdušněnosti odvzdušněnosti
odvzdušněnostech odvzdušněnostech
odvzdušněnostmi odvzdušněnostmi
odvzdušněnost odvzdušněnost
odvzdušněnosti odvzdušněnosti
odvzdušněnosti odvzdušněnosti
odvzdušněností odvzdušněností
nejmalokvětěji nejmalokvětěji
ref: nejnemalokvětěji pred: nejmalokvětěji
ref: celiakií pred: celiakých
ref: celiakiím pred: celiakim
celiakie celiakie
ref: celiakiemi pred: celiakimi
celiakie celiakie
celiakie celiakie
ref: celiakii pred: celiakiej
ref: celiakii pred: celiaké
ref: celiakií pred: celiakou
čtyřiapadesátisvazkovějšíma čtyřiapadesátisvazkovějšíma
nejčtyřiapadesátisvazkovějšíma nejčtyřiapadesátisvazkovějšíma
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkových čtyřiapadesátisvazkových
nejčtyřiapadesátisvazkovějších nejčtyřiapadesátisvazkovějších
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkovějších čtyřiapadesátisvazkovějších
nejčtyřiapadesátisvazkovějších nejčtyřiapadesátisvazkovějších
čtyřiapadesátisvazkovými čtyřiapadesátisvazkovými
čtyřiapadesátisvazkovějšími čtyřiapadesátisvazkovějšími
nejčtyřiapadesátisvazkovějšími nejčtyřiapadesátisvazkovějšími
čtyřiapadesátisvazkové čtyřiapadesátisvazkové
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkové čtyřiapadesátisvazkové
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkovou čtyřiapadesátisvazkovou
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkové čtyřiapadesátisvazkové
čtyřiapadesátisvazkové čtyřiapadesátisvazkové
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkových čtyřiapadesátisvazkových
čtyřiapadesátisvazkovějším čtyřiapadesátisvazkovějším
nejčtyřiapadesátisvazkovějším nejčtyřiapadesátisvazkovějším
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
nejčtyřiapadesátisvazkovějších nejčtyřiapadesátisvazkovějších
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkového čtyřiapadesátisvazkového
čtyřiapadesátisvazkovějšího čtyřiapadesátisvazkovějšího
nejčtyřiapadesátisvazkovějšího nejčtyřiapadesátisvazkovějšího
čtyřiapadesátisvazkovému čtyřiapadesátisvazkovému

nejčtyřiapadesátisvazkovějšímu nejčtyřiapadesátisvazkovějšímu
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkovém čtyřiapadesátisvazkovém
čtyřiapadesátisvazkovějším čtyřiapadesátisvazkovějším
nejčtyřiapadesátisvazkovějším nejčtyřiapadesátisvazkovějším
čtyřiapadesátisvazkoví čtyřiapadesátisvazkoví
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkových čtyřiapadesátisvazkových
čtyřiapadesátisvazkovějších čtyřiapadesátisvazkovějších
nejčtyřiapadesátisvazkovějších nejčtyřiapadesátisvazkovějších
nejčtyřiapadesátisvazkovějším nejčtyřiapadesátisvazkovějším
čtyřiapadesátisvazkové čtyřiapadesátisvazkové
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkoví čtyřiapadesátisvazkoví
čtyřiapadesátisvazkovějších čtyřiapadesátisvazkovějších
čtyřiapadesátisvazkovými čtyřiapadesátisvazkovými
čtyřiapadesátisvazkovějšími čtyřiapadesátisvazkovějšími
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkového čtyřiapadesátisvazkového
nejčtyřiapadesátisvazkovějšího nejčtyřiapadesátisvazkovějšího
čtyřiapadesátisvazkovému čtyřiapadesátisvazkovému
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkovějším čtyřiapadesátisvazkovějším
čtyřiapadesátisvazková čtyřiapadesátisvazková
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkovým čtyřiapadesátisvazkovým
čtyřiapadesátisvazkovějším čtyřiapadesátisvazkovějším
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazková čtyřiapadesátisvazková
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkových čtyřiapadesátisvazkových
čtyřiapadesátisvazkovějších čtyřiapadesátisvazkovějších
čtyřiapadesátisvazkové čtyřiapadesátisvazkové
nejčtyřiapadesátisvazkovější nejčtyřiapadesátisvazkovější
čtyřiapadesátisvazkovějšího čtyřiapadesátisvazkovějšího
nejčtyřiapadesátisvazkovějšího nejčtyřiapadesátisvazkovějšího
čtyřiapadesátisvazkovější čtyřiapadesátisvazkovější
čtyřiapadesátisvazkovějším čtyřiapadesátisvazkovějším
nejčtyřiapadesátisvazkovějším nejčtyřiapadesátisvazkovějším
zavrhovávanosti zavrhovávanosti
zavrhovávanost zavrhovávanost
zavrhovávanosti zavrhovávanosti
zavrhovávanost zavrhovávanost
zavrhovávanosti zavrhovávanosti
ref: přelousknutelně pred: nepřelousknutelně
ref: přelousknutelněji pred: nepřelousknutelněji
nepřelousknutelněji nepřelousknutelněji
nenainstalovávatelně nenainstalovávatelně
ref: nainstalovávatelněji pred: nenainstalovávatelněji
ref: nebezpříčinně pred: bezpříčinně
ref: nebezpříčinněji pred: bezpříčinněji
nejbezpříčinněji nejbezpříčinněji
rozlinutí rozlinutí
rozlinutí rozlinutí
rozlinutí rozlinutí
nejchangajštějšíma nejchangajštějšíma
changajské changajské
changajštější changajštější
nejchangajštější nejchangajštější
changajských changajských
nejchangajštějších nejchangajštějších
nejchangajštějším nejchangajštějším
changajské changajské
changajštější changajštější
nejchangajštější nejchangajštější
changajštější changajštější
nejchangajštější nejchangajštější
changajských changajských
changajštějších changajštějších
nejchangajštějších nejchangajštějších
changajskými changajskými
changajštějšími changajštějšími
nejchangajštější nejchangajštější
nejchangajštější nejchangajštější
changajských changajských
changajštějších changajštějších
nejchangajštějších nejchangajštějších
changajštějším changajštějším
nejchangajštějším nejchangajštějším
changajské changajské
changajštější changajštější
changajštějších changajštějších
nejchangajštějšími nejchangajštějšími
changajský changajský
nejchangajštějšího nejchangajštějšího
changajštějšímu changajštějšímu
nejchangajštějšímu nejchangajštějšímu
nejchangajštější nejchangajštější
changajštější changajštější
changajském changajském
changajštějším changajštějším
changajštějším changajštějším
changajští changajští
nejchangajštější nejchangajštější
changajských changajských
nejchangajštějších nejchangajštějších
changajským changajským
changajštějším changajštějším
changajské changajské
nejchangajštější nejchangajštější
changajští changajští
changajských changajských
nejchangajštějších nejchangajštějších
changajskými changajskými
changajskému changajskému
nejchangajštějšího nejchangajštějšího
nejchangajštější nejchangajštější
nejchangajštějším nejchangajštějším
nejchangajštějším nejchangajštějším
changajská changajská
changajštějších changajštějších
nejchangajštějších nejchangajštějších
changajským changajským
changajštějším changajštějším
nejchangajštějším nejchangajštějším
changajštější changajštější
nejchangajštější nejchangajštější
changajštější changajštější
changajských changajských
nejchangajštějších nejchangajštějších
changajské changajské
nejchangajštější nejchangajštější
nejchangajštějšího nejchangajštějšího
changajskému changajskému
nejchangajštější nejchangajštější
nejchangajštějším nejchangajštějším
nejchangajštějším nejchangajštějším
ohromovávanosti ohromovávanosti
ohromovávanostem ohromovávanostem
ohromovávanosti ohromovávanosti
ohromovávanostmi ohromovávanostmi
ohromovávanost ohromovávanost
ohromovávanosti ohromovávanosti
ohromovávanost ohromovávanost
ohromovávanosti ohromovávanosti
ohromovávaností ohromovávaností
0.96
livles/slavic-distant-word-or-family
test file:  ../preprocessing/preprocessing_to_json/data/csb-lang-word_tst.json
ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzaczom pred: narzãdzôczam
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczama pred: narzãdzôczami
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczowi pred: narzãdzôczoju
ref: narzãdzacza pred: narzãdzôcza
ref: narzãdzaczach pred: narzãdzôczach
ref: narzãdzaczów pred: narzãdzôczy
ref: narzãdzaczã pred: narzãdzôczom
ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzacza pred: narzãdzôcz
narzãdzôcz narzãdzôcz
ref: narzãdzacze pred: narzãdzôcze
ref: Jastrë pred: Jastrje
Jastrach Jastrach
ref: Jastróm pred: Jastram
ref: Jastrów pred: Jastrow
ref: Jastrama pred: Jastrje
ref: Jastrë pred: Jastrje
ref: Jastrë pred: Jastrje
ref: pòniedzałczi pred: pòniedzôłki
ref: pòniedzałkóm pred: pòniedzôłkam
ref: pòniedzałkù pred: pòniedzôłku
ref: pòniedzałkama pred: pòniedzôłkami
ref: pòniedzałkù pred: pòniedzôłku
ref: poniedzałkòwi pred: pòniedzôłkoju
ref: pòniedzałkù pred: pòniedzôłka
ref: pòniedzałkach pred: pòniedzôłkach
ref: pòniedzałków pred: pòniedzôłkow
ref: pòniedzałkã pred: pòniedzôłkiem
ref: pòniedzałczi pred: pòniedzôłki
pòniedzôłk pòniedzôłk
pòniedzôłk pòniedzôłk
ref: pòniedzałczi pred: pòniedzôłki
ref: pùjczi pred: pùjki
ref: pùjkom pred: pùjkam
ref: pùjkù pred: pùjku
ref: pùjkama pred: pùjkami
ref: pùjkù pred: pùjku
ref: pùjkòwi pred: pùjkoju
pùjka pùjka
pùjkach pùjkach
ref: pùjków pred: pùjkow
ref: pùjkã pred: pùjkom
ref: pùjczi pred: pùjki
ref: pùjka pred: pùjk
pùjk pùjk
ref: pùjczi pred: pùjki
ref: môlniczi pred: môlniki
ref: môlnikòm pred: môlnikam
ref: môlnikù pred: môlniku
ref: môlnikama pred: môlnikami
ref: môlnikù pred: môlniku
ref: môlnikòwi pred: môlnikoju
môlnika môlnika
môlnikach môlnikach
ref: môlników pred: môlnikow
ref: môlnikã pred: môlnikom
ref: môlniczi pred: môlniki
ref: môlnik pred: môlnika
môlnik môlnik
ref: môlniczi pred: môlniki
ref: wòłiwaczë pred: wòłiwôcze
ref: wòłiwaczom pred: wòłiwôczam
ref: wòłiwaczu pred: wòłiwôczu
ref: wòłiwaczama pred: wòłiwôczami
ref: wòłiwaczu pred: wòłiwôczu
ref: wòłiwaczowi pred: wòłiwôczoju
ref: wòłiwacza pred: wòłiwôcza
ref: wòłiwaczach pred: wòłiwôczach
ref: wòłiwaczów pred: wòłiwôczow
ref: wòłiwaczã pred: wòłiwôczom
ref: wòłiwaczë pred: wòłiwôcze
ref: wòłiwacza pred: wòłiwôcz
wòłiwôcz wòłiwôcz
ref: wòłiwaczë pred: wòłiwôcze
ref: łżëkwiôtë pred: łżëkwiôty
ref: łżëkwiôtom pred: łżëkwiotam
ref: łżëkwiôce pred: łżëkwiôto
ref: łżëkwiôtama pred: łżëkwiotami
ref: łżëkwiôce pred: łżëkwiôcie
ref: łżëkwiôtowi pred: łżëkwiôtoju
łżëkwiôta łżëkwiôta
ref: łżëkwiôtach pred: łżëkwiotach
ref: łżëkwiôtów pred: łżëkwiotow
ref: łżëkwiôtã pred: łżëkwiôtom
ref: łżëkwiôtë pred: łżëkwioty
ref: łżëkwiôta pred: łżëkwiôt
łżëkwiôt łżëkwiôt
ref: łżëkwiôtë pred: łżëkwioty
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnikòm pred: lëstopadnikam
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikama pred: lëstopadnikami
ref: lëstopadnikù pred: lëstopadniku

ref: lëstopadnikòwi pred: lëstopadnikoju
lëstopadnika lëstopadnika
lëstopadnikach lëstopadnikach
ref: lëstopadników pred: lëstopadnikow
ref: lëstopadnikã pred: lëstopadnikom
ref: lëstopadniczi pred: lëstopadniki
lëstopadnika lëstopadnika
lëstopadnik lëstopadnik
ref: lëstopadniczi pred: lëstopadniki
ref: sobòtë pred: sobòty
ref: sobòtóm pred: sobòtam
sobòto sobòto
ref: sobòtama pred: sobòtami
ref: sobòce pred: sobòśe
ref: sobòce pred: sobòtje
ref: sobòtë pred: sobòty
sobòtach sobòtach
ref: sobòtów pred: sobòtow
ref: sobòtã pred: sobòtu
ref: sobòtë pred: sobòty
ref: sobòtã pred: sobòtu
sobòta sobòta
ref: sobòtë pred: sobòty
ref: kònie pred: kónje
ref: kòniom pred: kónjam
ref: kòniu pred: kónju
ref: kòniama pred: kónjami
ref: kòniu pred: kónju
ref: kòniowi pred: kónjoju
ref: kònia pred: kónja
ref: kòniach pred: kónjach
ref: kòni pred: kónjow
ref: kòniã pred: kónjom
ref: kònie pred: kónje
ref: kònia pred: kónj
kóń kóń
ref: kònie pred: kónje
ref: nazéwacze pred: nazéwôcze
ref: nazéwaczom pred: nazéwôczam
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczama pred: nazéwôczami
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczowi pred: nazéwôczoju
ref: nazéwacza pred: nazéwôcza
ref: nazéwaczach pred: nazéwôczach
ref: nazéwaczów pred: nazéwôczow
ref: nazéwaczã pred: nazéwôczom
ref: nazéwacze pred: nazéwôcze
ref: nazéwacza pred: nazéwôcz
nazéwôcz nazéwôcz
ref: nazéwacze pred: nazéwôcze
ref: piątczi pred: piątki
ref: piątkóm pred: piątkom
ref: piątkù pred: piątku
ref: piątkama pred: piątkami
ref: piątkù pred: piątku
ref: piątkòwi pred: piątkowi
ref: piątkù pred: piątka
piątkach piątkach
piątków piątków
ref: piątkã pred: piątkiem
ref: piątczi pred: piątki
piątk piątk
piątk piątk
ref: piątczi pred: piątki
ref: rënczi pred: rënki
ref: rënkóm pred: rënkam
ref: stolem pred: rënku
ref: rënkama pred: rënkami
ref: rënkù pred: rënku
ref: rënkòwi pred: rënkoju
ref: rënkù pred: rënka
rënkach rënkach
ref: rënków pred: rënkow
ref: rënkã pred: rënkom
ref: rënczi pred: rënki
rënk rënk
rënk rënk
ref: rënczi pred: rënki
ref: wtórczi pred: wtórki
ref: wtórkòm pred: wtórkam
ref: wtórkù pred: wtórku
ref: wtórkama pred: wtórkami
ref: wtórkù pred: wtórku
ref: wtórkòwi pred: wtórkoju
wtórka wtórka
wtórkach wtórkach
ref: wtórków pred: wtórkow
ref: wtórkã pred: wtórkom
ref: wtórczi pred: wtórki
wtórk wtórk
wtórk wtórk
ref: wtórczi pred: wtórki
ref: winowacze pred: winowôcze
ref: winowaczom pred: winowôczam
ref: winowaczu pred: winowôczu
ref: winowaczama pred: winowôczami
ref: winowaczu pred: winowôczu
ref: winowaczowi pred: winowôczoju
ref: winowacza pred: winowôcza
ref: winowaczach pred: winowôczach
ref: winowaczów pred: winowôczow
ref: winowaczã pred: winowôczom
ref: winowacze pred: winowôcze
ref: winowacza pred: winowôcz
winowôcz winowôcz
ref: winowacze pred: winowôcze
ref: òjcowie pred: òjcy
ref: òjcóm pred: òjcam
ref: òjcze pred: òjco
ref: òjcama pred: òjcami
òjcu òjcu
ref: òjcu pred: òjcoju
òjca òjca
òjcach òjcach
ref: òjców pred: òjcow
ref: òjcã pred: òjcom
ref: òjcem pred: òjcom
ref: òjców pred: òjcy
ref: òjca pred: òjc
òjc òjc
ref: òjcowie pred: òjcy
ref: latawiska pred: latawiskowie
ref: latawiskóm pred: latawiskom
ref: latawiskù pred: latawisko
ref: latawiskama pred: latawiskomi
ref: latawiskù pred: latawiskoju
ref: latawiskù pred: latawiskoju
ref: latawiska pred: latawiskowu
ref: latawiskach pred: latawiskoch
ref: latawisków pred: latawiskow
ref: latawiskã pred: latawiskòm
ref: latawiska pred: latawiskow
latawiskò latawiskò
latawiskò latawiskò
ref: latawiska pred: latawiskowie
ref: Jastra pred: Jastry
Jastrach Jastrach
ref: Jastróm pred: Jastram
ref: Jastrów pred: Jastrow
ref: Jastrama pred: Jastry
ref: Jastra pred: Jastry
ref: Jastra pred: Jastry
czerwińce czerwińce
ref: czerwińcom pred: czerwińcam
czerwińcu czerwińcu
ref: czerwińcama pred: czerwińcami
czerwińcu czerwińcu
ref: czerwińcowi pred: czerwińcoju
czerwińca czerwińca
czerwińcach czerwińcach
ref: czerwińców pred: czerwińcow
ref: czerwińcã pred: czerwińcom
czerwińce czerwińce
czerwińca czerwińca
czerwińc czerwińc
ref: czerwińc pred: czerwińce
ref: rujanë pred: rujany
ref: rujanom pred: rujanam
rujanie rujanie
ref: rujanama pred: rujanami
ref: rujanie pred: rujanje
ref: rujanowi pred: rujanoju
rujana rujana
rujanach rujanach
ref: rujanów pred: rujanow
ref: rujanã pred: rujanom
ref: rujanë pred: rujany
ref: rujana pred: rujan
rujan rujan
ref: rujanë pred: rujany
ref: dôwacze pred: dôwôcze
ref: dôwaczom pred: dôwôczam
ref: dôwaczu pred: dôwôczu
ref: dôwaczama pred: dôwôczami
ref: dôwaczu pred: dôwôczu
ref: dôwaczowi pred: dôwôczoju
dôwôcza dôwôcza
ref: dôwaczach pred: dôwôczach
ref: dôwaczów pred: dôwôczow
ref: dôwaczã pred: dôwôczom
ref: dôwacze pred: dôwôcze
ref: dôwacza pred: dôwôcz
dôwôcz dôwôcz
ref: dôwacze pred: dôwôcze
serca serca
ref: sercóm pred: sercam
serce serce
ref: sercama pred: sercami
sercu sercu
ref: serce pred: sercu
ref: sercu pred: sercoju
serca serca
sercach sercach
ref: serców pred: sercow
ref: serc pred: sercow
ref: sercã pred: sercom
ref: sercem pred: sercom
ref: serca pred: serce
serce serce
serce serce
serca serca
ref: lëpince pred: lëpincy
ref: lëpincom pred: lëpincam
lëpincu lëpincu
ref: lëpincama pred: lëpincami
lëpincu lëpincu
ref: lëpincowi pred: lëpincoju
lëpinca lëpinca
lëpincach lëpincach
ref: lëpinców pred: lëpincow
ref: lëpincã pred: lëpincom
lëpince lëpince
lëpinc lëpinc
lëpinc lëpinc
ref: lëpince pred: lëpincy
ref: séwniczi pred: séwniki
ref: séwnikòm pred: séwnikam
ref: séwnikù pred: séwniku
ref: séwnikama pred: séwnikami
ref: séwnikù pred: séwniku
ref: séwnikòwi pred: séwnikoju
séwnika séwnika
séwnikach séwnikach
ref: séwników pred: séwnikow
ref: séwnikã pred: séwnikom
ref: séwniczi pred: séwniki
séwnika séwnika
séwnik séwnik
ref: séwniczi pred: séwniki
ref: zélniczi pred: zélniki
ref: zélnikòm pred: zélnikam
ref: zélnikù pred: zélniku
ref: zélnikama pred: zélnikami
ref: zélnikù pred: zélniku
ref: zélnikòwi pred: zélnikoju
zélnika zélnika
zélnikach zélnikach
ref: zélników pred: zélnikow
ref: zélnikã pred: zélnikom
ref: zélniczi pred: zélniki
zélnika zélnika
zélnik zélnik
ref: zélniczi pred: zélniki
ref: stëczniczi pred: stëczniki
ref: stëcznikòm pred: stëcznikam
ref: stëcznikù pred: stëczniku
ref: stëcznikama pred: stëcznikami
ref: stëcznikù pred: stëczniku
ref: stëcznikòwi pred: stëcznikoju
stëcznika stëcznika
stëcznikach stëcznikach
ref: stëczników pred: stëcznikow
ref: stëcznikã pred: stëcznikom
ref: stëczniczi pred: stëczniki
stëcznika stëcznika
stëcznik stëcznik
ref: stëczniczi pred: stëczniki
ref: strzodë pred: strzody
ref: strzodóm pred: strzodam
strzodo strzodo
ref: strzodama pred: strzodami
ref: strzodze pred: strzodzie
ref: strzodze pred: strzodzie
ref: strzodë pred: strzody
strzodach strzodach
ref: strzodów pred: strzodow
ref: strzodã pred: strzodą
ref: strzodë pred: strzody
ref: strzodã pred: strzodę
strzoda strzoda
ref: strzodë pred: strzody
ref: maje pred: môje
ref: majom pred: môjam
ref: maju pred: môju
ref: majima pred: môjami
ref: maju pred: môju
ref: majowi pred: môjoju
ref: maja pred: môja
ref: majach pred: môjach
ref: majów pred: môjow
ref: majã pred: môjom
ref: maje pred: môje
môj môj
môj môj
ref: maje pred: môje
ref: strumianniczi pred: strumianniki
ref: strumiannikòm pred: strumiannikam
ref: strumiannikù pred: strumianniku
ref: strumiannikama pred: strumiannikami
ref: strumiannikù pred: strumianniku
ref: strumiannikòwi pred: strumiannikoju
strumiannika strumiannika
strumiannikach strumiannikach
ref: strumianników pred: strumiannikow
ref: strumiannikã pred: strumiannikom
ref: strumianniczi pred: strumianniki
ref: strumiannik pred: strumiannika
strumiannik strumiannik
ref: strumianniczi pred: strumiannicy
ref: tidzénie pred: tidzéni
ref: tidzénióm pred: tidzénjam
ref: tidzéniu pred: tidzéni
ref: tidzénama pred: tidzénjami
ref: tidzéniu pred: tidzenju
ref: tidzéniowi pred: tidzénjoju
tidzénia tidzénia
ref: tidzénach pred: tidzénjach
ref: tidzéniów pred: tidzenjow
ref: tidzénã pred: tidzénjom
ref: tidzénie pred: tidzéni
ref: tidzéń pred: tidzéni
tidzéń tidzéń
tidzénie tidzénie
ref: czwôrtczi pred: czwôrtki
ref: czwôrtkóm pred: czwôrtkam
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkama pred: czwôrtkami
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkòwi pred: czwôrtkoju

ref: czwôrtkù pred: czwôrtka
czwôrtkach czwôrtkach
ref: czwôrtków pred: czwôrtkow
ref: czwôrtkã pred: czwôrtkom
ref: czwôrtczi pred: czwôrtki
ref: czwôrtk pred: czwôrtka
czwôrtk czwôrtk
ref: czwôrtczi pred: czwôrtki
ref: kòtë pred: kòty
ref: kòtom pred: kòtam
ref: kòce pred: kòto
ref: kòtama pred: kòtami
ref: kòce pred: kòtje
ref: kòtowi pred: kòtoju
ref: kòtu pred: kòtoju
kòta kòta
kòtach kòtach
ref: kòtów pred: kòtow
ref: kòtã pred: kòtom
ref: kòtë pred: kòty
ref: kòta pred: kòt
kòt kòt
ref: kòtë pred: kòty
ref: gromiczniczi pred: gromiczniki
ref: gromicznikòm pred: gromicznikom
ref: gromicznikù pred: gromiczniku
ref: gromicznikama pred: gromicznikami
ref: gromicznikù pred: gromiczniku
ref: gromicznikòwi pred: gromicznikowi
gromicznika gromicznika
gromicznikach gromicznikach
gromiczników gromiczników
ref: gromicznikã pred: gromicznikiem
ref: gromiczniczi pred: gromiczniki
gromicznika gromicznika
gromicznik gromicznik
ref: gromiczniczi pred: gromicznicy
rodzôcze rodzôcze
ref: rodzôczom pred: rodzôczam
rodzôczu rodzôczu
ref: rodzôczama pred: rodzôczami
rodzôczu rodzôczu
ref: rodzôczowi pred: rodzôczoju
rodzôcza rodzôcza
rodzôczach rodzôczach
ref: rodzôczów pred: rodzôczy
ref: rodzôczã pred: rodzôczem
rodzôcze rodzôcze
ref: rodzôcza pred: rodzôcz
rodzôcz rodzôcz
rodzôcze rodzôcze
niedzele niedzele
ref: niedzelóm pred: niedzelam
niedzelo niedzelo
ref: niedzelama pred: niedzelami
ref: niedzeli pred: niedzele
niedzeli niedzeli
niedzeli niedzeli
niedzelach niedzelach
ref: niedzelów pred: niedzel
ref: niedzelã pred: niedzelą
niedzele niedzele
ref: niedzelã pred: niedzelę
niedzela niedzela
niedzele niedzele
ref: gòdniczi pred: gòdniki
ref: gòdnikòm pred: gòdnikam
ref: gòdnikù pred: gòdniku
ref: gòdnikama pred: gòdnikami
ref: gòdnikù pred: gòdniku
ref: gòdnikòwi pred: gòdnikoju
gòdnika gòdnika
gòdnikach gòdnikach
ref: gòdników pred: gòdnikow
ref: gòdnikã pred: gòdnikom
ref: gòdniczi pred: gòdniki
gòdnika gòdnika
gòdnik gòdnik
ref: gòdniczi pred: gòdniki
ref: stolemë pred: stolemy
ref: stolemóm pred: stolemam
ref: stolem pred: stolemie
ref: stolemama pred: stolemami
ref: stolemie pred: stolemje
ref: stolemòwi pred: stolemoju
stolema stolema
stolemach stolemach
ref: stolemów pred: stolemow
ref: stolemã pred: stolemom
ref: stolemów pred: stolemy
ref: stolema pred: stolem
stolem stolem
ref: stolemë pred: stolemy
0.2475442043222004
livles/slavic-distant-word-or-family
test file:  ../preprocessing/preprocessing_to_json/data/dsb-lang-word_tst.json
plějachmej plějachmej
plějachmy plějachmy
plějachu plějachu
plějašo plějašo
plějaštej plějaštej
plějomy plějomy
plějotej plějotej
plějo plějo
ref: plějśo pred: plějtej
plějtej plějtej
cujachu cujachu
cujach cujach
cujašćo cujašćo
cujaštej cujaštej
cujaštej cujaštej
cujomej cujomej
cujośo cujośo
cujotej cujotej
cujo cujo
cujśo cujśo
cujtej cujtej
cuju cuju
gibanjami gibanjami
gibanja gibanja
gibanja gibanja
ref: gibanjeju pred: gibanju
gibanje gibanje
gibanje gibanje
gibanjoma gibanjoma
gibanjoma gibanjoma
gibanjow gibanjow
gibanju gibanju
śańka śańka
śańke śańke
śańkego śańkego
śańkej śańkej
śańkej śańkej
śańkeju śańkeju
śańkemu śańkemu
śańki śańki
śańkich śańkich
śańkich śańkich
śańkima śańkima
śańkima śańkima
śańkim śańkim
casach casach
casa casa
casa casa
casa casa
cas cas
casoma casoma
casoma casoma
casoma casoma
casom casom
śiche śiche
śiche śiche
śichego śichego
śichej śichej
śichej śichej
śicheje śicheje
śicheju śicheju
śichem śichem
śichem śichem
śichych śichych
śichych śichych
śichyma śichyma
śichyma śichyma
śichym śichym
śichymi śichymi
gjardła gjardła
gjardła gjardła
gjardle gjardle
gjardłoju gjardłoju
gjardłom gjardłom
gjardło gjardło
gjardłow gjardłow
gjardłowu gjardłowu
bólechmej bólechmej
bólechu bólechu
ref: bólech pred: bólach
ref: bólešo pred: bólašo
ref: bóleštej pred: bólaštej
ref: bólimej pred: bólemej
bóliśo bóliśo
bólitej bólitej
ból ból
kśiwa kśiwa
kśiwe kśiwe
kśiwe kśiwe
kśiwego kśiwego
kśiwego kśiwego
kśiwej kśiwej
kśiwej kśiwej
kśiweje kśiweje
kśiweju kśiweju
kśiweju kśiweju
kśiweju kśiweju
kśiwem kśiwem
kśiwemu kśiwemu
kśiwemu kśiwemu
kśiwu kśiwu
kśiwych kśiwych
kśiwych kśiwych
kśiwyma kśiwyma
kśiwymi kśiwymi
sykorce sykorce
sykorkoma sykorkoma
sykorkowu sykorkowu
sykorku sykorku
kawce kawce
kawce kawce
kawce kawce
kawka kawka
kawki kawki
kawkoma kawkoma
kawkoma kawkoma
kawkoma kawkoma
kawku kawku
bronami bronami
bronje bronje
bronje bronje
bronje bronje
bronoma bronoma
bronow bronow
bronu bronu
wos wos
gusach gusach
gusami gusami
gusam gusam
gus gus
gusoma gusoma
ref: gusy pred: gusa
ref: gusy pred: gusoju
ref: gusy pred: gusje
ref: gusy pred: gusa
gusy gusy
wodce wodce
ref: bydleni pred: bydlenja
bydlenjami bydlenjami
bydlenja bydlenja
ref: bydlenjeju pred: bydlenju
bydlenje bydlenje
bydlenjoma bydlenjoma
bydlenjoma bydlenjoma
bydlenjow bydlenjow
bydlenjowu bydlenjowu
gotoweju gotoweju
bobrach bobrach
bobram bobram
bobra bobra
bobr bobr
bobroma bobroma
bobroma bobroma
bobrom bobrom
bobrowu bobrowu
bobry bobry
bobry bobry
kupadłami kupadłami
kupadłam kupadłam
kupadła kupadła
kupadła kupadła
kupadła kupadła
kupadłoma kupadłoma
kupadłoma kupadłoma
kupadłom kupadłom
kupadło kupadło
kupadło kupadło
kupadłow kupadłow
kupadłowu kupadłowu
ref: mechu pred: mchu
módrych módrych
ježach ježach
ježami ježami
ježam ježam
ref: ježa pred: jež
ježa ježa
ježa ježa
ježoju ježoju
ježoma ježoma
ježoma ježoma
ježom ježom
ježu ježu
mjodach mjodach
mjoda mjoda
mjod mjod
mjodoma mjodoma
mjodowu mjodowu
mjody mjody
elektrikarjami elektrikarjami
elektrikarja elektrikarja
elektrikarje elektrikarje
elektrikarje elektrikarje
elektrikarjowu elektrikarjowu
elektrikarjowu elektrikarjowu
ref: elektrikaŕ pred: elektrikarj
lubowachmy lubowachmy
lubowašo lubowašo
lubujomy lubujomy
lubujośo lubujośo
lubujoš lubujoš
lubujotej lubujotej
lubujo lubujo
lubujśo lubujśo
lubuju lubuju
syte syte
sytego sytego
sytego sytego
sytej sytej
sytej sytej
sytej sytej
syteju syteju
syteju syteju
sytem sytem
sytem sytem
sytemu sytemu
syty syty
sytych sytych
sytych sytych
sytyma sytyma
sytyma sytyma
sytymi sytymi
ref: kazni pred: kaznja
ref: kazni pred: kaznje
ref: kazni pred: kaznja
kaznjow kaznjow
kazń kazń
kazń kazń
chorej chorej
minutce minutce
minutce minutce
minutkach minutkach
minutkami minutkami
minutki minutki
minutki minutki
ref: minutkow pred: minutek
minutkowu minutkowu
minutku minutku
łonami łonami
łona łona
łonje łonje
łonje łonje
łonje łonje
łonoma łonoma
łonom łonom
łono łono
powrjozach powrjozach
powrjozami powrjozami
powrjoza powrjoza
powrjoza powrjoza
ref: powrjoze pred: powrjozy
powrjoz powrjoz
powrjoz powrjoz
powrjozoju powrjozoju
powrjozoma powrjozoma
powrjozoma powrjozoma
powrjozoma powrjozoma
powrjozom powrjozom
powrjozow powrjozow
powrjozu powrjozu
morjow morjow
kócka kócka
pólackam pólackam
syre syre
syre syre
syrego syrego
syrego syrego
syrej syrej
syrej syrej
syrej syrej
syreju syreju
syrem syrem
syru syru
syry syry
syrych syrych
syrych syrych
syryma syryma
syryma syryma
syryma syryma
syrymi syrymi
crjowach crjowach
crjowam crjowam
crjowa crjowa
crjowa crjowa
crjowje crjowje
crjowoma crjowoma
crjowom crjowom
crjowo crjowo
crjowowu crjowowu
wósy wósy
wusmjerśowachu wusmjerśowachu
wusmjerśowašćo wusmjerśowašćo
wusmjerśowašo wusmjerśowašo
wusmjerśowašo wusmjerśowašo
wusmjerśowaštej wusmjerśowaštej
wusmjerśowaštej wusmjerśowaštej
wusmjerśujomej wusmjerśujomej
wusmjerśujoš wusmjerśujoš
wusmjerśujtej wusmjerśujtej
wusmjerśuju wusmjerśuju
znamjenja znamjenja
znamjenjoma znamjenjoma
znamjenjow znamjenjow
znamjenjowu znamjenjowu
znamjenju znamjenju
wósobach wósobach
wósobam wósobam
wósoba wósoba
wósobje wósobje
wósobje wósobje
wósoboma wósoboma
wósobowu wósobowu
wósobu wósobu
wósoby wósoby
złote złote
złote złote
złotego złotego
złotego złotego
złotej złotej
złotej złotej
złoteje złoteje
złoteju złoteju
złoteju złoteju
złotemu złotemu
złoty złoty
złotyma złotyma
złotyma złotyma
złotym złotym
złotym złotym
módryma módryma
kózy kózy
garbami garbami
garbam garbam
garba garba
garbje garbje
garbje garbje
garbje garbje
garboma garboma
garboma garboma
garby garby
poloma poloma
módremu módremu
źaržachmej źaržachmej
źaržach źaržach
źaržaštej źaržaštej
źaržaštej źaržaštej
źarž źarž
ref: źaržym pred: źaržu
źaržymy źaržymy
źaržyśo źaržyśo

ref: źaržytej pred: źaržatej
źaržytej źaržytej
ref: jsach pred: wjasach
ref: jsoma pred: wjasoma
ref: jsoma pred: wjasoma
ref: jsu pred: wjasom
ref: jsy pred: wjasoju
ref: jsy pred: wjasje
ref: jsy pred: wjasy
woda woda
molow molow
wugorjach wugorjach
wugorja wugorja
wugorje wugorje
wugorje wugorje
wugorjoma wugorjoma
wugorjoma wugorjoma
ref: wugorjowu pred: wugorja
wugorjowu wugorjowu
wugoŕ wugoŕ
ref: njebi pred: njebja
njebjach njebjach
njebja njebja
njebja njebja
njebja njebja
njebjoju njebjoju
njebjoma njebjoma
njebjoma njebjoma
njebjo njebjo
njebjowu njebjowu
njebju njebju
fotografowachmy fotografowachmy
fotografowachu fotografowachu
fotografowach fotografowach
fotografowašo fotografowašo
fotografujomej fotografujomej
fotografujoš fotografujoš
fotografujotej fotografujotej
fotografujo fotografujo
fotografujtej fotografujtej
lažčejše lažčejše
lažčejšej lažčejšej
lažčejšej lažčejšej
lažčejšeje lažčejšeje
lažčejšeju lažčejšeju
ref: lažčejšeju pred: lažčejšou
lažčejšem lažčejšem
lažčejšem lažčejšem
lažčejšemu lažčejšemu
lažčejšy lažčejšy
lažčejšy lažčejšy
lažčejšych lažčejšych
lažčejšyma lažčejšyma
lažčejšym lažčejšym
lažčejšym lažčejšym
lažčejšymi lažčejšymi
běłe běłe
běłe běłe
běłe běłe
běłej běłej
běłej běłej
běłeje běłeje
běłeju běłeju
běłemu běłemu
běły běły
běłych běłych
běłych běłych
běłyma běłyma
běłyma běłyma
běłym běłym
běłym běłym
pśigótowachmy pśigótowachmy
pśigótowach pśigótowach
pśigótowašćo pśigótowašćo
ref: pśigótowa pred: pśigótowašo
pśigótujomy pśigótujomy
pśigótujotej pśigótujotej
pśigótujotej pśigótujotej
pśigótujśo pśigótujśo
pśigótujtej pśigótujtej
pśigótuju pśigótuju
radija radija
ref: radiji pred: radijowu
radijoju radijoju
radijoma radijoma
radijo radijo
radijow radijow
wucabnicach wucabnicach
ref: wucabnice pred: wucabnicy
wucabnice wucabnice
wucabnicow wucabnicow
wucabnicowu wucabnicowu
wucabnicu wucabnicu
wucabnicy wucabnicy
wucabnicy wucabnicy
mačce mačce
mačce mačce
mačce mačce
mačkach mačkach
mačkami mačkami
mački mački
mački mački
mačkoma mačkoma
ref: mačkow pred: maček
mačkowu mačkowu
mačku mačku
kocce kocce
modrym modrym
žyjachmej žyjachmej
žyjach žyjach
žyjašo žyjašo
žyjaštej žyjaštej
žyjomej žyjomej
žyjomy žyjomy
žyjośo žyjośo
žyjo žyjo
žyju žyju
nockach nockach
nocki nocki
nocki nocki
nockoma nockoma
nockowu nockowu
choryma choryma
nožach nožach
nožam nožam
ref: noža pred: nožy
nože nože
nož nož
ref: nožoju pred: noži
ref: nožom pred: nožu
nožowu nožowu
ref: nožu pred: noži
ref: drozna pred: drozn
drozna drozna
droznje droznje
droznoju droznoju
droznoma droznoma
droznom droznom
droznowu droznowu
drozny drozny
modrych modrych
kózow kózow
babce babce
babce babce
babkam babkam
babki babki
babkoma babkoma
ref: babkow pred: babek
babkowu babkowu
babku babku
wikow wikow
studentach studentach
studentami studentami
studenta studenta
studentoma studentoma
studentoma studentoma
studentom studentom
studentow studentow
studentowu studentowu
studentowu studentowu
zegera zegera
zegera zegera
zegerje zegerje
zegeroju zegeroju
zegeroma zegeroma
zegeroma zegeroma
zegerowu zegerowu
módrej módrej
korespondentce korespondentce
korespondentce korespondentce
korespondentkami korespondentkami
korespondentkam korespondentkam
korespondentki korespondentki
korespondentki korespondentki
ref: korespondentkow pred: korespondentek
korespondentkowu korespondentkowu
korespondentku korespondentku
modrego modrego
mólami mólami
póloma póloma
bósučka bósučka
bósučke bósučke
bósučke bósučke
bósučkego bósučkego
bósučkego bósučkego
bósučkej bósučkej
bósučkeju bósučkeju
bósučkeju bósučkeju
bósučki bósučki
bósučkich bósučkich
bósučkima bósučkima
bósučkima bósučkima
bósučkim bósučkim
bósučkimi bósučkimi
bósučku bósučku
modrego modrego
zła zła
złe złe
złe złe
złego złego
złego złego
złeju złeju
złem złem
złemu złemu
złu złu
zły zły
zły zły
złych złych
złyma złyma
złymi złymi
rěce rěce
rěce rěce
rěkach rěkach
rěkam rěkam
rěki rěki
rěkoma rěkoma
rěkow rěkow
rěkowu rěkowu
rěku rěku
rěku rěku
chylachmej chylachmej
chylaštej chylaštej
chylaštej chylaštej
chylimej chylimej
chylim chylim
chyliśo chyliśo
ref: chylśo pred: chyliśo
chyltej chyltej
reagěrowachmy reagěrowachmy
reagěrowašćo reagěrowašćo
reagěrowašo reagěrowašo
reagěrowašo reagěrowašo
reagěrujotej reagěrujotej
reagěrujo reagěrujo
reagěrujśo reagěrujśo
reagěrujtej reagěrujtej
wosoma wosoma
paśpulach paśpulach
paśpulami paśpulami
paśpule paśpule
paśpule paśpule
ref: paśpuli pred: paśpulje
ref: paśpuli pred: paśpulje
paśpuloma paśpuloma
paśpuloma paśpuloma
paśpulowu paśpulowu
paśpulu paśpulu
paśpulu paśpulu
mólami mólami
ref: pěśe pred: pěźe
pětach pětach
pětam pětam
pěta pěta
pětoma pětoma
pětoma pětoma
pětoma pětoma
pětu pětu
pětu pětu
gotowy gotowy
serbiske serbiske
serbiske serbiske
serbiskego serbiskego
serbiskego serbiskego
serbiskej serbiskej
serbiskej serbiskej
serbiskeje serbiskeje
serbiskeju serbiskeju
serbiskem serbiskem
serbiskem serbiskem
serbiski serbiski
serbiskima serbiskima
serbiskim serbiskim
serbiskim serbiskim
rybami rybami
rybam rybam
ryba ryba
rybje rybje
rybje rybje
rybje rybje
ryboma ryboma
ryboma ryboma
rybu rybu
ryby ryby
ryby ryby
bananach bananach
bananami bananami
banana banana
bananje bananje
bananowu bananowu
bananu bananu
bananu bananu
banany banany
banany banany
konje konje
ref: wjedu pred: wjasą
ref: wjeźćo pred: wjaście
ref: wjeźechmej pred: wjasćechmej
ref: wjeźech pred: wjasęch
ref: wjeźešćo pred: wjasłyście
ref: wjeźešo pred: wjasło
ref: wjeźeštej pred: wjasłaštej
ref: wjeźeštej pred: wjasłaštej
ref: wjeźomej pred: wjasmej
ref: wjeźomy pred: wjasmy
ref: wjeźoš pred: wjasiš
ref: wjeźotej pred: wjastej
ref: wjeźotej pred: wjastej
ref: wjeź pred: wjas
bokach bokach
bokami bokami
boka boka
boki boki
bok bok
bokoma bokoma
bokoma bokoma
bokom bokom
boku boku
pólacki pólacki
měsćańske měsćańske
měsćańske měsćańske
měsćańske měsćańske
měsćańskego měsćańskego
měsćańskej měsćańskej
měsćańskej měsćańskej
měsćańskeju měsćańskeju
měsćańskem měsćańskem
měsćańskem měsćańskem
měsćańskemu měsćańskemu
měsćański měsćański
měsćański měsćański
měsćańskich měsćańskich
měsćańskima měsćańskima
měsćańskim měsćańskim
měsćańskim měsćańskim
měsćańskimi měsćańskimi
ref: měsćańsku pred: měsćańską
spańska spańska
spańske spańske
spańskego spańskego
spańskego spańskego
spańskej spańskej
spańskej spańskej
spańskeju spańskeju
spańskeju spańskeju
spańskem spańskem
spańskemu spańskemu
spański spański
spańskich spańskich
spańskima spańskima
ref: spańsku pred: spańską
póla póla
měsach měsach
měsom měsom
měso měso
měso měso
měsow měsow
ref: měsy pred: měsa
brodach brodach
broda broda
brod brod
brody brody
brody brody
alofonach alofonach
alofonam alofonam
alofona alofona
alofonje alofonje
alofonoju alofonoju
alofonoma alofonoma
alofonoma alofonoma
alofonow alofonow
alofonowu alofonowu
alofony alofony
alofony alofony
strowimej strowimej
strowim strowim
strowimy strowimy
strowitej strowitej
strowjašćo strowjašćo
strowjašo strowjašo
strowjašo strowjašo
ref: strowje pred: strowiju
strowśo strowśo
strowtej strowtej
strow strow
kótami kótami
tśmjenjam tśmjenjam
tśmjenja tśmjenja
tśmjenja tśmjenja
tśmjenje tśmjenje
tśmjenjoma tśmjenjoma
tśmjenjoma tśmjenjoma
tśmjenjom tśmjenjom
tśmjenjow tśmjenjow
tśmjenju tśmjenju
tśmjeń tśmjeń
domka domka
domka domka
domki domki
ref: domk pred: domka
domk domk
domkoma domkoma
domkoma domkoma
domku domku
kwasam kwasam
kwasa kwasa
ref: kwase pred: kwasy
kwas kwas
kwasoju kwasoju
kwasoma kwasoma
kwasoma kwasoma
kwasowu kwasowu
zelena zelena
zelene zelene
zelene zelene
zelene zelene
zelenego zelenego
zelenego zelenego
zelenej zelenej
zeleneje zeleneje
zeleneju zeleneju
zeleneju zeleneju
zelenem zelenem
zelenemu zelenemu
zelenych zelenych
zelenych zelenych
zelenyma zelenyma
zelenyma zelenyma
zelenyma zelenyma
zelenym zelenym
zelenymi zelenymi
sadłami sadłami
sadła sadła
ref: sadle pred: sadła
sadłoju sadłoju
sadłoma sadłoma
sadłoma sadłoma
sadło sadło
sadłow sadłow
sobośe sobośe
sobośe sobośe
sobotach sobotach
sobotam sobotam
sobota sobota
sobotoma sobotoma
sobotow sobotow
sobotowu sobotowu
sobotu sobotu
soboty soboty
soboty soboty
soboty soboty
rjobła rjobła
rjobła rjobła
rjobła rjobła
ref: rjoble pred: rjobłu
ref: rjoble pred: rjobła
rjobłoju rjobłoju
rjobłoma rjobłoma

rjobłom rjobłom
rjobłowu rjobłowu
ref: powětšach pred: pówětšach
ref: powětšami pred: pówětšami
ref: powětšam pred: pówětšam
ref: powětša pred: pówětša
ref: powětša pred: pówětša
ref: powětš pred: pówětša
ref: powětš pred: pówětš
ref: powětšoma pred: pówětšoma
ref: powětšoma pred: pówětšoma
ref: powětšoma pred: pówětšoma
ref: powětšom pred: pówětšom
ref: powětšow pred: pówětšow
ref: powětšy pred: pówětšy
mjeńša mjeńša
mjeńše mjeńše
mjeńše mjeńše
mjeńše mjeńše
mjeńšego mjeńšego
mjeńšego mjeńšego
mjeńšego mjeńšego
mjeńšej mjeńšej
mjeńšeju mjeńšeju
mjeńšemu mjeńšemu
mjeńšemu mjeńšemu
mjeńšyma mjeńšyma
mjeńšymi mjeńšymi
wjapśam wjapśam
wjapśa wjapśa
wjapśe wjapśe
wjapś wjapś
wjapśoma wjapśoma
wjapśom wjapśom
wjapśu wjapśu
rjemjenjami rjemjenjami
rjemjenja rjemjenja
rjemjenja rjemjenja
rjemjenje rjemjenje
rjemjenjoma rjemjenjoma
rjemjenjow rjemjenjow
cysta cysta
cyste cyste
cyste cyste
cystego cystego
cystego cystego
cystej cystej
cystej cystej
cysteju cysteju
cysteju cysteju
cystem cystem
cystemu cystemu
cystych cystych
cystym cystym
cystym cystym
cystymi cystymi
pólam pólam
kónjami kónjami
grodami grodami
groda groda
grodoma grodoma
grodom grodom
grodow grodow
grodowu grodowu
grody grody
grody grody
ref: groźe pred: grodje
granicami granicami
granica granica
ref: granice pred: granicy
granice granice
granicoma granicoma
granicoma granicoma
granicow granicow
granicowu granicowu
granicu granicu
ref: smjejachmej pred: smjachmej
ref: smjejachu pred: smjachu
ref: smjejach pred: smjach
ref: smjejašćo pred: smjašćo
ref: smjejašo pred: smjašo
ref: smjejaštej pred: smjaštej
ref: smjejaštej pred: smjaštej
ref: smjejomy pred: smjamy
ref: smjejotej pred: smjatej
ref: smjejtej pred: smjajtej
lěwe lěwe
lěwe lěwe
lěwego lěwego
lěwej lěwej
lěwej lěwej
lěwej lěwej
lěwej lěwej
lěweju lěweju
lěweju lěweju
lěwemu lěwemu
ref: lěwi pred: lěwy
ref: lěwima pred: lěwyma
ref: lěwim pred: lěwym
ref: lěwim pred: lěwym
ref: lěwimi pred: lěwymi
ref: jabłuce pred: jabłuka
jabłukach jabłukach
jabłukam jabłukam
jabłuka jabłuka
jabłukoju jabłukoju
jabłukoma jabłukoma
jabłukoma jabłukoma
jabłukom jabłukom
jabłuko jabłuko
jabłukow jabłukow
jabłukowu jabłukowu
ref: kose pred: kosy
wałtoram wałtoram
wałtora wałtora
wałtorje wałtorje
wałtorje wałtorje
wałtoroma wałtoroma
wałtorowu wałtorowu
wałtoru wałtoru
wałtory wałtory
wałtory wałtory
wóskoma wóskoma
płośe płośe
płotach płotach
płotami płotami
płotam płotam
płota płota
płota płota
płot płot
płotoma płotoma
płotoma płotoma
płotom płotom
płoty płoty
módry módry
ref: maśeri pred: maśe
ref: maśerjami pred: maśami
ref: maśerjam pred: maśam
ref: maśerje pred: maśa
ref: maśerjoma pred: maśoma
ref: maśerjoma pred: maśoma
ref: maśerjow pred: maśow
ref: maśerju pred: maśom
spórachmej spórachmej
spórach spórach
spórajśo spórajśo
spóraju spóraju
spóraj spóraj
spóram spóram
spóramy spóramy
spórašćo spórašćo
spóraśo spóraśo
spóratej spóratej
spóratej spóratej
ref: spóra pred: spórašo
ref: spóra pred: spórašo
słomach słomach
słomje słomje
słomje słomje
słomow słomow
słomowu słomowu
słomu słomu
słomy słomy
słomy słomy
wójcach wójcach
wójce wójce
ref: wójce pred: wójcy
wójcowu wójcowu
ref: wójcy pred: wójce
ref: wójcy pred: wójce
serpa serpa
serp serp
serpoma serpoma
serpoma serpoma
serpoma serpoma
serpy serpy
serpy serpy
ref: njasešo pred: njasło
ref: njaseštej pred: njasćeštej
ref: njasomej pred: njasmej
ref: njaso pred: njasi
njastej njastej
njas njas
damastach damastach
damastami damastami
ref: damasta pred: damastowu
damasta damasta
damasta damasta
damast damast
damastoma damastoma
damastow damastow
damasty damasty
damasty damasty
modrej modrej
0.88
livles/slavic-distant-word-or-family
test file:  ../preprocessing/preprocessing_to_json/data/slk-lang-word_tst.json
ref: ulievárni pred: ulieváreni
ref: ulievárne pred: ulievárene
obsaditeľného obsaditeľného
najobsaditeľnejšia najobsaditeľnejšia
najobsaditeľnejším najobsaditeľnejším
obsaditeľný obsaditeľný
obsaditeľné obsaditeľné
obsaditeľné obsaditeľné
obsaditeľnejšiemu obsaditeľnejšiemu
najobsaditeľnejšiemu najobsaditeľnejšiemu
obsaditeľným obsaditeľným
najobsaditeľnejšími najobsaditeľnejšími
obsaditeľnejšími obsaditeľnejšími
obsaditeľnejšími obsaditeľnejšími
najobsaditeľnejšími najobsaditeľnejšími
obsaditeľnejšou obsaditeľnejšou
obsaditeľní obsaditeľní
najobsaditeľnejších najobsaditeľnejších
najobsaditeľnejších najobsaditeľnejších
obsaditeľnejších obsaditeľnejších
najobsaditeľnejších najobsaditeľnejších
najobsaditeľnejších najobsaditeľnejších
najobsaditeľnejších najobsaditeľnejších
najobsaditeľnejší najobsaditeľnejší
obsaditeľnejší obsaditeľnejší
obsaditeľnejší obsaditeľnejší
najobsaditeľnejší najobsaditeľnejší
najobsaditeľnejší najobsaditeľnejší
obsaditeľnejšie obsaditeľnejšie
najobsaditeľnejšie najobsaditeľnejšie
najobsaditeľnejšie najobsaditeľnejšie
obsaditeľnejšie obsaditeľnejšie
najobsaditeľnejšie najobsaditeľnejšie
obsaditeľnejšie obsaditeľnejšie
obsaditeľnejšie obsaditeľnejšie
najobsaditeľnejšie najobsaditeľnejšie
obsaditeľnejšie obsaditeľnejšie
obsaditeľných obsaditeľných
obsaditeľných obsaditeľných
obsaditeľných obsaditeľných
obsaditeľných obsaditeľných
obsaditeľných obsaditeľných
obsaditeľnejšej obsaditeľnejšej
najobsaditeľnejšieho najobsaditeľnejšieho
najobsaditeľnejšieho najobsaditeľnejšieho
obsaditeľnejšieho obsaditeľnejšieho
najobsaditeľnejšieho najobsaditeľnejšieho
obsaditeľnému obsaditeľnému
najneuzátvorkovanejšie najneuzátvorkovanejšie
prebrusujúceho prebrusujúceho
prebrusujúce prebrusujúce
prebrusujúce prebrusujúce
prebrusujúce prebrusujúce
prebrusujúce prebrusujúce
prebrusujúcim prebrusujúcim
prebrusujúcim prebrusujúcim
prebrusujúca prebrusujúca
prebrusujúca prebrusujúca
prebrusujúcej prebrusujúcej
prebrusujúci prebrusujúci
prebrusujúci prebrusujúci
prebrusujúcich prebrusujúcich
prebrusujúcich prebrusujúcich
prebrusujúcemu prebrusujúcemu
prebrusujúcemu prebrusujúcemu
ref: vnukateľnejšie pred: nevnukateľnejšie
ref: najodvodeninovejšie pred: najneodvodeninovejšie
karhacia karhacia
karhaciu karhaciu
karhacích karhacích
karhacích karhacích
karhacích karhacích
karhacích karhacích
karhacích karhacích
karhacieho karhacieho
karhacieho karhacieho
karhacej karhacej
karhacie karhacie
karhacie karhacie
karhacie karhacie
karhaciemu karhaciemu
karhacími karhacími
karhacími karhacími
karhacím karhacím
karhacím karhacím
pribúdavanú pribúdavanú
pribúdavaš pribúdavaš
nepribúdavané nepribúdavané
nepribúdavané nepribúdavané
pribúdavané pribúdavané
nebudeš pribúdavať nebudeš pribúdavať
bude pribúdavať bude pribúdavať
nebude pribúdavať nebude pribúdavať
nebudeme pribúdavať nebudeme pribúdavať
nebudete pribúdavať nebudete pribúdavať
budú pribúdavať budú pribúdavať
nepribúdavaš nepribúdavaš
nepribúdavate nepribúdavate
neboli by pribúdavali neboli by pribúdavali
neboli by sme pribúdavali neboli by sme pribúdavali
nepribúdavali ste nepribúdavali ste
nepribúdavali by sme nepribúdavali by sme
nepribúdavali by ste nepribúdavali by ste
nepribúdavali sme nepribúdavali sme
nepribúdavali ste nepribúdavali ste
nepribúdavali by ste nepribúdavali by ste
neboli by pribúdavali neboli by pribúdavali
neboli by sme pribúdavali neboli by sme pribúdavali
nepribúdavali by sme nepribúdavali by sme
neboli by sme pribúdavali neboli by sme pribúdavali
nepribúdavali ste nepribúdavali ste
nepribúdavali sme nepribúdavali sme
nepribúdavali by sme nepribúdavali by sme
nepribúdavali ste nepribúdavali ste
nepribúdavali by ste nepribúdavali by ste
neboli by pribúdavali neboli by pribúdavali
neboli by ste pribúdavali neboli by ste pribúdavali
nepribúdavali by nepribúdavali by
neboli by sme pribúdavali neboli by sme pribúdavali
pribúdaval si pribúdaval si
bol by pribúdaval bol by pribúdaval
pribúdaval by pribúdaval pribúdaval by pribúdaval
pribúdaval by som pribúdaval pribúdaval by som pribúdaval
bol by pribúdaval bol by pribúdaval
nepribúdavať nepribúdavať
pribúdavaní pribúdavaní
pribúdavaní pribúdavaní
pribúdavané pribúdavané
ref: pribúdavalo by som pribúdaval pred: pribúdavalo by som pribúdavalo
ref: pribúdavalo by si pribúdaval pred: pribúdavalo by si pribúdavalo
bolo by pribúdavalo bolo by pribúdavalo
pribúdavala som pribúdavala som
pribúdavala si pribúdavala si
ref: pribúdavala by pribúdavalo pred: pribúdavala by pribúdavala

ref: pribúdavala by si pribúdavalo pred: pribúdavala by si pribúdavala
bola by pribúdavala bola by pribúdavala
pribúdavala pribúdavala
pribúdavala by pribúdavala pribúdavala by pribúdavala
bola by som pribúdavala bola by som pribúdavala
nepribúdava nepribúdava
nepribúdava nepribúdava
pribúdavali sme pribúdavali sme
pribúdavali by ste pribúdavali by ste
pribúdavali pribúdavali
pribúdavali pribúdavali
pribúdavali sme pribúdavali sme
boli by pribúdavali boli by pribúdavali
boli by ste pribúdavali boli by ste pribúdavali
pribúdavali sme pribúdavali sme
pribúdavali pribúdavali
pribúdavali sme pribúdavali sme
pribúdavali pribúdavali
pribúdavali by pribúdavali by
boli by pribúdavali boli by pribúdavali
pribúdavali ste pribúdavali ste
pribúdavali by sme pribúdavali by sme
boli by pribúdavali boli by pribúdavali
pribúdavali ste pribúdavali ste
pribúdavali by sme pribúdavali by sme
boli by pribúdavali boli by pribúdavali
pribúdavate pribúdavate
nepribúdavané nepribúdavané
nepribúdavalo si nepribúdavalo si
nepribúdavalo by pribúdavalo nepribúdavalo by pribúdavalo
nepribúdavalo by som pribúdavalo nepribúdavalo by som pribúdavalo
nepribúdavalo by si pribúdavalo nepribúdavalo by si pribúdavalo
nepribúdavaný nepribúdavaný
pribúdavaný pribúdavaný
pribúdavaný pribúdavaný
nepribúdavame nepribúdavame
pribúdavam pribúdavam
pribúdavané pribúdavané
pribúdavaná pribúdavaná
ref: nepribúdaval by som pribúdavalo pred: nepribúdaval by som pribúdaval
ref: nepribúdaval by si pribúdavalo pred: nepribúdaval by si pribúdaval
nepribúdaval by som pribúdaval nepribúdaval by som pribúdaval
nepribúdavala si nepribúdavala si
ref: nepribúdavala by si pribúdaval pred: nepribúdavala by si pribúdavala
nepribúdavala som nepribúdavala som
pribúdavajú pribúdavajú
dvojčiarkovaností dvojčiarkovaností
dvojčiarkovanosti dvojčiarkovanosti
dvojčiarkovanosti dvojčiarkovanosti
dvojčiarkovanostiam dvojčiarkovanostiam
vymodelovávaní vymodelovávaní
vymodelovávania vymodelovávania
vymodelovávania vymodelovávania
vymodelovávaniach vymodelovávaniach
vymodelovávaniami vymodelovávaniami
vymodelovávanie vymodelovávanie
ref: pokutene pred: nepokutene
ref: pokutenejšie pred: nepokutenejšie
neabstinúvanejšie neabstinúvanejšie
ref: zmaškrtenejšie pred: nezmaškrtenejšie
nezmaškrtenejšie nezmaškrtenejšie
primiešavavajúceho primiešavavajúceho
primiešavavajúce primiešavavajúce
primiešavavajúce primiešavavajúce
primiešavavajúce primiešavavajúce
primiešavavajúcimi primiešavavajúcimi
primiešavavajúcimi primiešavavajúcimi
primiešavavajúcim primiešavavajúcim
primiešavavajúcim primiešavavajúcim
primiešavavajúcu primiešavavajúcu
primiešavavajúca primiešavavajúca
primiešavavajúcej primiešavavajúcej
primiešavavajúcej primiešavavajúcej
primiešavavajúci primiešavavajúci
primiešavavajúci primiešavavajúci
primiešavavajúci primiešavavajúci
primiešavavajúcich primiešavavajúcich
primiešavavajúcemu primiešavavajúcemu
odstránkúvania odstránkúvania
odstránkúvania odstránkúvania
odstránkúvaniu odstránkúvaniu
ref: nepodliehane pred: podliehane
ref: podliehanejšie pred: nepodliehanejšie
najnepodliehanejšie najnepodliehanejšie
turbovrtuľové turbovrtuľové
turbovrtuľové turbovrtuľové
turbovrtuľové turbovrtuľové
turbovrtuľové turbovrtuľové
najturbovrtuľovejšiu najturbovrtuľovejšiu
turbovrtuľovejšom turbovrtuľovejšom
najturbovrtuľovejšom najturbovrtuľovejšom
turbovrtuľovejšiemu turbovrtuľovejšiemu
najturbovrtuľovejšiemu najturbovrtuľovejšiemu
turbovrtuľovejšiemu turbovrtuľovejšiemu
najturbovrtuľovejšiemu najturbovrtuľovejšiemu
turbovrtuľovými turbovrtuľovými
turbovrtuľového turbovrtuľového
turbovrtuľového turbovrtuľového
turbovrtuľový turbovrtuľový
turbovrtuľovejším turbovrtuľovejším
turbovrtuľovejším turbovrtuľovejším
najturbovrtuľovejším najturbovrtuľovejším
turbovrtuľovejším turbovrtuľovejším
turbovrtuľová turbovrtuľová
turbovrtuľovejší turbovrtuľovejší
turbovrtuľovejší turbovrtuľovejší
turbovrtuľovejší turbovrtuľovejší
najturbovrtuľovejších najturbovrtuľovejších
najturbovrtuľovejších najturbovrtuľovejších
najturbovrtuľovejších najturbovrtuľovejších
turbovrtuľovejších turbovrtuľovejších
najturbovrtuľovejších najturbovrtuľovejších
najturbovrtuľovejšie najturbovrtuľovejšie
turbovrtuľovejšie turbovrtuľovejšie
turbovrtuľovejšie turbovrtuľovejšie
turbovrtuľovejšie turbovrtuľovejšie
najturbovrtuľovejšie najturbovrtuľovejšie
turbovrtuľových turbovrtuľových
turbovrtuľovejšej turbovrtuľovejšej
najturbovrtuľovejšej najturbovrtuľovejšej
turbovrtuľovejšej turbovrtuľovejšej
turbovrtuľovému turbovrtuľovému
turbovrtuľovému turbovrtuľovému
turbovrtuľovejšieho turbovrtuľovejšieho
najturbovrtuľovejšieho najturbovrtuľovejšieho
turbovrtuľovým turbovrtuľovým
turbovrtuľovej turbovrtuľovej
turbovrtuľovejšou turbovrtuľovejšou
turbovrtuľovejšími turbovrtuľovejšími
najturbovrtuľovejšími najturbovrtuľovejšími
ododrené ododrené
ododrené ododrené
ododrené ododrené
ododrenejšom ododrenejšom
najododrenejšiemu najododrenejšiemu
ododrenými ododrenými
ododreného ododreného
ododreného ododreného
ododrený ododrený
ododrený ododrený
najododrenejším najododrenejším
ododrenejším ododrenejším
ododrenejším ododrenejším
najododrenejším najododrenejším
ododrenejším ododrenejším
najododrenejšia najododrenejšia
ododrenejší ododrenejší
najododrenejší najododrenejší
ododrenejší ododrenejší
najododrenejší najododrenejší
ododrenejší ododrenejší
ododrenejší ododrenejší
ododrenejší ododrenejší
ododrenejších ododrenejších
ododrenejších ododrenejších
najododrenejších najododrenejších
najododrenejšie najododrenejšie
ododrenejšie ododrenejšie
najododrenejšie najododrenejšie
najododrenejšie najododrenejšie
najododrenejšie najododrenejšie
ododrenejšie ododrenejšie
najododrenejšie najododrenejšie
ododrenejšie ododrenejšie
najododrenejšie najododrenejšie
ododrenejšie ododrenejšie
najododrenejšie najododrenejšie
ododrenejšie ododrenejšie
najododrenejšie najododrenejšie
ododrení ododrení
ododrených ododrených
ododrených ododrených
najododrenejšej najododrenejšej
najododrenejšej najododrenejšej
ododrenému ododrenému
ododrenejšieho ododrenejšieho
najododrenejšieho najododrenejšieho
ododrenejšieho ododrenejšieho
ododreným ododreným
ododreným ododreným
ododrenej ododrenej
najododrenejšími najododrenejšími
ododrenejšími ododrenejšími
najododrenejšími najododrenejšími
bankrotovacích bankrotovacích
bankrotovacích bankrotovacích
bankrotovacích bankrotovacích
bankrotovacích bankrotovacích
bankrotovacieho bankrotovacieho
bankrotovacieho bankrotovacieho
bankrotovacie bankrotovacie
bankrotovacie bankrotovacie
bankrotovacie bankrotovacie
bankrotovacie bankrotovacie
bankrotovaciemu bankrotovaciemu
bankrotovacími bankrotovacími
bankrotovacou bankrotovacou
bankrotovacím bankrotovacím
bankrotovacom bankrotovacom
bankrotovací bankrotovací
bankrotovací bankrotovací
bankrotovací bankrotovací
odkvapovú odkvapovú
odkvapové odkvapové
odkvapové odkvapové
odkvapové odkvapové
odkvapové odkvapové
odkvapové odkvapové
odkvapové odkvapové
odkvapovom odkvapovom
odkvapovom odkvapovom
najodkvapovejšiu najodkvapovejšiu
odkvapovejšom odkvapovejšom
odkvapovejšom odkvapovejšom
odkvapovejšom odkvapovejšom
odkvapovými odkvapovými
odkvapového odkvapového
odkvapového odkvapového
odkvapový odkvapový
odkvapovejším odkvapovejším
odkvapovejším odkvapovejším
odkvapovejším odkvapovejším
najodkvapovejším najodkvapovejším
najodkvapovejším najodkvapovejším
odkvapovejšia odkvapovejšia
najodkvapovejší najodkvapovejší
odkvapovejší odkvapovejší
najodkvapovejší najodkvapovejší
najodkvapovejších najodkvapovejších
odkvapovejších odkvapovejších
najodkvapovejších najodkvapovejších
odkvapovejších odkvapovejších
najodkvapovejších najodkvapovejších
najodkvapovejších najodkvapovejších
najodkvapovejších najodkvapovejších
najodkvapovejšie najodkvapovejšie
odkvapovejšie odkvapovejšie
odkvapovejšie odkvapovejšie
odkvapovejšie odkvapovejšie
najodkvapovejšie najodkvapovejšie
odkvapových odkvapových
odkvapovejšej odkvapovejšej
odkvapovejšej odkvapovejšej
najodkvapovejšej najodkvapovejšej
odkvapovému odkvapovému
najodkvapovejšieho najodkvapovejšieho
odkvapovej odkvapovej
odkvapovej odkvapovej
najodkvapovejšou najodkvapovejšou
odkvapovejšími odkvapovejšími
odkvapovejšími odkvapovejšími
odkvapovejšími odkvapovejšími
najodkvapovejšími najodkvapovejšími
štukoví štukoví
štukové štukové

štukových štukových
štukových štukových
štukových štukových
štukových štukových
štukových štukových
štukového štukového
štukovej štukovej
štukovým štukovým
štukovými štukovými
štukovými štukovými
štuková štuková
štukový štukový
nevypojovávateľne nevypojovávateľne
ref: vypojovávateľnejšie pred: nevypojovávateľnejšie
najnevypojovávateľnejšie najnevypojovávateľnejšie
diskutúvané diskutúvané
diskutúvané diskutúvané
diskutúvanom diskutúvanom
najdiskutúvanejšiu najdiskutúvanejšiu
diskutúvanejšom diskutúvanejšom
diskutúvanejšom diskutúvanejšom
diskutúvanejšiemu diskutúvanejšiemu
diskutúvanejšiemu diskutúvanejšiemu
diskutúvaného diskutúvaného
diskutúvaného diskutúvaného
diskutúvaný diskutúvaný
diskutúvanejším diskutúvanejším
najdiskutúvanejším najdiskutúvanejším
diskutúvanejšia diskutúvanejšia
najdiskutúvanejšia najdiskutúvanejšia
diskutúvaná diskutúvaná
diskutúvanejší diskutúvanejší
diskutúvanejší diskutúvanejší
najdiskutúvanejší najdiskutúvanejší
diskutúvanejších diskutúvanejších
diskutúvanejších diskutúvanejších
najdiskutúvanejších najdiskutúvanejších
diskutúvanejších diskutúvanejších
diskutúvanejších diskutúvanejších
najdiskutúvanejšie najdiskutúvanejšie
najdiskutúvanejšie najdiskutúvanejšie
najdiskutúvanejšie najdiskutúvanejšie
najdiskutúvanejšie najdiskutúvanejšie
diskutúvanejšie diskutúvanejšie
najdiskutúvanejšie najdiskutúvanejšie
diskutúvanejšie diskutúvanejšie
diskutúvaní diskutúvaní
diskutúvaných diskutúvaných
diskutúvaných diskutúvaných
diskutúvanejšieho diskutúvanejšieho
diskutúvanejšieho diskutúvanejšieho
najdiskutúvanejšieho najdiskutúvanejšieho
diskutúvaným diskutúvaným
diskutúvaným diskutúvaným
diskutúvaným diskutúvaným
diskutúvanej diskutúvanej
diskutúvanej diskutúvanej
najdiskutúvanejšou najdiskutúvanejšou
najdiskutúvanejšími najdiskutúvanejšími
diskutúvanejšími diskutúvanejšími
najdiskutúvanejšími najdiskutúvanejšími
vyčiarkovania vyčiarkovania
vyčiarkovaniach vyčiarkovaniach
vyčiarkovaniam vyčiarkovaniam
vyčiarkovania vyčiarkovania
vyčiarkovaní vyčiarkovaní
vyčiarkovanie vyčiarkovanie
vyčiarkovaní vyčiarkovaní
dodýchaní dodýchaní
dodýchania dodýchania
dodýchania dodýchania
dodýchaniach dodýchaniach
dodýchaniam dodýchaniam
ref: nevymrene pred: vymrene
nevymrenejšie nevymrenejšie
predkopírúvajúcom predkopírúvajúcom
predkopírúvajúce predkopírúvajúce
predkopírúvajúce predkopírúvajúce
predkopírúvajúcim predkopírúvajúcim
predkopírúvajúcim predkopírúvajúcim
predkopírúvajúcu predkopírúvajúcu
predkopírúvajúca predkopírúvajúca
predkopírúvajúcej predkopírúvajúcej
predkopírúvajúcej predkopírúvajúcej
predkopírúvajúci predkopírúvajúci
predkopírúvajúci predkopírúvajúci
predkopírúvajúci predkopírúvajúci
predkopírúvajúcich predkopírúvajúcich
predkopírúvajúcich predkopírúvajúcich
predkopírúvajúcich predkopírúvajúcich
predkopírúvajúcich predkopírúvajúcich
pohládzanosť pohládzanosť
pohládzanosťami pohládzanosťami
pohládzanosti pohládzanosti
pohládzanosti pohládzanosti
pohládzanostiam pohládzanostiam
rozpermutovávacia rozpermutovávacia
rozpermutovávacích rozpermutovávacích
rozpermutovávacieho rozpermutovávacieho
rozpermutovávacej rozpermutovávacej
rozpermutovávacie rozpermutovávacie
rozpermutovávacie rozpermutovávacie
rozpermutovávacie rozpermutovávacie
rozpermutovávacie rozpermutovávacie
rozpermutovávacie rozpermutovávacie
rozpermutovávacie rozpermutovávacie
rozpermutovávacím rozpermutovávacím
rozpermutovávacím rozpermutovávacím
rozpermutovávací rozpermutovávací
ref: pucúvateľne pred: nepucúvateľne
nepucúvateľne nepucúvateľne
ref: pucúvateľnejšie pred: nepucúvateľnejšie
nepucúvateľnejšie nepucúvateľnejšie
ref: debuggeru pred: debuggera
ref: debuggeru pred: debuggerovi
debuggerom debuggerom
debuggerom debuggerom
ejektory ejektory
ref: ejektormi pred: ejektorami
ejektorov ejektorov
ejektor ejektor
ref: ejektoroch pred: ejektorach
ref: ejektoru pred: ejektorovi
nerozparcelúvane nerozparcelúvane
ref: najrozparcelúvanejšie pred: najnerozparcelúvanejšie
zdezintegrovávacích zdezintegrovávacích
zdezintegrovávacích zdezintegrovávacích
zdezintegrovávacích zdezintegrovávacích
zdezintegrovávacích zdezintegrovávacích
zdezintegrovávacích zdezintegrovávacích
zdezintegrovávacieho zdezintegrovávacieho
zdezintegrovávacej zdezintegrovávacej
zdezintegrovávacie zdezintegrovávacie
zdezintegrovávaciemu zdezintegrovávaciemu
zdezintegrovávaciemu zdezintegrovávaciemu
zdezintegrovávacím zdezintegrovávacím
zdezintegrovávacím zdezintegrovávacím
zdezintegrovávacom zdezintegrovávacom
zdezintegrovávací zdezintegrovávací
zdezintegrovávací zdezintegrovávací
zdezintegrovávací zdezintegrovávací
preasfaltovávateľnosť preasfaltovávateľnosť
preasfaltovávateľnosti preasfaltovávateľnosti
preasfaltovávateľnosti preasfaltovávateľnosti
preasfaltovávateľnosťou preasfaltovávateľnosťou
vyhrnutú vyhrnutú
vyhrnuté vyhrnuté
vyhrnuté vyhrnuté
vyhrnuté vyhrnuté
vyhrnutom vyhrnutom
najvyhrnutejšiu najvyhrnutejšiu
vyhrnutejšom vyhrnutejšom
vyhrnutejšiemu vyhrnutejšiemu
vyhrnutého vyhrnutého
vyhrnutejším vyhrnutejším
najvyhrnutejším najvyhrnutejším
vyhrnutejšia vyhrnutejšia
vyhrnutá vyhrnutá
vyhrnutejší vyhrnutejší
najvyhrnutejší najvyhrnutejší
najvyhrnutejších najvyhrnutejších
vyhrnutejších vyhrnutejších
najvyhrnutejších najvyhrnutejších
najvyhrnutejších najvyhrnutejších
najvyhrnutejších najvyhrnutejších
vyhrnutejších vyhrnutejších
najvyhrnutejších najvyhrnutejších
vyhrnutejších vyhrnutejších
vyhrnutejších vyhrnutejších
najvyhrnutejších najvyhrnutejších
najvyhrnutejšie najvyhrnutejšie
vyhrnutejšie vyhrnutejšie
najvyhrnutejšie najvyhrnutejšie
vyhrnutejšie vyhrnutejšie
najvyhrnutejšie najvyhrnutejšie
vyhrnutejšie vyhrnutejšie
vyhrnutejšie vyhrnutejšie
vyhrnutých vyhrnutých
vyhrnutých vyhrnutých
vyhrnutých vyhrnutých
vyhrnutému vyhrnutému
najvyhrnutejšieho najvyhrnutejšieho
vyhrnutým vyhrnutým
vyhrnutej vyhrnutej
vyhrnutejšími vyhrnutejšími
vyhrnutejšími vyhrnutejšími
otesávateľnú otesávateľnú
otesávateľné otesávateľné
otesávateľné otesávateľné
otesávateľné otesávateľné
otesávateľnom otesávateľnom
otesávateľnom otesávateľnom
otesávateľnou otesávateľnou
najotesávateľnejšom najotesávateľnejšom
otesávateľnejšom otesávateľnejšom
najotesávateľnejšom najotesávateľnejšom
otesávateľnejšiemu otesávateľnejšiemu
otesávateľnými otesávateľnými
otesávateľného otesávateľného
otesávateľný otesávateľný
otesávateľný otesávateľný
otesávateľný otesávateľný
najotesávateľnejším najotesávateľnejším
najotesávateľnejším najotesávateľnejším
najotesávateľnejším najotesávateľnejším
otesávateľnejším otesávateľnejším
otesávateľnejším otesávateľnejším
najotesávateľnejším najotesávateľnejším
otesávateľnejšia otesávateľnejšia
otesávateľná otesávateľná
najotesávateľnejší najotesávateľnejší
otesávateľnejší otesávateľnejší
najotesávateľnejší najotesávateľnejší
otesávateľnejší otesávateľnejší
najotesávateľnejších najotesávateľnejších
najotesávateľnejších najotesávateľnejších
najotesávateľnejších najotesávateľnejších
najotesávateľnejších najotesávateľnejších
najotesávateľnejších najotesávateľnejších
otesávateľnejšie otesávateľnejšie
otesávateľnejšie otesávateľnejšie
otesávateľnejšie otesávateľnejšie
otesávateľnejšie otesávateľnejšie
otesávateľnejšie otesávateľnejšie
otesávateľnejšie otesávateľnejšie
otesávateľných otesávateľných
otesávateľných otesávateľných
otesávateľnejšej otesávateľnejšej
najotesávateľnejšej najotesávateľnejšej
otesávateľnejšej otesávateľnejšej
otesávateľnému otesávateľnému
otesávateľnejšieho otesávateľnejšieho
najotesávateľnejšieho najotesávateľnejšieho
otesávateľnejšieho otesávateľnejšieho
otesávateľným otesávateľným
otesávateľnej otesávateľnej
otesávateľnejšími otesávateľnejšími
odvliekavate odvliekavate
neodvliekavali sme neodvliekavali sme
neodvliekavali by neodvliekavali by
neboli by sme odvliekavali neboli by sme odvliekavali
neodvliekavali ste neodvliekavali ste
neodvliekavali by neodvliekavali by
neodvliekavali by ste neodvliekavali by ste
neboli by odvliekavali neboli by odvliekavali
neboli by ste odvliekavali neboli by ste odvliekavali
neodvliekavali sme neodvliekavali sme
neodvliekavali ste neodvliekavali ste
neodvliekavali by neodvliekavali by
neodvliekavali by sme neodvliekavali by sme
neboli by ste odvliekavali neboli by ste odvliekavali
neodvliekavali sme neodvliekavali sme
neodvliekavali by neodvliekavali by
neodvliekavali by ste neodvliekavali by ste

neboli by odvliekavali neboli by odvliekavali
neodvliekavali sme neodvliekavali sme
neodvliekavali by neodvliekavali by
neboli by odvliekavali neboli by odvliekavali
neboli by sme odvliekavali neboli by sme odvliekavali
neodvliekavali sme neodvliekavali sme
neodvliekavali by sme neodvliekavali by sme
neodvliekavali sme neodvliekavali sme
neodvliekavali ste neodvliekavali ste
bola by si odvliekavala bola by si odvliekavala
odvliekavala som odvliekavala som
odvliekavala si odvliekavala si
odvliekavala by odvliekavala odvliekavala by odvliekavala
bola by som odvliekavala bola by som odvliekavala
neodvliekavaný neodvliekavaný
ref: neodvliekavalo by odvliekavala pred: neodvliekavalo by odvliekavalo
nebolo by som odvliekavalo nebolo by som odvliekavalo
neodvliekavalo by odvliekavalo neodvliekavalo by odvliekavalo
nebolo by som odvliekavalo nebolo by som odvliekavalo
odvliekavanú odvliekavanú
odvliekavajte odvliekavajte
odvliekavaní odvliekavaní
neodvliekavaní neodvliekavaní
neodvliekavala som neodvliekavala som
nebola by odvliekavala nebola by odvliekavala
neodvliekavala neodvliekavala
neodvliekavala by odvliekavala neodvliekavala by odvliekavala
nebola by odvliekavala nebola by odvliekavala
odvliekavaj odvliekavaj
odvliekavané odvliekavané
budem odvliekavať budem odvliekavať
bude odvliekavať bude odvliekavať
nebude odvliekavať nebude odvliekavať
budeme odvliekavať budeme odvliekavať
nebudeme odvliekavať nebudeme odvliekavať
budú odvliekavať budú odvliekavať
odvliekavalo odvliekavalo
bolo by odvliekavalo bolo by odvliekavalo
bolo by si odvliekavalo bolo by si odvliekavalo
odvliekavalo som odvliekavalo som
neodvliekavané neodvliekavané
odvliekavame odvliekavame
odvliekavame odvliekavame
neodvliekavanú neodvliekavanú
neodvliekavanú neodvliekavanú
odvliekavajú odvliekavajú
odvliekavajú odvliekavajú
neodvliekavaný neodvliekavaný
odvliekavali by ste odvliekavali by ste
odvliekavali by odvliekavali by
odvliekavali by sme odvliekavali by sme
boli by sme odvliekavali boli by sme odvliekavali
boli by sme odvliekavali boli by sme odvliekavali
odvliekavali odvliekavali
odvliekavali by ste odvliekavali by ste
odvliekavali odvliekavali
odvliekavali by odvliekavali by
boli by odvliekavali boli by odvliekavali
boli by sme odvliekavali boli by sme odvliekavali
odvliekavali by sme odvliekavali by sme
odvliekavali ste odvliekavali ste
odvliekavali sme odvliekavali sme
boli by sme odvliekavali boli by sme odvliekavali
neodvliekavajú neodvliekavajú
neodvliekavajú neodvliekavajú
ref: odvliekavaná pred: odvliekavanú
odvliekavaná odvliekavaná
neodvliekavané neodvliekavané
neodvliekavam neodvliekavam
neodvliekaval si neodvliekaval si
ref: neodvliekaval by som odvliekavali pred: neodvliekaval by som odvliekaval
neodvliekaval neodvliekaval
neodvliekaval by som odvliekaval neodvliekaval by som odvliekaval
nebol by som odvliekaval nebol by som odvliekaval
neodvliekavajte neodvliekavajte
odvliekavané odvliekavané
odvliekaval odvliekaval
odvliekaval si odvliekaval si
odvliekaval by si odvliekaval odvliekaval by si odvliekaval
bol by odvliekaval bol by odvliekaval
odvliekaval by odvliekaval odvliekaval by odvliekaval
odvliekaval by si odvliekaval odvliekaval by si odvliekaval
bol by odvliekaval bol by odvliekaval
odvliekava odvliekava
neuropočítače neuropočítače
neuropočítačom neuropočítačom
neuropočítač neuropočítač
neuropočítač neuropočítač
ref: najsfarbúvateľnejšie pred: najnesfarbúvateľnejšie
najnesfarbúvateľnejšie najnesfarbúvateľnejšie
čmeliak čmeliak
ref: čmeliakoch pred: čmeliakach
ref: čmeliakmi pred: čmeliakami
presnoríš presnoríš
presnoríš presnoríš
presnoril presnoril
ref: presnoril by presnilo pred: presnoril by presnoril
presnoril si presnoril si
presnoril by si presnoril presnoril by si presnoril
bol by presnoril bol by presnoril
nepresnorilo som nepresnorilo som
ref: nepresnorilo by som presnoril pred: nepresnorilo by som presnorilo
nebolo by som presnorilo nebolo by som presnorilo
nebolo by si presnorilo nebolo by si presnorilo
nepresnorenú nepresnorenú
nepresnorené nepresnorené
nepresnorené nepresnorené
presnoria presnoria
presnoria presnoria
presnorený presnorený
presnorené presnorené
nepresnoriť nepresnoriť
presnorené presnorené
nepresnorme nepresnorme
nepresnorili nepresnorili
nepresnorili ste nepresnorili ste
neboli by sme presnorili neboli by sme presnorili
nepresnorili nepresnorili
nepresnorili sme nepresnorili sme
nepresnorili by sme nepresnorili by sme
nepresnorili by ste nepresnorili by ste
nepresnorili by sme nepresnorili by sme
nepresnorili by ste nepresnorili by ste
nepresnorili ste nepresnorili ste
nepresnorili by sme nepresnorili by sme
neboli by presnorili neboli by presnorili
nepresnorili sme nepresnorili sme
neboli by presnorili neboli by presnorili
nepresnorili by ste nepresnorili by ste
neboli by sme presnorili neboli by sme presnorili
nepresnorili ste nepresnorili ste
nepresnorili by nepresnorili by
nepresnorili by sme nepresnorili by sme
neboli by sme presnorili neboli by sme presnorili
nepresnorili nepresnorili
nepresnorili by ste nepresnorili by ste
bolo by som presnorilo bolo by som presnorilo
presnorilo by som presnorilo presnorilo by som presnorilo
nepresnorené nepresnorené
presnorili ste presnorili ste
presnorili by sme presnorili by sme
presnorili by ste presnorili by ste
boli by presnorili boli by presnorili
presnorili presnorili
presnorili by ste presnorili by ste
presnorili sme presnorili sme
presnorili by sme presnorili by sme
presnorili ste presnorili ste
boli by ste presnorili boli by ste presnorili
presnorili by ste presnorili by ste
boli by presnorili boli by presnorili
presnorili by presnorili by
boli by presnorili boli by presnorili
boli by ste presnorili boli by ste presnorili
presnorili presnorili
presnorili ste presnorili ste
presnorili by presnorili by
presnorili by sme presnorili by sme
boli by ste presnorili boli by ste presnorili
nepresnorení nepresnorení
nebudeš presnoriť nebudeš presnoriť
presnorila som presnorila som
ref: presnorila by presnorili pred: presnorila by presnorila
ref: presnorila by si presnorili pred: presnorila by si presnorila
presnorila presnorila
presnorila by si presnorila presnorila by si presnorila
bola by presnorila bola by presnorila
nepresnorený nepresnorený
nepresnorený nepresnorený
nepresnorila by presnorila nepresnorila by presnorila
nebola by som presnorila nebola by som presnorila
nebola by si presnorila nebola by si presnorila
nebola by si presnorila nebola by si presnorila
ref: nepresnoril by som presnorila pred: nepresnoril by som presnoril
ref: nepresnoril by si presnorila pred: nepresnoril by si presnoril
nebol by som presnoril nebol by som presnoril
nepresnoril si nepresnoril si
nepresnoril by presnoril nepresnoril by presnoril
nepresnoril by si presnoril nepresnoril by si presnoril
nepresnoríme nepresnoríme
ref: presnorená pred: presnorenú
ref: presnorená pred: presnorenú
nepresnoríš nepresnoríš
triódam triódam
triódy triódy
plečkúvateľnosť plečkúvateľnosť
plečkúvateľnosťami plečkúvateľnosťami
plečkúvateľnosti plečkúvateľnosti
plečkúvateľnosti plečkúvateľnosti
opentliteľného opentliteľného
opentliteľného opentliteľného
opentliteľnými opentliteľnými
opentliteľnejšia opentliteľnejšia
opentliteľná opentliteľná
opentliteľná opentliteľná
opentliteľnejším opentliteľnejším
opentliteľnejším opentliteľnejším
opentliteľnejším opentliteľnejším
opentliteľnejším opentliteľnejším
opentliteľný opentliteľný
opentliteľné opentliteľné
opentliteľné opentliteľné
opentliteľné opentliteľné
opentliteľnejšiemu opentliteľnejšiemu
najopentliteľnejšiemu najopentliteľnejšiemu
najopentliteľnejšom najopentliteľnejšom
opentliteľnejšom opentliteľnejšom
opentliteľným opentliteľným
opentliteľným opentliteľným
opentliteľnej opentliteľnej
opentliteľnejšími opentliteľnejšími
najopentliteľnejšími najopentliteľnejšími
opentliteľnejšími opentliteľnejšími
opentliteľnejšími opentliteľnejšími
najopentliteľnejšími najopentliteľnejšími
opentliteľní opentliteľní
najopentliteľnejších najopentliteľnejších
opentliteľnejších opentliteľnejších
opentliteľnejších opentliteľnejších
najopentliteľnejších najopentliteľnejších
opentliteľnejších opentliteľnejších
opentliteľnejších opentliteľnejších
opentliteľnejších opentliteľnejších

opentliteľnejší opentliteľnejší
najopentliteľnejší najopentliteľnejší
najopentliteľnejší najopentliteľnejší
opentliteľnejší opentliteľnejší
opentliteľnejšie opentliteľnejšie
najopentliteľnejšie najopentliteľnejšie
opentliteľnejšie opentliteľnejšie
opentliteľnejšie opentliteľnejšie
najopentliteľnejšie najopentliteľnejšie
opentliteľných opentliteľných
opentliteľných opentliteľných
najopentliteľnejšej najopentliteľnejšej
opentliteľnejšieho opentliteľnejšieho
opentliteľnému opentliteľnému
dĺžam dĺžam
ref: dĺži pred: dĺže
dĺže dĺže
dĺžach dĺžach
dĺž dĺž
ref: dĺž pred: dĺži
naväzovávanú naväzovávanú
naväzovávané naväzovávané
naväzovávané naväzovávané
naväzovávanom naväzovávanom
naväzovávanejšom naväzovávanejšom
najnaväzovávanejšom najnaväzovávanejšom
naväzovávanejšom naväzovávanejšom
najnaväzovávanejšiemu najnaväzovávanejšiemu
naväzovávanými naväzovávanými
naväzovávanými naväzovávanými
naväzovávaného naväzovávaného
naväzovávaný naväzovávaný
najnaväzovávanejším najnaväzovávanejším
najnaväzovávanejším najnaväzovávanejším
najnaväzovávanejším najnaväzovávanejším
najnaväzovávanejším najnaväzovávanejším
najnaväzovávanejším najnaväzovávanejším
najnaväzovávanejšia najnaväzovávanejšia
naväzovávaná naväzovávaná
naväzovávanejší naväzovávanejší
naväzovávanejší naväzovávanejší
najnaväzovávanejší najnaväzovávanejší
najnaväzovávanejší najnaväzovávanejší
najnaväzovávanejší najnaväzovávanejší
naväzovávanejších naväzovávanejších
najnaväzovávanejších najnaväzovávanejších
naväzovávanejších naväzovávanejších
najnaväzovávanejších najnaväzovávanejších
naväzovávanejších naväzovávanejších
najnaväzovávanejšie najnaväzovávanejšie
najnaväzovávanejšie najnaväzovávanejšie
naväzovávanejšie naväzovávanejšie
najnaväzovávanejšie najnaväzovávanejšie
naväzovávaných naväzovávaných
naväzovávaných naväzovávaných
najnaväzovávanejšej najnaväzovávanejšej
naväzovávanejšej naväzovávanejšej
naväzovávanému naväzovávanému
naväzovávanému naväzovávanému
naväzovávanejšieho naväzovávanejšieho
naväzovávaným naväzovávaným
naväzovávaným naväzovávaným
naväzovávaným naväzovávaným
naväzovávaným naväzovávaným
naväzovávanejšími naväzovávanejšími
naväzovávanejšími naväzovávanejšími
najnaväzovávanejšími najnaväzovávanejšími
najnaväzovávanejšími najnaväzovávanejšími
dotekanú dotekanú
dotekané dotekané
dotekané dotekané
dotekané dotekané
dotekanom dotekanom
dotekanejšiu dotekanejšiu
dotekanou dotekanou
dotekanejšom dotekanejšom
dotekanejšom dotekanejšom
dotekanejšiemu dotekanejšiemu
najdotekanejšiemu najdotekanejšiemu
dotekanými dotekanými
dotekanými dotekanými
dotekaného dotekaného
dotekaného dotekaného
dotekaný dotekaný
dotekaný dotekaný
dotekaný dotekaný
najdotekanejším najdotekanejším
najdotekanejším najdotekanejším
dotekanejším dotekanejším
najdotekanejším najdotekanejším
dotekanejším dotekanejším
dotekanejšia dotekanejšia
najdotekanejšia najdotekanejšia
dotekaná dotekaná
dotekaná dotekaná
dotekanejší dotekanejší
najdotekanejší najdotekanejší
dotekanejší dotekanejší
najdotekanejší najdotekanejší
dotekanejší dotekanejší
najdotekanejší najdotekanejší
dotekanejší dotekanejší
najdotekanejší najdotekanejší
dotekanejších dotekanejších
najdotekanejších najdotekanejších
dotekanejších dotekanejších
najdotekanejšie najdotekanejšie
dotekanejšie dotekanejšie
najdotekanejšie najdotekanejšie
dotekanejšie dotekanejšie
najdotekanejšie najdotekanejšie
dotekaní dotekaní
dotekaných dotekaných
dotekaných dotekaných
dotekaných dotekaných
dotekanejšej dotekanejšej
dotekanejšej dotekanejšej
dotekanejšieho dotekanejšieho
najdotekanejšieho najdotekanejšieho
dotekanejšieho dotekanejšieho
najdotekanejšieho najdotekanejšieho
dotekaným dotekaným
dotekaným dotekaným
dotekanej dotekanej
dotekanej dotekanej
dotekanejšou dotekanejšou
dotekanejšími dotekanejšími
dotekanejšími dotekanejšími
najdotekanejšími najdotekanejšími
najdotekanejšími najdotekanejšími
odľahčovateľnosti odľahčovateľnosti
odľahčovateľnostiach odľahčovateľnostiach
odľahčovateľnosťou odľahčovateľnosťou
odľahčovateľnostiam odľahčovateľnostiam
0.958
livles/slavic-distant-word-or-family
test file:  ../preprocessing/preprocessing_to_json/data/mkd-lang-word_tst.json
отворам отворам
отворат отворат
отворев отворев
отворевме отворевме
отворевте отворевте
отворел отворел
отвореле отвореле
отворело отворело
отворете отворете
отвореше отвореше
отвори отвори
отвори отвори
отвори отвори
отвори отвори
отворив отворив
отворивме отворивме
отворил отворил
отворило отворило
отвориме отвориме
чепна чепна
чепнаа чепнаа
чепнав чепнав
чепнала чепнала
чепнало чепнало
чепнам чепнам
чепнат чепнат
чепнев чепнев
чепневме чепневме
чепневте чепневте
чепнела чепнела
чепнеле чепнеле
чепнеме чепнеме
чепнете чепнете
чепнете чепнете
чепнеш чепнеш
чепнеше чепнеше
чепнеше чепнеше
мајтапчии мајтапчии
мајтапчииве мајтапчииве
мајтапчиине мајтапчиине
мајтапчија мајтапчија
мајтапчијана мајтапчијана
мајтапчијата мајтапчијата
ref: манији pred: мании
ref: манијиве pred: манииве
ref: манијине pred: маниине
ref: манијја pred: манија
термит термит
термита термита
термити термити
термити термити
термитите термитите
термитон термитон
термитот термитот
термиту термиту
мечувалство мечувалство
мечувалствоно мечувалствоно
нацрта нацрта
нацрта нацрта
нацрта нацрта
нацртаа нацртаа
нацртаа нацртаа
нацртав нацртав
нацртав нацртав
нацртавме нацртавме
нацртајте нацртајте
нацртал нацртал
нацртале нацртале
нацртало нацртало
нацртало нацртало
нацртам нацртам
нацртан нацртан
нацртате нацртате
нацрташ нацрташ
нацрташе нацрташе
патос патос
патосов патосов
патосон патосон
патосот патосот
патосу патосу
ѕидар ѕидар
ref: ѕидаре pred: ѕидару
ѕидари ѕидари
ѕидариве ѕидариве
ѕидарине ѕидарине
ѕидарите ѕидарите
ѕидаров ѕидаров
ѕидарон ѕидарон
етида етида
етиди етиди
етидине етидине
етидо етидо
дејност дејност
дејноста дејноста
дејности дејности
дејностиве дејностиве
дејностине дејностине
дејностите дејностите
врачува врачува
врачував врачував
врачувавме врачувавме
врачувавте врачувавте
врачувај врачувај
врачувајте врачувајте
врачувајќи врачувајќи
врачувал врачувал
врачувале врачувале
врачувам врачувам
врачуваме врачуваме
врачување врачување
врачуваш врачуваш
врачуваше врачуваше
потрагана потрагана
потраги потраги
потрагиве потрагиве
потрагите потрагите
потраго потраго
вакцинана вакцинана
вакцината вакцината
вакциниве вакциниве
вакцинине вакцинине
вакцините вакцините
недоверливост недоверливост
недоверливост недоверливост
недоверливоста недоверливоста
ref: ќе мачкав pred: мачкава
ref: ќе мачкам pred: мачката
ref: ќе сум мачкал pred: мачкана
бучкуруш бучкуруш
бучкуруши бучкуруши
бучкурушиве бучкурушиве
бучкурушине бучкурушине
бучкурушите бучкурушите
бучкурушот бучкурушот
бучкурушу бучкурушу
решета решета
решета решета
решетава решетава
решетана решетана
решетово решетово
решетото решетото
изџвака изџвака
изџвакаа изџвакаа
изџвакаат изџвакаат
изџвакав изџвакав
изџвакавме изџвакавме
изџвакавме изџвакавме
изџвакавте изџвакавте
изџвакај изџвакај
изџвакајте изџвакајте
изџвакал изџвакал
изџвакале изџвакале
изџвакале изџвакале
изџвакам изџвакам
изџвакаме изџвакаме
изџвакан изџвакан
изџвакаше изџвакаше
помодари помодари
помодариве помодариве
помодарине помодарине
помодаров помодаров
помодарон помодарон
помодарот помодарот
помодару помодару
печеница печеница
печеницана печеницана
печеницата печеницата
печенице печенице
печеници печеници
печениците печениците
помножам помножам
помножат помножат
помножеа помножеа
помножев помножев
помножевме помножевме
помножевте помножевте
помножел помножел
помножела помножела
помножеле помножеле
помножело помножело
помножен помножен
помножи помножи
помножи помножи
помножил помножил
помножила помножила
помножиме помножиме
помножиш помножиш
ref: врскине pred: врскион
забележителен забележителен
забележителна забележителна
забележителнана забележителнана
забележителната забележителната
забележителни забележителни
забележителнине забележителнине
забележителнион забележителнион
забележителново забележителново
забележителноно забележителноно
изнервирајте се изнервирајте се
се изнервира се изнервира
се изнервира се изнервира
се изнервираа се изнервираа
се изнервираа се изнервираа
се изнервирав се изнервирав
се изнервирав се изнервирав
се изнервиравте се изнервиравте
се изнервирал се изнервирал
се изнервирала се изнервирала

се изнервирала се изнервирала
се изнервирале се изнервирале
се изнервирало се изнервирало
се изнервирало се изнервирало
се изнервирам се изнервирам
се изнервираме се изнервираме
се изнервирате се изнервирате
ужасна ужасна
ужасна ужасна
ужаснав ужаснав
ужаснавме ужаснавме
ужаснавте ужаснавте
ужаснал ужаснал
ужаснала ужаснала
ужаснале ужаснале
ужаснало ужаснало
ужаснам ужаснам
ужасне ужасне
ужасневме ужасневме
ужаснел ужаснел
ужаснела ужаснела
ужаснеле ужаснеле
ужаснете ужаснете
ужаснете ужаснете
украсна украсна
украснава украснава
украснана украснана
украсната украсната
украсни украсни
украсниве украсниве
украснине украснине
украсниов украсниов
украснион украснион
украсниот украсниот
украсново украсново
украсноно украсноно
наидува наидува
наидуваа наидуваа
наидував наидував
наидувавме наидувавме
наидувај наидувај
наидувајте наидувајте
наидувајќи наидувајќи
наидувал наидувал
наидувала наидувала
наидувале наидувале
наидувало наидувало
наидуваме наидуваме
наидување наидување
наидувате наидувате
наидуваше наидуваше
позлатам позлатам
позлатеа позлатеа
позлатевте позлатевте
позлателе позлателе
позлатен позлатен
позлатеше позлатеше
позлатеше позлатеше
позлати позлати
позлати позлати
позлати позлати
позлативте позлативте
позлатил позлатил
позлатила позлатила
позлатите позлатите
регистрираат регистрираат
регистрирав регистрирав
регистриравме регистриравме
регистрирајќи регистрирајќи
регистрирале регистрирале
регистрирало регистрирало
регистрирам регистрирам
регистриран регистриран
регистрирате регистрирате
регистрираш регистрираш
регистрираше регистрираше
регистрираше регистрираше
валкаат валкаат
валкавме валкавме
валкавте валкавте
валкајќи валкајќи
валкал валкал
валкала валкала
валкало валкало
валкаме валкаме
валкан валкан
валкате валкате
валкаш валкаш
чорбаџикана чорбаџикана
чорбаџиката чорбаџиката
ref: чорбаџике pred: чорбаџико
чорбаџики чорбаџики
чорбаџикиве чорбаџикиве
чорбаџиките чорбаџиките
професорка професорка
професоркана професоркана
ref: професорке pred: професорко
професорки професорки
професоркиве професоркиве
професоркине професоркине
професорките професорките
фантазира фантазира
фантазираат фантазираат
фантазирај фантазирај
фантазирајќи фантазирајќи
фантазирал фантазирал
фантазирале фантазирале
фантазирало фантазирало
фантазирам фантазирам
фантазираме фантазираме
фантазиран фантазиран
фантазирање фантазирање
фантазираше фантазираше
истурпија истурпија
истурпија истурпија
истурпијаа истурпијаа
истурпијаа истурпијаа
истурпијав истурпијав
истурпијавме истурпијавме
истурпијавме истурпијавме
истурпијавте истурпијавте
истурпијавте истурпијавте
истурпијај истурпијај
истурпијајте истурпијајте
истурпијал истурпијал
истурпијал истурпијал
истурпијала истурпијала
истурпијале истурпијале
истурпијаш истурпијаш
истурпијаше истурпијаше
истурпијаше истурпијаше
британска британска
британскава британскава
британскана британскана
британски британски
британски британски
британскине британскине
британскиов британскиов
британскиот британскиот
британските британските
британско британско
британсково британсково
британсконо британсконо
пиленцана пиленцана
пиленцата пиленцата
пиленце пиленце
пиленце пиленце
пиленцево пиленцево
пиленцено пиленцено
пиленцето пиленцето
ќоравава ќоравава
ќоравана ќоравана
ќоравиов ќоравиов
ќоравион ќоравион
ќоравиот ќоравиот
ќораво ќораво
ќоравово ќоравово
ќоравоно ќоравоно
ќоравото ќоравото
третина третина
третинана третинана
третината третината
третини третини
третини третини
третините третините
третино третино
елана елана
еланиве еланиве
еланине еланине
еланите еланите
еланот еланот
бездомен бездомен
бездомнава бездомнава
бездомнана бездомнана
бездомната бездомната
бездомни бездомни
бездомниве бездомниве
бездомниов бездомниов
бездомнион бездомнион
бездомниот бездомниот
бездомно бездомно
бездомново бездомново
бездомното бездомното
бразилска бразилска
бразилски бразилски
бразилски бразилски
бразилскиве бразилскиве
бразилскине бразилскине
бразилскиов бразилскиов
бразилскиот бразилскиот
бразилските бразилските
бразилско бразилско
бразилсконо бразилсконо
бразилското бразилското
робии робии
робииве робииве
робиине робиине
робиите робиите
робијава робијава
робијана робијана
робијата робијата
робијо робијо
грешен грешен
грешнава грешнава
грешнана грешнана
грешниве грешниве
грешниов грешниов
грешнион грешнион
грешниот грешниот
грешните грешните
грешно грешно
грешново грешново
грешноно грешноно
грешното грешното
жита жита
житава житава
житана житана
житата житата
жито жито
житово житово
житоно житоно
житото житото
обработливава обработливава
обработливата обработливата
обработливи обработливи
обработлививе обработлививе
обработливиов обработливиов
обработливион обработливион
обработливо обработливо
обработливово обработливово
обработливоно обработливоно
обработливото обработливото
мотика мотика
мотикана мотикана
мотики мотики
мотики мотики
мотикиве мотикиве
мотикине мотикине
мотиките мотиките
победник победник
победника победника
победникон победникон
победникот победникот
победнику победнику
победнициве победнициве
победниците победниците
сточарства сточарства
сточарства сточарства
сточарствава сточарствава
сточарствата сточарствата
сточарство сточарство
сточарството сточарството
одам одам
одат одат
одевте одевте
одејќи одејќи
одел одел
оделе оделе
одење одење
одеше одеше
одеше одеше
оди оди
одиме одиме
одите одите
одиш одиш
санкајте се санкајте се
санкан санкан
се санка се санка
се санка се санка
се санкаа се санкаа
се санкав се санкав
се санкавте се санкавте
се санкавте се санкавте
се санкала се санкала
се санкале се санкале
се санкало се санкало
се санкаме се санкаме
се санкаш се санкаш
се санкаше се санкаше
се санкаше се санкаше
воскресна воскресна
воскресна воскресна
воскреснаа воскреснаа
воскреснав воскреснав
воскреснавме воскреснавме
воскреснавте воскреснавте
воскреснал воскреснал
воскреснала воскреснала
воскреснало воскреснало
воскресневме воскресневме
воскресневте воскресневте
воскреснел воскреснел
воскреснела воскреснела
воскреснете воскреснете
воскреснеш воскреснеш
воскреснеше воскреснеше
воскреснеше воскреснеше
запиша запиша
запишаа запишаа
запишавме запишавме
запишавте запишавте
запишала запишала
запишало запишало
запишам запишам
ref: запишан pred: запишен
запишеа запишеа
запишев запишев
запишел запишел
запишела запишела
запишеле запишеле
запишеме запишеме
запишете запишете
запишете запишете
запишеш запишеш
запишеше запишеше
запишеше запишеше
финансира финансира
финансираа финансираа
финансиравме финансиравме
финансиравте финансиравте
финансирајте финансирајте
финансирал финансирал
финансирала финансирала
финансираме финансираме
финансирање финансирање
разварат разварат
развареа развареа
разваревме разваревме
разваревте разваревте
разварело разварело
разварете разварете
развари развари
развари развари
развари развари
разваривме разваривме
разваривте разваривте
разварија разварија
разварил разварил
разварила разварила
разварило разварило
развариме развариме
разварите разварите
мозочницава мозочницава
мозочницата мозочницата
мозочнице мозочнице
мозочници мозочници
мозочнициве мозочнициве
мозочницине мозочницине
бубрег бубрег
бубрега бубрега
бубрегон бубрегон
бубрегот бубрегот
ref: бубрези pred: бубреги
ref: бубрезиве pred: бубрегиве
ref: бубрезите pred: бубрегите
ref: сознаниjа pred: сознания
ref: сознаниjата pred: сознанията
сознание сознание
сознание сознание
сознанието сознанието
казнам казнам
казнеа казнеа
казнев казнев
казневме казневме
казневте казневте
казнел казнел
казнела казнела
казнело казнело
казнет казнет
казнете казнете
казнеше казнеше
казни казни
казни казни
казни казни
казнив казнив
казнивте казнивте
казнил казнил
казниле казниле
казнило казнило
казниме казниме
казните казните
казниш казниш
бенкана бенкана
бенки бенки
бенкине бенкине
бенките бенките
бунтува бунтува
бунтуваа бунтуваа
бунтуваат бунтуваат
бунтував бунтував
бунтувавме бунтувавме
бунтувајте бунтувајте
бунтувал бунтувал
бунтувала бунтувала
бунтувале бунтувале
бунтуваме бунтуваме
бунтување бунтување
бунтуваш бунтуваш
бунтуваше бунтуваше
образован образован
образованана образованана
образовани образовани
образованине образованине
образованиов образованиов
образованион образованион
образовано образовано
образованово образованово
поволност поволност
доградам доградам
доградат доградат

доградев доградев
доградевме доградевме
доградело доградело
доградеше доградеше
догради догради
догради догради
догради догради
догради догради
доградив доградив
доградивме доградивме
доградивте доградивте
доградија доградија
доградил доградил
доградила доградила
доградиле доградиле
доградило доградило
доградите доградите
шестаголнава шестаголнава
шестаголнана шестаголнана
шестаголнине шестаголнине
шестаголниов шестаголниов
шестаголниот шестаголниот
шестаголните шестаголните
шестаголно шестаголно
шестаголноно шестаголноно
шестаголното шестаголното
опсипа опсипа
опсипаа опсипаа
опсипав опсипав
опсипавте опсипавте
опсипал опсипал
опсипале опсипале
опсипало опсипало
опсипам опсипам
ref: опсипан pred: опсипен
опсипевме опсипевме
опсипевте опсипевте
опсипел опсипел
опсипеле опсипеле
опсипеме опсипеме
опсипеш опсипеш
опсипеше опсипеше
подлактицава подлактицава
подлактицана подлактицана
подлактице подлактице
ref: натерааат pred: натераат
ref: натераав pred: натерав
ref: натераав pred: натерав
ref: натераавме pred: натеравме
ref: натераавме pred: натеравме
ref: натераавте pred: натеравте
ref: натераавте pred: натеравте
ref: натераај pred: натерај
ref: натераал pred: натерал
ref: натераал pred: натерал
ref: натераала pred: натерала
ref: натераале pred: натерале
ref: натераало pred: натерало
ref: натераало pred: натерало
ref: натераам pred: натерам
ref: натерааме pred: натераме
ref: натераан pred: натеран
ref: натераате pred: натерате
ref: натерааш pred: натераш
ref: натерааше pred: натераше
ref: натерааше pred: натераше
измрсам измрсам
измрсеа измрсеа
измрсевме измрсевме
измрсевте измрсевте
измрсел измрсел
измрселе измрселе
измрсело измрсело
измрсен измрсен
измрсете измрсете
измрси измрси
измрси измрси
измрси измрси
измрсив измрсив
измрсиш измрсиш
напредува напредува
напредував напредував
напредувавме напредувавме
напредувавте напредувавте
напредувајќи напредувајќи
напредувала напредувала
напредувало напредувало
напредуваме напредуваме
напредување напредување
напредувате напредувате
напредуваш напредуваш
напредуваше напредуваше
напредуваше напредуваше
ref: одржа pred: одржи
ref: одржа pred: одржи
ref: одржавте pred: одрживте
ref: одржал pred: одржил
ref: одржало pred: одржило
ref: одржан pred: одржен
одржевме одржевме
одржевте одржевте
одржеле одржеле
одржете одржете
одржеше одржеше
одржи одржи
одржи одржи
одржиме одржиме
некултурност некултурност
ref: рекла pred: речала
ref: рекле pred: речале
ref: рекоа pred: речаа
ref: реков pred: речав
ref: рековме pred: речавме
речам речам
ref: рече pred: реча
ref: рече pred: реча
речеа речеа
речев речев
речевме речевме
речевте речевте
речел речел
речела речела
речеле речеле
речете речете
речеш речеш
речеше речеше
речеше речеше
шамара шамара
шамараа шамараа
шамараат шамараат
шамарав шамарав
шамарал шамарал
шамарало шамарало
шамарам шамарам
шамараме шамараме
шамаран шамаран
шамарање шамарање
шамарате шамарате
шамараш шамараш
шамараше шамараше
подобрувања подобрувања
подобрувањава подобрувањава
подобрување подобрување
подобрувањено подобрувањено
безжичен безжичен
безжичнана безжичнана
безжичната безжичната
безжични безжични
безжичнине безжичнине
безжичниов безжичниов
безжичнион безжичнион
безжично безжично
безжичноно безжичноно
честица честица
честицава честицава
честицана честицана
честицата честицата
честици честици
честици честици
честициве честициве
честицине честицине
растревожува растревожува
растревожував растревожував
растревожувавме растревожувавме
растревожувавте растревожувавте
растревожувај растревожувај
растревожувајќи растревожувајќи
растревожувал растревожувал
растревожувало растревожувало
растревожувам растревожувам
растревожување растревожување
растревожуваше растревожуваше
растревожуваше растревожуваше
мртвороденчено мртвороденчено
мртвороденчиња мртвороденчиња
мртвороденчињава мртвороденчињава
мртвороденчињата мртвороденчињата
несовршенства несовршенства
несовршенствана несовршенствана
несовршенствата несовршенствата
несовршенство несовршенство
несовршенството несовршенството
полезна полезна
полезнава полезнава
полезната полезната
полезнине полезнине
полезниов полезниов
полезниот полезниот
полезните полезните
полезно полезно
полезново полезново
полезното полезното
се задума се задума
се задума се задума
се задумаа се задумаа
се задумаа се задумаа
се задумаат се задумаат
се задумав се задумав
се задумавме се задумавме
се задумавте се задумавте
се задумал се задумал
се задумала се задумала
се задумала се задумала
се задумало се задумало
се задумало се задумало
се задумам се задумам
се задумате се задумате
се задумаш се задумаш
се задумаше се задумаше
се задумаше се задумаше
потчинет потчинет
потчинета потчинета
потчинетава потчинетава
потчинетана потчинетана
потчинетата потчинетата
потчинетине потчинетине
потчинетиот потчинетиот
потчинетоно потчинетоно
потчинетото потчинетото
Словенеца Словенеца
Словенецов Словенецов
Словенецот Словенецот
Словенцине Словенцине
разгневам разгневам
разгневеа разгневеа
разгневев разгневев
разгневевте разгневевте
разгневел разгневел
разгневеле разгневеле
разгневи разгневи
разгневи разгневи
разгневивте разгневивте
разгневија разгневија
разгневил разгневил
разгневила разгневила
разгневиле разгневиле
разгневило разгневило
разгневите разгневите
разгневиш разгневиш
онколошкава онколошкава
онколошки онколошки
онколошкине онколошкине
онколошкиов онколошкиов
онколошкион онколошкион
онколошките онколошките
онколошково онколошково
онколошкото онколошкото
видеа видеа
видеа видеа
ref: видеава pred: видеовиве
видеана видеана
видеата видеата
видео видео
видеово видеово
видеоно видеоно
видеото видеото
Ѓуптин Ѓуптин
ref: Ѓуптине pred: Ѓуптину
Ѓуптини Ѓуптини
Ѓуптинине Ѓуптинине
Ѓуптинов Ѓуптинов
Ѓуптинон Ѓуптинон
Ѓуптинот Ѓуптинот
зинаа зинаа
зинавме зинавме
зинавте зинавте
зинал зинал
зинало зинало
зинат зинат
зине зине
зинеа зинеа
зинев зинев
зиневте зиневте
зинела зинела
зинело зинело
зинеме зинеме
зинете зинете
зинеше зинеше
зинеше зинеше
пичкава пичкава
пичкана пичкана
пичката пичката
пички пички
пичкине пичкине
пичките пичките
пичко пичко
закона закона
закониве закониве
законине законине
законов законов
законон законон
закону закону
мрсен мрсен
мрсна мрсна
мрснава мрснава
мрснана мрснана
мрсната мрсната
мрсни мрсни
мрснине мрснине
мрсниов мрсниов
мрсниот мрсниот
мрсново мрсново
мрсноно мрсноно
мрсното мрсното
испрскаа испрскаа
испрскаат испрскаат
испрскав испрскав
испрскавме испрскавме
испрскавте испрскавте
испрскај испрскај
испрскајте испрскајте
испрскал испрскал
испрскал испрскал
испрскала испрскала
испрскала испрскала
испрскале испрскале
испрскале испрскале
испрскам испрскам
испрскаме испрскаме
испрскате испрскате
испрскаш испрскаш
испрскаше испрскаше
органска органска
органскава органскава
органската органската
органски органски
органски органски
органскион органскион
органскиот органскиот
органските органските
органско органско
органското органското
бодежи бодежи
бодеживе бодеживе
бодежине бодежине
бодежов бодежов
бодежу бодежу
штимунгон штимунгон
штимунгот штимунгот
штимунгу штимунгу
ref: штимунзиве pred: штимунгиве
ref: штимунзите pred: штимунгите
голем голем
големана големана
големиве големиве
големине големине
големиов големиов
големион големион
големиот големиот
големите големите
големо големо
големово големово
здробат здробат
здробеа здробеа
здробев здробев
здробевме здробевме
здробел здробел
здробен здробен
здроби здроби
здроби здроби
здроби здроби
здробивте здробивте
здробила здробила
здробиле здробиле
здробило здробило
здробиш здробиш
пожарен пожарен
пожарна пожарна
пожарнава пожарнава
пожарнана пожарнана
пожарната пожарната
пожарниве пожарниве
пожарниов пожарниов
пожарнион пожарнион
пожарните пожарните
пожарново пожарново
пожарноно пожарноно
пожарното пожарното
маченица маченица
маченицава маченицава
маченицана маченицана
маченици маченици
маченициве маченициве
0.944
livles/slavic-distant-word-or-family
test file:  ../preprocessing/preprocessing_to_json/data/rus-lang-word_tst.json
асексуальных асексуальных
асексуальный асексуальный
асексуальные асексуальные
асексуальной асексуальной
асексуальном асексуальном
асексуальных асексуальных
асексуальным асексуальным
асексуально асексуально
асексуальная асексуальная
асексуальный асексуальный
афроамериканок афроамериканок

афроамериканку афроамериканку
афроамериканках афроамериканках
афроамериканке афроамериканке
афроамериканок афроамериканок
афроамериканки афроамериканки
афроамериканками афроамериканками
афроамериканкой афроамериканкой
афроамериканки афроамериканки
афроамериканка афроамериканка
беленьких беленьких
беленькую беленькую
беленький беленький
беленькому беленькому
беленьким беленьким
беленьких беленьких
беленькой беленькой
беленьким беленьким
беленькими беленькими
беленький беленький
благородие благородие
благородиям благородиям
благородию благородию
благородиях благородиях
благородии благородии
благородий благородий
благородия благородия
благородиями благородиями
благородием благородием
благородие благородие
вешалку вешалку
вешалкам вешалкам
ref: вешалке pred: вешалцы
вешалках вешалках
вешалке вешалке
вешалок вешалок
вешалки вешалки
вешалками вешалками
вешалкой вешалкой
вешалки вешалки
вешалка вешалка
водоносного водоносного
водоносных водоносных
водоносному водоносному
водоносном водоносном
водоносных водоносных
водоносной водоносной
водоносным водоносным
водоносный водоносный
водоносные водоносные
вольнодумцев вольнодумцев
ref: вольнодумца pred: вольнодумеца
вольнодумцам вольнодумцам
вольнодумцу вольнодумцу
вольнодумцах вольнодумцах
ref: вольнодумцев pred: вольнодумцов
вольнодумца вольнодумца
вольнодумцами вольнодумцами
ref: вольнодумцем pred: вольнодумцом
вольнодумец вольнодумец
вскакивав вскакивав
вскакивающий вскакивающий
будешь вскакивать будешь вскакивать
будут вскакивать будут вскакивать
будет вскакивать будет вскакивать
вскакиваю вскакиваю
вскакиваете вскакиваете
вскакивали вскакивали
вскакивало вскакивало
вывёртывавшийся вывёртывавшийся
буду вывёртываться буду вывёртываться
будут вывёртываться будут вывёртываться
будет вывёртываться будет вывёртываться
вывёртывайтесь вывёртывайтесь
вывёртываемся вывёртываемся
вывёртываюсь вывёртываюсь
вывёртываются вывёртываются
вывёртывалось вывёртывалось
выстраивая выстраивая
будешь выстраивать будешь выстраивать
будут выстраивать будут выстраивать
выстраивайте выстраивайте
выстраивай выстраивай
выстраиваем выстраиваем
выстраиваю выстраиваю
выстраиваете выстраиваете
выстраиваешь выстраиваешь
выстраивают выстраивают
выстраивали выстраивали
гастрольного гастрольного
гастрольному гастрольному
гастрольной гастрольной
гастрольного гастрольного
гастрольного гастрольного
гастрольных гастрольных
гастрольным гастрольным
гастрольными гастрольными
гастрольная гастрольная
гастрольное гастрольное
гастрольные гастрольные
гибельного гибельного
гибельное гибельное
гибельному гибельному
гибельным гибельным
гибельном гибельном
гибельных гибельных
гибельного гибельного
гибельным гибельным
гибелен гибелен
гибельно гибельно
гибельные гибельные
глобальных глобальных
глобальный глобальный
глобальной глобальной
глобальному глобальному
глобальному глобальному
глобальным глобальным
глобальных глобальных
глобальных глобальных
глобальным глобальным
глобальным глобальным
деревообделочные деревообделочные
деревообделочную деревообделочную
деревообделочной деревообделочной
деревообделочных деревообделочных
деревообделочных деревообделочных
деревообделочными деревообделочными
деревообделочной деревообделочной
деревообделочные деревообделочные
деревообделочная деревообделочная
ref: жилетки pred: жилеток
жилетку жилетку
жилеткам жилеткам
ref: жилетке pred: жилетцы
жилетках жилетках
жилетке жилетке
жилеток жилеток
жилетками жилетками
жилетки жилетки
жилетка жилетка
зажиточную зажиточную
зажиточные зажиточные
зажиточному зажиточному
зажиточному зажиточному
зажиточным зажиточным
зажиточными зажиточными
зажиточно зажиточно
зажиточная зажиточная
зажиточный зажиточный
зажиточное зажиточное
зажиточны зажиточны
заседания заседания
заседание заседание
заседаниям заседаниям
заседанию заседанию
заседаниях заседаниях
заседании заседании
заседаний заседаний
заседания заседания
заседания заседания
заседание заседание
зрелый зрелый
зрелые зрелые
зрелому зрелому
зрелым зрелым
зрелой зрелой
зрелом зрелом
зрелых зрелых
зрелого зрелого
зрелым зрелым
зрелым зрелым
зрелыми зрелыми
игру игру
играм играм
игре игре
играх играх
игр игр
игры игры
играми играми
игрой игрой
игры игры
игра игра
ref: игрока pred: игрок
ref: игрокам pred: игркам
игроку игроку
ref: игроках pred: игрках
игроке игроке
игроков игроков
игрока игрока
ref: игроками pred: игрками
игроком игроком
игроки игроки
игрок игрок
изолируя изолируя
изолировавший изолировавший
будем изолировать будем изолировать
буду изолировать буду изолировать
будете изолировать будете изолировать
будет изолировать будет изолировать
изолируй изолируй
изолировать изолировать
изолируем изолируем
изолировало изолировало
иностранной иностранной
иностранному иностранному
иностранному иностранному
иностранном иностранном
иностранном иностранном
иностранной иностранной
иностранного иностранного
иностранных иностранных
иностранными иностранными
иностранный иностранный
иностранные иностранные
кованых кованых
кованую кованую
кованой кованой
кованому кованому
кованому кованому
кованых кованых
кованой кованой
кованого кованого
кованым кованым
коваными коваными
красноватого красноватого
красноватый красноватый
красноватому красноватому
красноватым красноватым
красноватой красноватой
красноватого красноватого
красноватыми красноватыми
красновато красновато
красноватая красноватая
красноваты красноваты
кулачковый кулачковый
кулачковое кулачковое
кулачковой кулачковой
кулачковой кулачковой
кулачковом кулачковом
кулачковой кулачковой
кулачкового кулачкового
кулачкового кулачкового
кулачковой кулачковой
кулачковые кулачковые
ланок ланок
ланку ланку
ref: ланке pred: ланцы
ланках ланках
ref: ланке pred: ланце
ланок ланок
ланки ланки
ланкой ланкой
ланки ланки
ласкового ласкового
ласковых ласковых
ласковому ласковому
ласковых ласковых
ласковой ласковой
ласковых ласковых
ласковым ласковым
ласковыми ласковыми
ласковая ласковая
ласковый ласковый
ласковые ласковые
лесопосадочное лесопосадочное
лесопосадочному лесопосадочному
лесопосадочному лесопосадочному
лесопосадочным лесопосадочным
лесопосадочном лесопосадочном
лесопосадочных лесопосадочных
лесопосадочной лесопосадочной
лесопосадочным лесопосадочным
лесопосадочными лесопосадочными
лесопосадочные лесопосадочные
линяв линяв
линявший линявший
будут линять будут линять
линяйте линяйте
линять линять
линяем линяем
линяете линяете
линяешь линяешь
линяют линяют
линяет линяет
лирического лирического
лирическую лирическую
лирическое лирическое
лирической лирической
лирическим лирическим
лирическом лирическом
лирическом лирическом
лирического лирического
лирическим лирическим
лирическое лирическое
лирические лирические
ловкачей ловкачей
ref: ловкача pred: ловкач
ловкачам ловкачам
ловкачу ловкачу
ловкачах ловкачах
ловкаче ловкаче
ref: ловкачей pred: ловкачов
ловкача ловкача
ловкачами ловкачами
ref: ловкачи pred: ловкачы
ловкач ловкач
ref: лосося pred: лосось
лососю лососю
лососях лососях
лососе лососе
лососей лососей
лосося лосося
лососями лососями
лососем лососем
ref: лососи pred: лосось
лосось лосось
маршрутного маршрутного
маршрутных маршрутных
маршрутной маршрутной
маршрутном маршрутном
маршрутных маршрутных
маршрутного маршрутного
маршрутных маршрутных
маршрутной маршрутной
маршрутная маршрутная
маршрутное маршрутное
машинный перевод машинный перевод
машинным переводам машинным переводам
машинному переводу машинному переводу
машинных переводах машинных переводах
машинном переводе машинном переводе
машинных переводов машинных переводов
машинного перевода машинного перевода
машинными переводами машинными переводами
машинным переводом машинным переводом
машинные переводы машинные переводы
машинный перевод машинный перевод
междоусобия междоусобия
междоусобие междоусобие
междоусобию междоусобию
междоусобиях междоусобиях
междоусобии междоусобии
междоусобий междоусобий
междоусобия междоусобия
междоусобиями междоусобиями
междоусобием междоусобием
междоусобия междоусобия
миссионерских миссионерских
миссионерскую миссионерскую
миссионерское миссионерское
миссионерскому миссионерскому
миссионерскому миссионерскому
миссионерской миссионерской
миссионерской миссионерской
миссионерских миссионерских
миссионерским миссионерским
миссионерскими миссионерскими
миссионерские миссионерские
мозжечкам мозжечкам

мозжечку мозжечку
мозжечках мозжечках
мозжечке мозжечке
ref: мозжечков pred: мозжечок
мозжечка мозжечка
мозжечками мозжечками
мозжечком мозжечком
мозжечки мозжечки
мозжечок мозжечок
мудрую мудрую
мудрый мудрый
мудрое мудрое
мудром мудром
мудрых мудрых
мудрой мудрой
мудрого мудрого
мудрых мудрых
надлежать надлежать
ref: надлежит pred: надлежает
надлежало надлежало
непредсказуемых непредсказуемых
непредсказуемую непредсказуемую
непредсказуемому непредсказуемому
непредсказуемому непредсказуемому
непредсказуемом непредсказуемом
непредсказуемом непредсказуемом
непредсказуемого непредсказуемого
непредсказуемыми непредсказуемыми
ref: непредсказуемо pred: непредсказуем
непредсказуемое непредсказуемое
одолевающий одолевающий
одолевавший одолевавший
будем одолевать будем одолевать
будут одолевать будут одолевать
одолевать одолевать
одолеваем одолеваем
одолеваю одолеваю
одолеваешь одолеваешь
одолевают одолевают
одолевает одолевает
одолевали одолевали
океанских океанских
океанский океанский
океанское океанское
океанской океанской
океанских океанских
океанской океанской
океанской океанской
океанскими океанскими
океанские океанские
орбитальную орбитальную
орбитальному орбитальному
орбитальных орбитальных
орбитальной орбитальной
орбитального орбитального
орбитальных орбитальных
орбитальным орбитальным
орбитальная орбитальная
орбитальное орбитальное
орбитальные орбитальные
оспаривая оспаривая
оспаривав оспаривав
оспаривающий оспаривающий
будем оспаривать будем оспаривать
будете оспаривать будете оспаривать
будешь оспаривать будешь оспаривать
оспаривать оспаривать
оспариваю оспариваю
оспаривали оспаривали
оспаривал оспаривал
оспаривало оспаривало
ref: отдыхающего pred: отдыхающий
отдыхающему отдыхающему
отдыхающем отдыхающем
отдыхающего отдыхающего
отдыхающим отдыхающим
отдыхающий отдыхающий
будем отключаться будем отключаться
будете отключаться будете отключаться
будешь отключаться будешь отключаться
будут отключаться будут отключаться
отключайся отключайся
отключаемся отключаемся
отключаешься отключаешься
отключаются отключаются
отключается отключается
отключались отключались
отключался отключался
отравимся отравимся
ref: отравлюсь pred: отравюсь
отравитесь отравитесь
отравишься отравишься
отравятся отравятся
отравится отравится
ref: отравитесь pred: отравьтесь
отравились отравились
отравилась отравилась
отравился отравился
отравилось отравилось
отрегулировавшись отрегулировавшись
отрегулировавшийся отрегулировавшийся
ref: отрегулируемся pred: будем отрегулироваться
ref: отрегулируетесь pred: будете отрегулироваться
ref: отрегулируешься pred: будешь отрегулироваться
ref: отрегулируются pred: будут отрегулироваться
ref: отрегулируется pred: будет отрегулироваться
отрегулироваться отрегулироваться
отрегулировались отрегулировались
отрегулировалась отрегулировалась
отрегулировалось отрегулировалось
отряхнувшись отряхнувшись
отряхнетесь отряхнетесь
отряхнешься отряхнешься
отряхнется отряхнется
отряхнитесь отряхнитесь
отряхнись отряхнись
отряхнуться отряхнуться
ref: отряхнулись pred: отряхлись
ref: отряхнулась pred: отряхлась
отряхнулся отряхнулся
ref: отряхнулось pred: отряхлось
отсняв отсняв
отснявший отснявший
ref: отснятый pred: отсняемый
ref: отснимем pred: будем отснять
ref: отснимете pred: будете отснять
ref: отснимешь pred: будешь отснять
ref: отснимут pred: будут отснять
ref: отснимите pred: отсняйте
ref: отсними pred: отсняй
отсняла отсняла
отыгрывая отыгрывая
отыгрывав отыгрывав
отыгрывающий отыгрывающий
буду отыгрывать буду отыгрывать
будет отыгрывать будет отыгрывать
отыгрывай отыгрывай
отыгрываем отыгрываем
отыгрывает отыгрывает
отыгрывала отыгрывала
отыгрывал отыгрывал
пантеизмы пантеизмы
пантеизм пантеизм
пантеизму пантеизму
пантеизмах пантеизмах
пантеизме пантеизме
пантеизмов пантеизмов
пантеизма пантеизма
пантеизмами пантеизмами
пантеизмом пантеизмом
пантеизмы пантеизмы
пантеизм пантеизм
пассивный пассивный
пассивные пассивные
пассивному пассивному
пассивна пассивна
пассивного пассивного
пассивного пассивного
пассивным пассивным
пассивными пассивными
пассивный пассивный
пассивное пассивное
пассивны пассивны
передумывав передумывав
передумываемый передумываемый
будешь передумывать будешь передумывать
будет передумывать будет передумывать
передумываем передумываем
передумываете передумываете
передумываешь передумываешь
передумывает передумывает
передумывало передумывало
переменяясь переменяясь
переменявшись переменявшись
переменявшийся переменявшийся
будете переменяться будете переменяться
будут переменяться будут переменяться
будет переменяться будет переменяться
переменяйся переменяйся
переменяться переменяться
переменяемся переменяемся
переменяются переменяются
переработав переработав
ref: переработаю pred: буду переработать
ref: переработаете pred: будете переработать
ref: переработаешь pred: будешь переработать
ref: переработают pred: будут переработать
ref: переработает pred: будет переработать
переработайте переработайте
переработай переработай
переработали переработали
переработала переработала
переработало переработало
планетарные туманности планетарные туманности
планетарную туманность планетарную туманность
планетарным туманностям планетарным туманностям
планетарной туманности планетарной туманности
планетарных туманностей планетарных туманностей
планетарной туманности планетарной туманности
планетарными туманностями планетарными туманностями
планетарной туманностью планетарной туманностью
планетарные туманности планетарные туманности
планетарная туманность планетарная туманность
пластины пластины
пластину пластину
пластинам пластинам
пластине пластине
пластинах пластинах
пластин пластин
пластины пластины
пластинами пластинами
пластины пластины
пластина пластина
плевальницы плевальницы
плевальницу плевальницу
плевальницах плевальницах
плевальнице плевальнице
плевальниц плевальниц
плевальницы плевальницы
плевальницами плевальницами
ref: плевальницей pred: плевальницой
плевальницы плевальницы
плевальница плевальница
плеснувший плеснувший
ref: плеснем pred: будем плеснуть
плеснешь плеснешь
плеснет плеснет
плесните плесните
плесни плесни
плеснуть плеснуть
плеснули плеснули
плеснула плеснула
плеснул плеснул
плеснуло плеснуло
позорного позорного
позорную позорную
позорное позорное
позорном позорном
позорном позорном
позорных позорных
позорного позорного
позорной позорной
позорен позорен
показательного показательного
показательных показательных
показательную показательную
показательный показательный
показательному показательному
показательном показательном
показательной показательной
показательный показательный
показательное показательное
показательные показательные
полдни полдни
ref: полдням pred: полдне
ref: полднях pred: полдне
ref: полдён pred: полдни
ref: полднями pred: полднем
полдни полдни
потакая потакая
потакавший потакавший
буду потакать буду потакать
потакай потакай
потакать потакать
потакаем потакаем
потакаю потакаю
потакают потакают
потакает потакает
потакали потакали
потакала потакала
ref: предводителей pred: предводители
ref: предводителя pred: предводитель
предводителям предводителям
предводителю предводителю
предводителе предводителе
предводителей предводителей
предводителя предводителя
предводителями предводителями
предводителем предводителем
предводители предводители
предводитель предводитель
прибалтийских прибалтийских
прибалтийскую прибалтийскую
прибалтийское прибалтийское
прибалтийскому прибалтийскому
прибалтийскому прибалтийскому
прибалтийским прибалтийским
прибалтийском прибалтийском
прибалтийских прибалтийских
прибалтийским прибалтийским
прибалтийскими прибалтийскими
проронивший проронивший
пророню пророню
пророните пророните
проронит проронит
пророните пророните
проронить проронить
проронили проронили
проронила проронила
проронило проронило
противостояние противостояние
противостояниям противостояниям
противостоянию противостоянию
противостояниях противостояниях
противостояний противостояний
противостояния противостояния
противостояниями противостояниями
противостоянием противостоянием
противостояния противостояния
противостояние противостояние
пуховых пуховых
пуховый пуховый
пуховое пуховое
пуховому пуховому
пуховом пуховом
пуховых пуховых
пухового пухового
пуховым пуховым
пуховыми пуховыми
пуховая пуховая
пуховые пуховые

разбазарив разбазарив
разбазаривший разбазаривший
разбазаренный разбазаренный
разбазарю разбазарю
разбазаришь разбазаришь
разбазарят разбазарят
ref: разбазарьте pred: разбазарите
разбазарили разбазарили
разбазарила разбазарила
разваливаясь разваливаясь
разваливавшись разваливавшись
будете разваливаться будете разваливаться
будешь разваливаться будешь разваливаться
будут разваливаться будут разваливаться
разваливайся разваливайся
разваливаться разваливаться
разваливаемся разваливаемся
разваливаетесь разваливаетесь
разваливаешься разваливаешься
разваливалась разваливалась
резюмируя резюмируя
резюмировав резюмировав
ref: резюмированный pred: резюмируемый
будем резюмировать будем резюмировать
будут резюмировать будут резюмировать
резюмируем резюмируем
резюмирую резюмирую
резюмируете резюмируете
резюмируют резюмируют
резюмирует резюмирует
резюмировал резюмировал
речников речников
ref: речника pred: речник
речникам речникам
речнику речнику
речнике речнике
речников речников
речника речника
речниками речниками
речником речником
речники речники
речник речник
рявкая рявкая
рявкав рявкав
рявкающий рявкающий
рявкавший рявкавший
рявкай рявкай
рявкать рявкать
рявкаем рявкаем
рявкаешь рявкаешь
рявкает рявкает
рявкали рявкали
рявкал рявкал
сжигание сжигание
сжиганию сжиганию
сжигании сжигании
сжигания сжигания
сжиганием сжиганием
сжигание сжигание
сосудистого сосудистого
сосудистый сосудистый
сосудистые сосудистые
сосудистой сосудистой
сосудистым сосудистым
сосудистой сосудистой
сосудистых сосудистых
сосудистой сосудистой
сосудистых сосудистых
сосудистая сосудистая
сосудистое сосудистое
спрыгнем спрыгнем
спрыгну спрыгну
спрыгнете спрыгнете
спрыгнешь спрыгнешь
спрыгнут спрыгнут
спрыгни спрыгни
спрыгнули спрыгнули
спрыгнула спрыгнула
спрыгнуло спрыгнуло
среднемесячную среднемесячную
среднемесячный среднемесячный
среднемесячные среднемесячные
среднемесячной среднемесячной
среднемесячном среднемесячном
среднемесячных среднемесячных
среднемесячного среднемесячного
среднемесячным среднемесячным
среднемесячный среднемесячный
среднемесячные среднемесячные
стиральную машину стиральную машину
стиральным машинам стиральным машинам
стиральной машине стиральной машине
стиральных машинах стиральных машинах
стиральной машине стиральной машине
стиральных машин стиральных машин
стиральной машины стиральной машины
стиральными машинами стиральными машинами
стиральной машиной стиральной машиной
стиральные машины стиральные машины
стиральная машина стиральная машина
строительских строительских
строительскую строительскую
строительские строительские
строительскому строительскому
строительскому строительскому
строительской строительской
строительском строительском
строительских строительских
строительского строительского
строительского строительского
строительским строительским
ref: тартрат диэтиламида лизергиновой кислоты pred: тартрат диэтиламиды лизерг
ref: тартрате диэтиламида лизергиновой кислоты pred: тартрате диэтиламидовой ки
ref: тартрата диэтиламида лизергиновой кислоты pred: тартрата диэтиламиды лизер
ref: тартратом диэтиламида лизергиновой кислоты pred: тартратом диэтиламидой лиз
ref: тартрат диэтиламида лизергиновой кислоты pred: тартрат диэтиламида лизерг
терабайты терабайты
терабайт терабайт
терабайтам терабайтам
терабайтах терабайтах
терабайте терабайте
терабайтов терабайтов
терабайта терабайта
терабайтами терабайтами
терабайтом терабайтом
терабайты терабайты
терабайт терабайт
тоннели тоннели
тоннель тоннель
тоннелям тоннелям
тоннелю тоннелю
тоннелях тоннелях
тоннеле тоннеле
тоннелей тоннелей
тоннелями тоннелями
тоннелем тоннелем
тоннели тоннели
тоннель тоннель
трудолюбия трудолюбия
трудолюбие трудолюбие
трудолюбиям трудолюбиям
трудолюбию трудолюбию
трудолюбиях трудолюбиях
трудолюбии трудолюбии
трудолюбий трудолюбий
трудолюбия трудолюбия
трудолюбиями трудолюбиями
трудолюбием трудолюбием
трудолюбие трудолюбие
тряпьё тряпьё
тряпью тряпью
тряпье тряпье
тряпья тряпья
ref: тряпьём pred: тряпьем
тряпьё тряпьё
ref: тётю pred: тётя
тётям тётям
ref: тёте pred: тётю
тётях тётях
ref: тёть pred: тётей
ref: тёти pred: тётя
тётями тётями
ref: тётей pred: тётям
ref: тёти pred: тётят
тётя тётя
уголовно-процессуального уголовно-процессуального
уголовно-процессуальных уголовно-процессуальных
уголовно-процессуальному уголовно-процессуальному
уголовно-процессуальной уголовно-процессуальной
уголовно-процессуальном уголовно-процессуальном
уголовно-процессуальных уголовно-процессуальных
уголовно-процессуальной уголовно-процессуальной
уголовно-процессуальной уголовно-процессуальной
уголовно-процессуальными уголовно-процессуальными
узкоколейной узкоколейной
узкоколейной узкоколейной
узкоколейна узкоколейна
узкоколейной узкоколейной
узкоколейного узкоколейного
узкоколейной узкоколейной
узкоколейно узкоколейно
узкоколейные узкоколейные
узкоколейны узкоколейны
узурпирования узурпирования
узурпирование узурпирование
узурпированию узурпированию
узурпированиях узурпированиях
узурпировании узурпировании
узурпирований узурпирований
узурпирования узурпирования
узурпированиями узурпированиями
узурпированием узурпированием
узурпирования узурпирования
узурпирование узурпирование
устоявшись устоявшись
устоявшийся устоявшийся
ref: устоимся pred: будем устояться
ref: устоюсь pred: буду устояться
устоитесь устоитесь
ref: устоятся pred: будут устояться
ref: устоится pred: будет устояться
устояться устояться
устоялись устоялись
устоялась устоялась
устоялся устоялся
ref: файлики pred: файликов
файлик файлик
файликам файликам
файлику файлику
файлике файлике
файликов файликов
файлика файлика
файликами файликами
файликом файликом
файлики файлики
файлик файлик
форматы форматы
формат формат
форматам форматам
формату формату
форматах форматах
форматов форматов
формата формата
форматы форматы
формат формат
форумы форумы
форум форум
форумам форумам
форуму форуму
форумах форумах
форуме форуме
форума форума
форумами форумами
форумом форумом
форумы форумы
хватившись хватившись
хватившийся хватившийся
ref: хватимся pred: будем хватиться
ref: хвачусь pred: буду хватиться
ref: хватитесь pred: будете хватиться
ref: хватятся pred: будут хватиться
хватитесь хватитесь
хватись хватись
хватились хватились
хватился хватился
хватилось хватилось
церковнославянский церковнославянский
церковнославянские церковнославянские
церковнославянской церковнославянской
церковнославянскому церковнославянскому
церковнославянским церковнославянским
церковнославянской церковнославянской
церковнославянских церковнославянских
церковнославянских церковнославянских
церковнославянской церковнославянской
церковнославянская церковнославянская
церковнославянский церковнославянский
цикл цикл
циклам циклам
циклу циклу
циклах циклах
цикле цикле
циклов циклов
цикла цикла
циклами циклами
циклы циклы
цикл цикл
ref: цыпочек pred: цыпочки
цыпочку цыпочку
цыпочкам цыпочкам
ref: цыпочке pred: цыпочцы
цыпочке цыпочке
цыпочек цыпочек
цыпочки цыпочки
цыпочками цыпочками
цыпочкой цыпочкой
цыпочка цыпочка
черпнувший черпнувший
ref: черпнем pred: будем черпнуть
ref: черпну pred: буду черпнуть
черпнете черпнете
ref: черпнут pred: будут черпнуть
черпните черпните
черпнуть черпнуть
черпнули черпнули
черпнула черпнула
черпнул черпнул
черпнуло черпнуло
щурившийся щурившийся
будем щуриться будем щуриться
будете щуриться будете щуриться
будешь щуриться будешь щуриться
ref: щурься pred: щурись
щуриться щуриться
щуримся щуримся
щуритесь щуритесь
щуришься щуришься
щурились щурились
щурилось щурилось
экшны экшны
экшн экшн
экшнам экшнам
экшну экшну
экшнах экшнах
экшнов экшнов
экшна экшна
экшнами экшнами
экшном экшном
экшны экшны
экшн экшн
0.919
livles/slavic-distant-word-or-family
test file:  ../preprocessing/preprocessing_to_json/data/bel-lang-word_tst.json
ref: абвінавацім pred: будзем абвінава́ціць
ref: абвінавачу pred: буду абвінава́ціць
ref: абвінаваціце pred: будзеце абвінава́ціць
ref: абвінаваціш pred: будзеш абвінава́ціць
ref: абвінавацяць pred: будуць абвінава́ціць
ref: абвінаваціць pred: будзе абвінава́ціць
абвінавацьце абвінавацьце
ref: абвінаваць pred: абвінаваці
абвінавацілі абвінавацілі
абвінаваціла абвінаваціла
абцугі абцугі
ref: абцугам pred: абцугім
ref: абцугах pred: абцугі
ref: абцугоў pred: абцугі
ref: абцугамі pred: абцугім
абцугі абцугі
аптэкарак аптэкарак

аптэкаркам аптэкаркам
аптэкарцы аптэкарцы
аптэкарках аптэкарках
аптэкарцы аптэкарцы
аптэкарак аптэкарак
аптэкаркамі аптэкаркамі
аптэкаркай аптэкаркай
аптэкаркі аптэкаркі
аптэкарка аптэкарка
аўстрыйцаў аўстрыйцаў
аўстрыйца аўстрыйца
ref: аўстрыйцам pred: аўстрыяцам
аўстрыйцу аўстрыйцу
ref: аўстрыйцах pred: аўстрыяцах
аўстрыйцу аўстрыйцу
аўстрыйцаў аўстрыйцаў
аўстрыйца аўстрыйца
ref: аўстрыйцамі pred: аўстрыяцамі
аўстрыйцам аўстрыйцам
аўстрыец аўстрыец
аўтобус аўтобус
аўтобусам аўтобусам
аўтобусу аўтобусу
аўтобусах аўтобусах
аўтобусе аўтобусе
ref: аўтобусай pred: аўтобусаў
аўтобуса аўтобуса
аўтобусамі аўтобусамі
аўтобусам аўтобусам
аўтобус аўтобус
аўторкам аўторкам
аўторку аўторку
аўторках аўторках
аўторку аўторку
ref: аўторкаў pred: аўторакаў
аўторка аўторка
аўторкамі аўторкамі
аўторкам аўторкам
аўторкі аўторкі
аўторак аўторак
бараду бараду
ref: бародам pred: барадам
барадзе барадзе
ref: бародах pred: барадах
барадзе барадзе
ref: барод pred: барад
барады барады
ref: бародамі pred: барадамі
ref: барадой pred: барадай
ref: бароды pred: барады
барада барада
бельгійцаў бельгійцаў
бельгійца бельгійца
бельгійцам бельгійцам
бельгійцу бельгійцу
бельгійцу бельгійцу
бельгійцаў бельгійцаў
бельгійца бельгійца
бельгійцамі бельгійцамі
бельгійцам бельгійцам
бельгійцы бельгійцы
ref: бельгіец pred: бельгійц
бутэлькі бутэлькі
бутэльку бутэльку
бутэлькам бутэлькам
бутэльцы бутэльцы
бутэльках бутэльках
бутэлек бутэлек
бутэлькі бутэлькі
бутэлькай бутэлькай
бутэлькі бутэлькі
бядро бядро
ref: бёдрам pred: бядрам
бядру бядру
ref: бёдрах pred: бядрах
бядры бядры
ref: бёдзер pred: бядраў
бядра бядра
ref: бёдрамі pred: бядрамі
ref: бядром pred: бядрам
ref: бёдры pred: бядры
бядро бядро
важную важную
важны важны
важныя важныя
важнае важнае
важнай важнай
важнаму важнаму
важнаму важнаму
важным важным
важным важным
важных важных
важная важная
ref: венграў pred: венгры
ref: венгра pred: венгр
венграм венграм
венграх венграх
ref: венгру pred: венгры
венграў венграў
венгра венгра
венграмі венграмі
венгры венгры
венгр венгр
ref: воблакі pred: воблак
воблакам воблакам
ref: воблаку pred: воблацы
воблаках воблаках
ref: воблаку pred: воблацы
ref: воблакаў pred: воблак
ref: воблака pred: воблакі
ref: воблакам pred: воблакай
воблакі воблакі
воблака воблака
ref: астравы pred: востраўі
востраў востраў
ref: астравом pred: востраўам
ref: востраву pred: востраўу
ref: астравох pred: востраўах
ref: востраве pred: вострэўе
ref: астравоў pred: востраў
ref: вострава pred: востраўа
ref: астравомі pred: востраўамі
ref: астравы pred: востраўы
востраў востраў
ref: вуллі pred: вулі
вулей вулей
ref: вуллям pred: вуляям
ref: вуллю pred: вулю
ref: вуллях pred: вулях
ref: вуллі pred: вулее
ref: вуллёў pred: вулей
ref: вулля pred: вуляя
ref: вуллямі pred: вулямі
ref: вуллём pred: вулеем
вулей вулей
вуліцы вуліцы
вуліцу вуліцу
вуліцам вуліцам
вуліцы вуліцы
вуліцах вуліцах
вуліцы вуліцы
ref: вуліцаў pred: вуліц
вуліцы вуліцы
вуліцамі вуліцамі
вуліцай вуліцай
вуліцы вуліцы
ref: вушы pred: вухі
ref: вушам pred: вухам
ref: вуху pred: вухе
ref: вушах pred: вухах
ref: вуху pred: вухе
ref: вуха pred: вухі
ref: вушамі pred: вухамі
ref: вухам pred: вухай
ref: вушы pred: вухі
вуха вуха
выбары выбары
выбарам выбарам
ref: выбараў pred: выбары
ref: выбарамі pred: выбарам
выбары выбары
высокіх высокіх
высокую высокую
высокае высокае
высокаму высокаму
высокаму высокаму
высокім высокім
высокай высокай
высокіх высокіх
высокім высокім
высокае высокае
ref: выхавальніц pred: выхавальніцы
выхавальніцу выхавальніцу
выхавальніцам выхавальніцам
выхавальніцы выхавальніцы
выхавальніцах выхавальніцах
выхавальніц выхавальніц
выхавальніцы выхавальніцы
выхавальніцамі выхавальніцамі
выхавальніцай выхавальніцай
выхавальніцы выхавальніцы
выхавальніца выхавальніца
ref: буду вячэ́раць pred: буду вячэра́ць
ref: будзеце вячэ́раць pred: будзеце вячэра́ць
ref: будзеш вячэ́раць pred: будзеш вячэра́ць
вячэрайце вячэрайце
вячэрай вячэрай
вячэраеце вячэраеце
вячэраеш вячэраеш
вячэраюць вячэраюць
вячэрае вячэрае
вячэралі вячэралі
вячэраў вячэраў
ref: буду гавары́ць pred: буду гава́рыць
ref: будзеш гавары́ць pred: будзеш гава́рыць
ref: будуць гавары́ць pred: будуць гава́рыць
ref: будзе гавары́ць pred: будзе гава́рыць
гаварыце гаварыце
ref: гаворым pred: гаварым
гавару гавару
ref: гаворыш pred: гаварыш
ref: гавораць pred: гаварыць
галодны галодны
галодныя галодныя
галоднай галоднай
галодным галодным
галодным галодным
галоднага галоднага
галодных галодных
галодным галодным
галодны галодны
галодныя галодныя
будзем гарэ́ць будзем гарэ́ць
будзеце гарэ́ць будзеце гарэ́ць
будзеш гарэ́ць будзеш гарэ́ць
будзе гарэ́ць будзе гарэ́ць
гары гары
гару гару
ref: гараць pred: гарэюць
ref: гарыць pred: гарэе
гарэлі гарэлі
гарэла гарэла
ref: гарады pred: горады
горад горад
ref: гарадам pred: горадам
гораду гораду
горадзе горадзе
ref: гарадоў pred: горадаў
горада горада
ref: гарадамі pred: горадамі
горадам горадам
ref: гарады pred: горады
горад горад
грабы грабы
граб граб
грабам грабам
грабу грабу
грабе грабе
грабаў грабаў
граба граба
грабамі грабамі
грабам грабам
грабы грабы
граб граб
грачанак грачанак
грачанку грачанку
грачанцы грачанцы
грачанках грачанках
грачанкі грачанкі
грачанкамі грачанкамі
грачанкай грачанкай
грачанкі грачанкі
грачанка грачанка
грывы грывы
грыву грыву
грывам грывам
грывах грывах
грыве грыве
ref: грыў pred: грыв
грывы грывы
грывамі грывамі
грывай грывай
грывы грывы
грыва грыва
ref: грэкаў pred: грэкі
ref: грэка pred: грэк
грэкам грэкам
грэку грэку
грэках грэках
ref: грэку pred: грэцы
грэкаў грэкаў
грэка грэка
грэкамі грэкамі
грэкам грэкам
грэк грэк
далоні далоні
далонь далонь
далоням далоням
ref: далоні pred: далоню
далоні далоні
ref: далоней pred: далоняў
далоні далоні
далонямі далонямі
ref: далонню pred: далонём
далоні далоні
далонь далонь
будзеце дары́ць будзеце дары́ць
будзеш дары́ць будзеш дары́ць
будуць дары́ць будуць дары́ць
будзе дары́ць будзе дары́ць
дарыце дарыце
дары дары
ref: дорым pred: дарым
ref: дорыце pred: дарыце
ref: дораць pred: дарыць
ref: дорыць pred: дарыць
дарылі дарылі
будзем дастава́ць будзем дастава́ць
буду дастава́ць буду дастава́ць
будзеш дастава́ць будзеш дастава́ць
ref: даставай pred: дастуй
ref: дастаю pred: дастую
ref: дастаеце pred: дастуеце
ref: дастаеш pred: дастуеш
ref: дастаюць pred: дастуюць
ref: дастае pred: дастуе
даставала даставала
дастанем дастанем
дастану дастану
дастанеш дастанеш
дастануць дастануць
дастане дастане
дастаньце дастаньце
дастань дастань
дасталі дасталі
дастала дастала
дастаў дастаў
дастала дастала
ref: дасягнём pred: дасягнем
дасягну дасягну
дасягнеце дасягнеце
дасягнеш дасягнеш
дасягнуць дасягнуць
дасягніце дасягніце
дасягні дасягні
дасягнулі дасягнулі
дасягнуў дасягнуў
дасягнула дасягнула
дзевятнаццатага дзевятнаццатага
дзевятнаццатую дзевятнаццатую
дзевятнаццаты дзевятнаццаты
дзевятнаццатым дзевятнаццатым
дзевятнаццатага дзевятнаццатага
дзевятнаццатых дзевятнаццатых
дзевятнаццатаю дзевятнаццатаю
дзевятнаццатым дзевятнаццатым
дзевятнаццатымі дзевятнаццатымі
ref: дні pred: дзянёў
дзень дзень
ref: днях pred: дзянях
ref: дні pred: дзяні
ref: дзён pred: дзянёў
ref: дня pred: дзяня
ref: днямі pred: дзянямі
ref: днём pred: дзенём
ref: дні pred: дзяні
дзень дзень
будзем забыва́ць будзем забыва́ць
будзеш забыва́ць будзеш забыва́ць
будуць забыва́ць будуць забыва́ць
будзе забыва́ць будзе забыва́ць
забывай забывай
забываем забываем
забываю забываю
забывалі забывалі
забывала забывала
забываў забываў
будзеш забіва́ць будзеш забіва́ць
будзе забіва́ць будзе забіва́ць
забівай забівай
забіваем забіваем
забіваеце забіваеце
забіваеш забіваеш
забіваюць забіваюць
забівае забівае
забівалі забівалі
забівала забівала
захад захад
захаду захаду
захадзе захадзе
захаду захаду
захадам захадам
захад захад
зачынім зачынім
зачыніце зачыніце
зачыняць зачыняць
зачыніць зачыніць
зачыніце зачыніце
зачыні зачыні
зачынілі зачынілі
зачыніла зачыніла
зачыніў зачыніў
зачыніла зачыніла
зморанага зморанага
зморанай зморанай
зморанаму зморанаму
зморанаму зморанаму
змораных змораных
зморанага зморанага
зморанага зморанага
змораных змораных
змораная змораная
зморанае зморанае
ref: землі pred: зямлі
зямлю зямлю
ref: землям pred: зямлям
ref: зямлі pred: зямлю
ref: землях pred: зямлях
зямлі зямлі
ref: земляў pred: зямлей
зямлі зямлі
ref: землямі pred: зямлямі

зімы зімы
зіму зіму
зімам зімам
зімах зімах
зіме зіме
зім зім
зімамі зімамі
ref: зімой pred: зімай
зімы зімы
зіма зіма
ref: каралёў pred: карлі
ref: караля pred: кароль
ref: каралям pred: карлям
ref: каралю pred: карлю
ref: каралях pred: карлях
ref: карале pred: карлі
ref: каралёў pred: карлей
ref: караля pred: карля
ref: каралям pred: карлём
ref: каралі pred: карлі
кароль кароль
будзем лама́ць будзем лама́ць
будзеце лама́ць будзеце лама́ць
будуць лама́ць будуць лама́ць
ref: ламі pred: ламай
ref: ломім pred: ламаем
ref: ламлю pred: ламаю
ref: ломіце pred: ламаеце
ref: ломіш pred: ламаеш
ref: ломяць pred: ламаюць
ламала ламала
ref: льва pred: леў
ref: львам pred: ляўам
ref: льву pred: ляўу
ref: львоў pred: ляў
ref: льва pred: ляўа
ref: львамі pred: ляўмі
леў леў
лужыцкія лужыцкія
лужыцкай лужыцкай
лужыцкіх лужыцкіх
лужыцкай лужыцкай
лужыцкага лужыцкага
лужыцкіх лужыцкіх
лужыцкаю лужыцкаю
лужыцкім лужыцкім
лужыцкімі лужыцкімі
лужыцкі лужыцкі
ліпеньскага ліпеньскага
ліпеньскія ліпеньскія
ліпеньскай ліпеньскай
ліпеньскім ліпеньскім
ліпеньскім ліпеньскім
ліпеньскага ліпеньскага
ліпеньскаю ліпеньскаю
ліпеньскі ліпеньскі
месяцы месяцы
месяц месяц
месяцам месяцам
месяцу месяцу
ref: месяцы pred: месяцу
месяца месяца
месяцамі месяцамі
месяцам месяцам
месяцы месяцы
месяц месяц
молаты молаты
молат молат
молатам молатам
молату молату
молатах молатах
молаце молаце
молатаў молатаў
молата молата
молатамі молатамі
молатам молатам
молаты молаты
ref: надвор’е pred: надвор'е
ref: надвор’ю pred: надвор'ю
ref: надвор’і pred: надвор'і
ref: надвор’я pred: надвор'я
ref: надвор’ем pred: надвор'ем
ref: надвор’е pred: надвор'е
ref: немак pred: немкі
немку немку
немкам немкам
немцы немцы
немках немках
немцы немцы
немкі немкі
немкай немкай
немкі немкі
немка немка
нажы нажы
нож нож
нажам нажам
ref: нажы pred: ножу
нажах нажах
ref: нажы pred: ножы
ref: нажамi pred: нажамі
ref: нажом pred: ножам
нажы нажы
нож нож
ref: нядзелі pred: нядзялі
нядзелю нядзелю
ref: нядзелям pred: нядзялям
ref: нядзелі pred: нядзелю
нядзелі нядзелі
ref: нядзель pred: нядзялёў
нядзелі нядзелі
ref: нядзелямі pred: нядзялямі
нядзеляй нядзеляй
ref: нядзелі pred: нядзялі
нядзеля нядзеля
пакурым пакурым
пакурыце пакурыце
пакурыш пакурыш
ref: пакураць pred: пакурыць
пакурыць пакурыць
пакуры пакуры
пакурылі пакурылі
пакурыла пакурыла
пакурыў пакурыў
пакурыла пакурыла
будзеце памята́ць будзеце памята́ць
будзеш памята́ць будзеш памята́ць
будзе памята́ць будзе памята́ць
памятаю памятаю
памятаеце памятаеце
памятаеш памятаеш
памятаюць памятаюць
памятае памятае
памятала памятала
памятала памятала
будзем паміна́ць будзем паміна́ць
будзеце паміна́ць будзеце паміна́ць
будзеш паміна́ць будзеш паміна́ць
будзе паміна́ць будзе паміна́ць
памінайце памінайце
памінай памінай
памінаю памінаю
памінаеце памінаеце
памінаюць памінаюць
памінае памінае
памінаў памінаў
паражэнні паражэнні
паражэнне паражэнне
паражэнню паражэнню
паражэнні паражэнні
паражэнняў паражэнняў
паражэння паражэння
паражэннямі паражэннямі
паражэнні паражэнні
паражэнне паражэнне
ref: паспрачаемся pred: будзем паспрача́цца
паспрачаюся паспрачаюся
паспрачаецеся паспрачаецеся
паспрачаешся паспрачаешся
паспрачаюцца паспрачаюцца
паспрачайцеся паспрачайцеся
паспрачайся паспрачайся
паспрачаліся паспрачаліся
паспрачалася паспрачалася
паспрачаўся паспрачаўся
паспрачалася паспрачалася
ref: пачысцім pred: будзем пачы́сціць
ref: пачышчу pred: пачышу
пачысціце пачысціце
ref: пачысціш pred: будзеш пачы́сціць
пачысцяць пачысцяць
пачысціць пачысціць
пачысціце пачысціце
пачысці пачысці
пачысцілі пачысцілі
пачысціла пачысціла
пачысціў пачысціў
печы печы
печ печ
печам печам
печы печы
печах печах
печы печы
ref: печы pred: печа
печамі печамі
ref: печчу pred: печам
печы печы
печ печ
будзем прадава́ць будзем прадава́ць
буду прадава́ць буду прадава́ць
будуць прадава́ць будуць прадава́ць
будзе прадава́ць будзе прадава́ць
ref: прадаём pred: прадуем
ref: прадаюць pred: прадуюць
ref: прадае pred: прадуе
прадавала прадавала
прадаваў прадаваў
прадавала прадавала
ref: прамоўцаў pred: прамоўцы
прамоўцам прамоўцам
ref: прамоўцу pred: прамоўцы
прамоўцах прамоўцах
ref: прамоўцу pred: прамоўцы
ref: прамоўцаў pred: прамоўц
прамоўцы прамоўцы
прамоўцамі прамоўцамі
ref: прамоўцам pred: прамоўцай
прамоўцы прамоўцы
прамоўца прамоўца
прыгожага прыгожага
прыгожую прыгожую
прыгожыя прыгожыя
прыгожай прыгожай
прыгожым прыгожым
прыгожых прыгожых
прыгожай прыгожай
прыгожых прыгожых
прыгожым прыгожым
прыгожым прыгожым
прыгожая прыгожая
прыйдзем прыйдзем
прыйду прыйду
прыйдзеце прыйдзеце
прыйдзеш прыйдзеш
прыйдуць прыйдуць
ref: прыйдзець pred: прыйдзе
ref: прыйдзіце pred: прыйдзьце
ref: прыйдзі pred: прыйдзь
прыйшлі прыйшлі
прыйшла прыйшла
прыйшоў прыйшоў
ref: пякарні pred: пякарни
пякарню пякарню
ref: пякарні pred: пякарне
пякарнях пякарнях
пякарні пякарні
ref: пякарань pred: пякарней
пякарні пякарні
пякарнямі пякарнямі
пякарняй пякарняй
пякарні пякарні
пякарня пякарня
пятнаццатую пятнаццатую
пятнаццаты пятнаццаты
пятнаццатыя пятнаццатыя
пятнаццатаму пятнаццатаму
пятнаццатаму пятнаццатаму
пятнаццатых пятнаццатых
пятнаццатага пятнаццатага
пятнаццатаю пятнаццатаю
пятнаццатымі пятнаццатымі
пятнаццатае пятнаццатае
ref: будзеце пячы́ pred: будзеце пя́чыць
ref: будзеш пячы́ pred: будзеш пя́чыць
ref: будуць пячы́ pred: будуць пя́чыць
ref: будзе пячы́ pred: будзе пя́чыць
ref: пячом pred: пячам
ref: пяку pred: пячу
ref: печаце pred: пячыце
ref: пячэш pred: пячыш
пяклі пяклі
ref: пякла pred: пячала
ref: пякло pred: пячала
ref: разаб'ём pred: будзем разбі́ць
ref: разаб’ю pred: буду разбі́ць
ref: разаб'еш pred: будзеш разбі́ць
ref: разаб'е pred: будзе разбі́ць
разбіце разбіце
разбі разбі
разбілі разбілі
разбіла разбіла
разбіў разбіў
разбіла разбіла
разумнага разумнага
разумны разумны
разумныя разумныя
разумнаму разумнаму
разумным разумным
разумных разумных
разумнай разумнай
разумнымі разумнымі
разумная разумная
разумнае разумнае
разумныя разумныя
ref: сабяром pred: будзем сабра́ць
ref: сабяру pred: буду сабра́ць
ref: сабераце pred: будзеце сабра́ць
ref: сабярэш pred: будзеш сабра́ць
ref: сабяруць pred: будуць сабра́ць
ref: сабярэ pred: будзе сабра́ць
ref: сабярыце pred: сабрайце
сабралі сабралі
сабрала сабрала
сабраў сабраў
сабрала сабрала
ref: сярпы pred: серпы
серп серп
ref: сярпам pred: серпам
ref: сярпу pred: серпу
ref: сярпах pred: серпах
ref: сярпе pred: серпе
ref: сярпа pred: серпа
ref: сярпамі pred: серпамі
ref: сярпом pred: серпам
ref: сярпы pred: серпы
серп серп
слабага слабага
слабую слабую
слабы слабы
слабыя слабыя
ref: слабай pred: слабой
слабым слабым
ref: слабай pred: слабой
слабым слабым
слабаю слабаю
слабыя слабыя
ref: солі pred: саляў
соль соль
ref: солям pred: салям
солю солю
ref: солях pred: салях
солі солі
ref: соляў pred: салей
ref: солямі pred: салямі
ref: солем pred: солём
ref: солі pred: салі
соль соль
спакой спакой
ref: спакою pred: спаку
ref: спакоі pred: спаке
ref: спакою pred: спакі
ref: спакоем pred: спакам
спакой спакой
ref: будзем спаць pred: будзем спа́ць
буду спаць буду спаць
ref: будзеце спаць pred: будзеце спа́ць
ref: будуць спаць pred: будуць спа́ць
ref: спіце pred: спайце
ref: сплю pred: спаю
ref: спіце pred: спаеце
ref: спіць pred: спае
спалі спалі
спала спала
спала спала
ref: спытаю pred: буду спыта́ць
ref: спытаеш pred: будзеш спыта́ць
ref: спытаюць pred: будуць спыта́ць
ref: спытае pred: будзе спыта́ць
спытайце спытайце
спытай спытай
спыталі спыталі
спытала спытала
спытаў спытаў
спытала спытала
ref: спечаце pred: будзеце спя́чыць
ref: спячэш pred: будзеш спя́чыць
ref: спякуць pred: будуць спя́чыць
ref: спячэ pred: будзе спя́чыць
спячыце спячыце
спячы спячы
ref: спяклі pred: спялі
ref: спякла pred: спяла
ref: спякло pred: спяло
стомленых стомленых
стомленаму стомленаму
стомленаму стомленаму
стомленым стомленым
стомленай стомленай
стомленай стомленай
стомленаю стомленаю
стомленымі стомленымі
стомленая стомленая
стомленае стомленае
стрэлкі стрэлкі
стрэлку стрэлку
стрэлкам стрэлкам
стрэлцы стрэлцы
стрэлках стрэлках
стрэлцы стрэлцы
стрэлак стрэлак
стрэлкі стрэлкі
стрэлкамі стрэлкамі
стрэлкі стрэлкі
стрэлка стрэлка
сумкі сумкі
сумку сумку
сумкам сумкам
сумцы сумцы
сумках сумках
сумак сумак
сумкамі сумкамі
сумкай сумкай
сумкі сумкі
сумка сумка
сярэбранага сярэбранага
сярэбраны сярэбраны

сярэбранаму сярэбранаму
сярэбраным сярэбраным
сярэбранай сярэбранай
сярэбранага сярэбранага
сярэбранага сярэбранага
сярэбранаю сярэбранаю
сярэбраны сярэбраны
сярэбранае сярэбранае
сястру сястру
ref: сястры pred: сястре
ref: сёстрах pred: сястрах
ref: сястры pred: сястре
ref: сёстраў pred: сёстр
сястры сястры
ref: сёстрамі pred: сястрамі
ref: сястрой pred: сястрай
ref: сёстры pred: сястры
сястра сястра
сінюю сінюю
сіняму сіняму
сіняму сіняму
сінім сінім
сіняй сіняй
сінім сінім
сініх сініх
сінім сінім
сіні сіні
сінія сінія
трынаццатых трынаццатых
трынаццатую трынаццатую
трынаццаты трынаццаты
трынаццатаму трынаццатаму
трынаццатым трынаццатым
трынаццатага трынаццатага
трынаццатага трынаццатага
трынаццатаю трынаццатаю
трынаццатым трынаццатым
трынаццатымі трынаццатымі
трынаццаты трынаццаты
буду уніка́ць буду уніка́ць
будзеце уніка́ць будзеце уніка́ць
будуць уніка́ць будуць уніка́ць
будзе уніка́ць будзе уніка́ць
унікай унікай
унікаем унікаем
унікаю унікаю
унікаеце унікаеце
унікаюць унікаюць
унікае унікае
унікала унікала
устанем устанем
ref: устану pred: буду уста́ць
устанеце устанеце
устанеш устанеш
ref: устануць pred: будуць уста́ць
устаньце устаньце
устань устань
усталі усталі
устала устала
устала устала
усходніх усходніх
усходнюю усходнюю
усходні усходні
усходняе усходняе
усходнім усходнім
усходнім усходнім
усходнім усходнім
усходняга усходняга
усходняга усходняга
усходняю усходняю
ref: ухілімся pred: будзем ухілі́цца
ref: ухілюся pred: буду ухілі́цца
ref: ухіліцеся pred: будзеце ухілі́цца
ref: ухіляцца pred: будуць ухілі́цца
ref: ухіліцца pred: будзе ухілі́цца
ухіліцеся ухіліцеся
ухіліся ухіліся
ухілілася ухілілася
ухіліўся ухіліўся
ухілілася ухілілася
ref: цароў pred: цары
ref: цара pred: цар
царам царам
царах царах
ref: цару pred: цары
ref: цароў pred: цараў
цара цара
царамі царамі
ref: царом pred: царам
цары цары
цар цар
цэлай цэлай
цэламу цэламу
цэлым цэлым
цэлых цэлых
цэлай цэлай
цэлых цэлых
цэлым цэлым
цэлая цэлая
цэлы цэлы
цэлыя цэлыя
чыстага чыстага
чысты чысты
чыстай чыстай
чыстаму чыстаму
чыстым чыстым
чыстага чыстага
чыстага чыстага
чыстаю чыстаю
чысты чысты
чыстае чыстае
чыстыя чыстыя
шапку шапку
шапкам шапкам
шапцы шапцы
шапках шапках
шапцы шапцы
шапак шапак
шапкі шапкі
шапкамі шапкамі
шапкай шапкай
шапка шапка
шахматы шахматы
шахматам шахматам
ref: шахматах pred: шахмаце
ref: шахмат pred: шахматы
ref: шахматамі pred: шахматам
шахматы шахматы
штодзённага штодзённага
штодзённы штодзённы
штодзённае штодзённае
штодзённай штодзённай
штодзённаму штодзённаму
штодзённаму штодзённаму
штодзённаю штодзённаю
штодзённым штодзённым
штодзённым штодзённым
штодзённы штодзённы
штодзённыя штодзённыя
шыі шыі
шыям шыям
шыях шыях
шыі шыі
шый шый
шыі шыі
шыямі шыямі
шыяй шыяй
шыі шыі
шыя шыя
яркага яркага
яркую яркую
яркія яркія
яркай яркай
яркіх яркіх
яркаю яркаю
яркім яркім
яркім яркім
яркімі яркімі
яркі яркі
ячмень ячмень
ячменю ячменю
ячмені ячмені
ячменем ячменем
ячмень ячмень
італьянак італьянак
італьянку італьянку
італьянкам італьянкам
італьянцы італьянцы
італьянках італьянках
італьянцы італьянцы
італьянак італьянак
італьянкі італьянкі
італьянкамі італьянкамі
італьянкай італьянкай
італьянкі італьянкі
ўнікнем ўнікнем
ўнікнеце ўнікнеце
ўнікнеш ўнікнеш
ref: ўнікнуць pred: будуць ўнікнуць
ref: ўнікне pred: будзе ўнікну́ць
ўнікніце ўнікніце
ўнікні ўнікні
ўніклі ўніклі
ўнікла ўнікла
ref: ўнік pred: ўнікнуў
ўнікла ўнікла
0.734